//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------


#ifndef _SPOT_HARDWARE_USB_NATIVE_H_
#define _SPOT_HARDWARE_USB_NATIVE_H_

#include <TinyCLR_Interop.h>
struct Library_spot_hardware_usb_native_Microsoft_SPOT_Hardware_UsbClient_Configuration
{
    static const int FIELD__descriptors = 1;


    //--//

};

struct Library_spot_hardware_usb_native_Microsoft_SPOT_Hardware_UsbClient_Configuration__ClassDescriptor
{
    static const int FIELD__bDescriptorType = 1;
    static const int FIELD__payload         = 2;


    //--//

};

struct Library_spot_hardware_usb_native_Microsoft_SPOT_Hardware_UsbClient_UsbController
{
    static const int FIELD_STATIC__s_controllers = 0;
    static const int FIELD_STATIC__s_openStreams = 1;

    static const int FIELD__m_controllerIndex    = 1;
    static const int FIELD__m_configError        = 2;

    TINYCLR_NATIVE_DECLARE(get_Status___MicrosoftSPOTHardwareUsbClientUsbControllerPortState);
    TINYCLR_NATIVE_DECLARE(get_Configuration___MicrosoftSPOTHardwareUsbClientConfiguration);
    TINYCLR_NATIVE_DECLARE(set_Configuration___VOID__MicrosoftSPOTHardwareUsbClientConfiguration);
    TINYCLR_NATIVE_DECLARE(nativeStart___BOOLEAN);
    TINYCLR_NATIVE_DECLARE(nativeStop___BOOLEAN);
    TINYCLR_NATIVE_DECLARE(get_Count___STATIC__I4);

    //--//

};

struct Library_spot_hardware_usb_native_Microsoft_SPOT_Hardware_UsbClient_Configuration__Descriptor
{
    static const int FIELD__index = 1;


    //--//

};

struct Library_spot_hardware_usb_native_Microsoft_SPOT_Hardware_UsbClient_Configuration__ConfigurationDescriptor
{
    static const int FIELD__interfaces     = 2;
    static const int FIELD__iConfiguration = 3;
    static const int FIELD__bmAttributes   = 4;
    static const int FIELD__bMaxPower      = 5;


    //--//

};

struct Library_spot_hardware_usb_native_Microsoft_SPOT_Hardware_UsbClient_Configuration__DeviceDescriptor
{
    static const int FIELD__idVendor        = 2;
    static const int FIELD__idProduct       = 3;
    static const int FIELD__bcdDevice       = 4;
    static const int FIELD__iManufacturer   = 5;
    static const int FIELD__iProduct        = 6;
    static const int FIELD__iSerialNumber   = 7;
    static const int FIELD__bDeviceClass    = 8;
    static const int FIELD__bDeviceSubClass = 9;
    static const int FIELD__bDeviceProtocol = 10;
    static const int FIELD__bMaxPacketSize0 = 11;
    static const int FIELD__bcdUSB          = 12;


    //--//

};

struct Library_spot_hardware_usb_native_Microsoft_SPOT_Hardware_UsbClient_Configuration__Endpoint
{
    static const int FIELD__bEndpointAddress = 1;
    static const int FIELD__bmAttributes     = 2;
    static const int FIELD__wMaxPacketSize   = 3;
    static const int FIELD__bInterval        = 4;


    //--//

};

struct Library_spot_hardware_usb_native_Microsoft_SPOT_Hardware_UsbClient_Configuration__GenericDescriptor
{
    static const int FIELD__bmRequestType = 2;
    static const int FIELD__bRequest      = 3;
    static const int FIELD__wValue        = 4;
    static const int FIELD__wIndex        = 5;
    static const int FIELD__payload       = 6;


    //--//

};

struct Library_spot_hardware_usb_native_Microsoft_SPOT_Hardware_UsbClient_UsbStream
{
    static const int FIELD__m_disposed        = 1;
    static const int FIELD__m_streamIndex     = 2;
    static const int FIELD__m_controllerIndex = 3;
    static const int FIELD__WriteEndpoint     = 4;
    static const int FIELD__ReadEndpoint      = 5;

    TINYCLR_NATIVE_DECLARE(nativeOpen___I4__I4__I4);
    TINYCLR_NATIVE_DECLARE(nativeClose___VOID);
    TINYCLR_NATIVE_DECLARE(nativeRead___I4__SZARRAY_U1__I4__I4);
    TINYCLR_NATIVE_DECLARE(nativeWrite___I4__SZARRAY_U1__I4__I4);
    TINYCLR_NATIVE_DECLARE(nativeFlush___VOID);

    //--//

};

struct Library_spot_hardware_usb_native_Microsoft_SPOT_Hardware_UsbClient_Configuration__StringDescriptor
{
    static const int FIELD__sString = 2;


    //--//

};

struct Library_spot_hardware_usb_native_Microsoft_SPOT_Hardware_UsbClient_Configuration__UsbInterface
{
    static const int FIELD__bInterfaceNumber   = 1;
    static const int FIELD__endpoints          = 2;
    static const int FIELD__classDescriptors   = 3;
    static const int FIELD__bInterfaceClass    = 4;
    static const int FIELD__bInterfaceSubClass = 5;
    static const int FIELD__bInterfaceProtocol = 6;
    static const int FIELD__iInterface         = 7;


    //--//

};



extern const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_Microsoft_SPOT_Hardware_Usb;

#endif  //_SPOT_HARDWARE_USB_NATIVE_H_
