//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------


#ifndef _WINDOWS_DEVICES_NATIVE_H_
#define _WINDOWS_DEVICES_NATIVE_H_

#include <TinyCLR_Interop.h>
struct Library_windows_devices_native_Windows_Devices_Adc_AdcChannel
{
    static const int FIELD__m_channelNumber = 1;
    static const int FIELD__m_controller = 2;
    static const int FIELD__m_provider = 3;
    static const int FIELD__m_disposed = 4;


    //--//

};

struct Library_windows_devices_native_Windows_Devices_Adc_AdcController
{
    static const int FIELD__m_provider = 1;


    //--//

};

struct Library_windows_devices_native_Windows_Devices_Enumeration_DeviceInformation
{
    static const int FIELD__m_id = 1;
    static const int FIELD__m_isDefault = 2;


    //--//

};

struct Library_windows_devices_native_Windows_Devices_Gpio_GpioController
{
    static const int FIELD_STATIC__s_instance = 0;

    TINYCLR_NATIVE_DECLARE(get_PinCount___I4);

    //--//

};

struct Library_windows_devices_native_Windows_Devices_Gpio_GpioPin
{
    static const int FIELD_STATIC__s_eventListener = 1;

    static const int FIELD__m_syncLock = 1;
    static const int FIELD__m_disposed = 2;
    static const int FIELD__m_pinNumber = 3;
    static const int FIELD__m_driveMode = 4;
    static const int FIELD__m_lastOutputValue = 5;
    static const int FIELD__m_callbacks = 6;

    TINYCLR_NATIVE_DECLARE(get_DebounceTimeout___mscorlibSystemTimeSpan);
    TINYCLR_NATIVE_DECLARE(set_DebounceTimeout___VOID__mscorlibSystemTimeSpan);
    TINYCLR_NATIVE_DECLARE(Read___WindowsDevicesGpioGpioPinValue);
    TINYCLR_NATIVE_DECLARE(Write___VOID__WindowsDevicesGpioGpioPinValue);
    TINYCLR_NATIVE_DECLARE(InitNative___BOOLEAN__I4);
    TINYCLR_NATIVE_DECLARE(DisposeNative___VOID);
    TINYCLR_NATIVE_DECLARE(SetDriveModeInternal___VOID__WindowsDevicesGpioGpioPinDriveMode);

    //--//

};

struct Library_windows_devices_native_Windows_Devices_Gpio_GpioPinEvent
{
    static const int FIELD__PinNumber = 3;
    static const int FIELD__Edge = 4;


    //--//

};

struct Library_windows_devices_native_Windows_Devices_Gpio_GpioPinEventListener
{
    static const int FIELD__m_pinMap = 1;


    //--//

};

struct Library_windows_devices_native_Windows_Devices_Gpio_GpioPinValueChangedEventArgs
{
    static const int FIELD__m_edge = 1;


    //--//

};

struct Library_windows_devices_native_Windows_Devices_I2c_I2cConnectionSettings
{
    static const int FIELD__m_slaveAddress = 1;
    static const int FIELD__m_busSpeed = 2;
    static const int FIELD__m_sharingMode = 3;


    //--//

};

struct Library_windows_devices_native_Windows_Devices_I2c_I2cDevice
{
    static const int FIELD_STATIC__s_deviceLock = 2;
    static const int FIELD_STATIC__s_deviceRefs = 3;
    static const int FIELD_STATIC__s_device = 4;
    static const int FIELD_STATIC__s_I2cPrefix = 5;

    static const int FIELD__m_deviceId = 1;
    static const int FIELD__m_settings = 2;
    static const int FIELD__m_syncLock = 3;
    static const int FIELD__m_disposed = 4;
    static const int FIELD__m_configuration = 5;


    //--//

};

struct Library_windows_devices_native_Windows_Devices_I2c_I2cTransferResult
{
    static const int FIELD__Status = 1;
    static const int FIELD__BytesTransferred = 2;


    //--//

};

struct Library_windows_devices_native_Windows_Devices_Pwm_PwmController
{
    static const int FIELD__m_provider = 1;


    //--//

};

struct Library_windows_devices_native_Windows_Devices_Pwm_PwmPin
{
    static const int FIELD__m_pinNumber = 1;
    static const int FIELD__m_controller = 2;
    static const int FIELD__m_provider = 3;
    static const int FIELD__m_started = 4;
    static const int FIELD__m_disposed = 5;
    static const int FIELD__m_dutyCycle = 6;
    static const int FIELD__m_polarity = 7;


    //--//

};

struct Library_windows_devices_native_Windows_Devices_Spi_SpiBusInfo
{
    static const int FIELD__MinClockFrequency_ = 1;
    static const int FIELD__MaxClockFrequency_ = 2;
    static const int FIELD__ChipSelectLineCount_ = 3;

    TINYCLR_NATIVE_DECLARE(_ctor___VOID__I4);

    //--//

};

struct Library_windows_devices_native_Windows_Devices_Spi_SpiConnectionSettings
{
    static const int FIELD__m_chipSelectionLine = 1;
    static const int FIELD__m_dataBitLength = 2;
    static const int FIELD__m_clockFrequency = 3;
    static const int FIELD__m_mode = 4;
    static const int FIELD__m_sharingMode = 5;


    //--//

};

struct Library_windows_devices_native_Windows_Devices_Spi_SpiDevice
{
    static const int FIELD_STATIC__s_SpiPrefix = 6;

    static const int FIELD__m_busInfo = 1;
    static const int FIELD__m_deviceId = 2;
    static const int FIELD__m_settings = 3;
    static const int FIELD__m_disposed = 4;
    static const int FIELD__m_mskPin = 5;
    static const int FIELD__m_misoPin = 6;
    static const int FIELD__m_mosiPin = 7;
    static const int FIELD__m_spiBus = 8;

    TINYCLR_NATIVE_DECLARE(InitNative___VOID);
    TINYCLR_NATIVE_DECLARE(DisposeNative___VOID);
    TINYCLR_NATIVE_DECLARE(TransferInternal___VOID__SZARRAY_U1__SZARRAY_U1__BOOLEAN);

    //--//

};



extern const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_Windows_Devices;

#endif  //_WINDOWS_DEVICES_NATIVE_H_
