//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolutionWizard.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SolutionWizard.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Projects.
        /// </summary>
        internal static string AllProjects {
            get {
                return ResourceManager.GetString("AllProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to exit the Solution Wizard?.
        /// </summary>
        internal static string AreYouSureYouWantToExit {
            get {
                return ResourceManager.GetString("AreYouSureYouWantToExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author.
        /// </summary>
        internal static string Author {
            get {
                return ResourceManager.GetString("Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CLR Projects.
        /// </summary>
        internal static string CLRProjects {
            get {
                return ResourceManager.GetString("CLRProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debugger Port.
        /// </summary>
        internal static string DebuggerPort {
            get {
                return ResourceManager.GetString("DebuggerPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documentation.
        /// </summary>
        internal static string Documentation {
            get {
                return ResourceManager.GetString("Documentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must select at least one project..
        /// </summary>
        internal static string ErrorNoProjects {
            get {
                return ResourceManager.GetString("ErrorNoProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feature List.
        /// </summary>
        internal static string FeatureList {
            get {
                return ResourceManager.GetString("FeatureList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Features.
        /// </summary>
        internal static string Features {
            get {
                return ResourceManager.GetString("Features", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following is a description of the components of this solution.  Each solution consists of a set of projects which in turn have a set of features and libraries..
        /// </summary>
        internal static string FinalDescription {
            get {
                return ResourceManager.GetString("FinalDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The .NET Micro Framework Solution Wizard will create the &apos;{0}&apos; solution in the directory:.
        /// </summary>
        internal static string FinalTitle {
            get {
                return ResourceManager.GetString("FinalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate Template.
        /// </summary>
        internal static string GenerateTemplate {
            get {
                return ResourceManager.GetString("GenerateTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid data has been entered.
        /// </summary>
        internal static string InvalidData {
            get {
                return ResourceManager.GetString("InvalidData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid porting kit directory.  Please enter the root directory of the porting kit..
        /// </summary>
        internal static string InvalidPkDirectory {
            get {
                return ResourceManager.GetString("InvalidPkDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid solution name.  A solution name must contain only letters, numbers and underscores..
        /// </summary>
        internal static string InvalidSolutionName {
            get {
                return ResourceManager.GetString("InvalidSolutionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Libraries.
        /// </summary>
        internal static string Libraries {
            get {
                return ResourceManager.GetString("Libraries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Library Categories.
        /// </summary>
        internal static string LibraryCategories {
            get {
                return ResourceManager.GetString("LibraryCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading cloned solution, please wait ....
        /// </summary>
        internal static string LoadingClonedSolution {
            get {
                return ResourceManager.GetString("LoadingClonedSolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading features, please wait ....
        /// </summary>
        internal static string LoadingFeatures {
            get {
                return ResourceManager.GetString("LoadingFeatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading libraries, please wait ....
        /// </summary>
        internal static string LoadingLibraries {
            get {
                return ResourceManager.GetString("LoadingLibraries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading processors, please wait ....
        /// </summary>
        internal static string LoadingProcessors {
            get {
                return ResourceManager.GetString("LoadingProcessors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading projects, please wait ....
        /// </summary>
        internal static string LoadingProjects {
            get {
                return ResourceManager.GetString("LoadingProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading solution, please wait ....
        /// </summary>
        internal static string LoadingSolution {
            get {
                return ResourceManager.GetString("LoadingSolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading solutions, please wait ....
        /// </summary>
        internal static string LoadingSolutions {
            get {
                return ResourceManager.GetString("LoadingSolutions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Native Projects.
        /// </summary>
        internal static string NativeProjects {
            get {
                return ResourceManager.GetString("NativeProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not all library categories have been resolved!.
        /// </summary>
        internal static string NotAllLibrariesResolved {
            get {
                return ResourceManager.GetString("NotAllLibrariesResolved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No unresolved library categories.
        /// </summary>
        internal static string NoUnresolvedLibCats {
            get {
                return ResourceManager.GetString("NoUnresolvedLibCats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path.
        /// </summary>
        internal static string Path {
            get {
                return ResourceManager.GetString("Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processor.
        /// </summary>
        internal static string Processor {
            get {
                return ResourceManager.GetString("Processor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project.
        /// </summary>
        internal static string Project {
            get {
                return ResourceManager.GetString("Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Path.
        /// </summary>
        internal static string ProjectPath {
            get {
                return ResourceManager.GetString("ProjectPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Existing Solution File.
        /// </summary>
        internal static string SelectExistingSolution {
            get {
                return ResourceManager.GetString("SelectExistingSolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select .NET Micro Framework Porting Kit Directory.
        /// </summary>
        internal static string SelectMfPkDirectory {
            get {
                return ResourceManager.GetString("SelectMfPkDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a node to view its description.
        /// </summary>
        internal static string SelectToViewDescr {
            get {
                return ResourceManager.GetString("SelectToViewDescr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solution.
        /// </summary>
        internal static string Solution {
            get {
                return ResourceManager.GetString("Solution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solution Files.
        /// </summary>
        internal static string SolutionFiles {
            get {
                return ResourceManager.GetString("SolutionFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solution List.
        /// </summary>
        internal static string SolutionList {
            get {
                return ResourceManager.GetString("SolutionList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solutions.
        /// </summary>
        internal static string Solutions {
            get {
                return ResourceManager.GetString("Solutions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .NET Micro Framework Solution Wizard.
        /// </summary>
        internal static string SolutionWizard {
            get {
                return ResourceManager.GetString("SolutionWizard", resourceCulture);
            }
        }
        
        internal static System.Drawing.Icon SolutionWizard1 {
            get {
                object obj = ResourceManager.GetObject("SolutionWizard1", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wizard Cancelled.
        /// </summary>
        internal static string WizardCancelled {
            get {
                return ResourceManager.GetString("WizardCancelled", resourceCulture);
            }
        }
    }
}
