//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolutionWizard.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>MemCfg      = 2</string>
  <string>DbgPort     = 1</string>
  <string>RamBase     = 0x08000000</string>
  <string>RamSize     = 0x02000000</string>
  <string>FlashBase   = 0x10000000</string>
  <string>FlashSize   = 0x01000000</string>
  <string>ClockSpeed  = 16000000</string>
  <string>SlowClock   = 16000000</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection MC9328_Defaults {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["MC9328_Defaults"]));
            }
            set {
                this["MC9328_Defaults"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>MemCfg      = 2</string>
  <string>DbgPort     = 1</string>
  <string>RamBase     = 0xA0000000</string>
  <string>RamSize     = 0x02000000</string>
  <string>FlashBase   = 0x00000000</string>
  <string>FlashSize   = 0x02000000</string>
  <string>ClockSpeed  = 3250000</string>
  <string>SlowClock   = 3250000</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection PXA271_Defaults {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["PXA271_Defaults"]));
            }
            set {
                this["PXA271_Defaults"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>MemCfg      = 0</string>
  <string>DbgPort     = 0</string>
  <string>RamBase     = 0x00000000</string>
  <string>RamSize     = 0x00020000</string>
  <string>FlashBase   = 0x00100000</string>
  <string>FlashSize   = 0x00080000</string>
  <string>ClockSpeed  = 1500000</string>
  <string>SlowClock   = 1500000</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection AT91SAM7X_Defaults {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["AT91SAM7X_Defaults"]));
            }
            set {
                this["AT91SAM7X_Defaults"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>MemCfg      = 2</string>
  <string>DbgPort     = 0</string>
  <string>RamBase     = 0x20000000</string>
  <string>RamSize     = 0x04000000</string>
  <string>FlashBase   = 0x20000000</string>
  <string>FlashSize   = 0x04000000</string>
  <string>ClockSpeed  = 6208000</string>
  <string>SlowClock   = 32768</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection AT91SAM9261_Defaults {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["AT91SAM9261_Defaults"]));
            }
            set {
                this["AT91SAM9261_Defaults"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>MemCfg      = 2</string>
  <string>DbgPort     = 0</string>
  <string>RamBase     = 0x81000000</string>
  <string>RamSize     = 0x01000000</string>
  <string>FlashBase   = 0x80000000</string>
  <string>FlashSize   = 0x02000000</string>
  <string>ClockSpeed  = 15000000</string>
  <string>SlowClock   = 15000000</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection LPC22XX_Defaults {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["LPC22XX_Defaults"]));
            }
            set {
                this["LPC22XX_Defaults"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>MemCfg      = 2</string>
  <string>DbgPort     = 1</string>
  <string>RamBase     = 0x10000000</string>
  <string>RamSize     = 0x02000000</string>
  <string>FlashBase   = 0x00000000</string>
  <string>FlashSize   = 0x40000000</string>
  <string>ClockSpeed  = 16000000</string>
  <string>SlowClock   = 16000000</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection CORTEXM3_Defaults {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["CORTEXM3_Defaults"]));
            }
            set {
                this["CORTEXM3_Defaults"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>MemCfg      = 2</string>
  <string>DbgPort     = 0</string>
  <string>RamBase     = 0x00000000</string>
  <string>RamSize     = 0x04000000</string>
  <string>FlashBase   = 0x10000000</string>
  <string>FlashSize   = 0x00400000</string>
  <string>ClockSpeed  = 600000000</string>
  <string>SlowClock   = 600000000</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection BF537_Defaults {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["BF537_Defaults"]));
            }
            set {
                this["BF537_Defaults"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>MemCfg      = 2</string>
  <string>DbgPort     = 1</string>
  <string>RamBase     = 0x08000000</string>
  <string>RamSize     = 0x02000000</string>
  <string>FlashBase   = 0x10000000</string>
  <string>FlashSize   = 0x01000000</string>
  <string>ClockSpeed  = 16000000</string>
  <string>SlowClock   = 16000000</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection TEMPLATE_Defaults {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["TEMPLATE_Defaults"]));
            }
            set {
                this["TEMPLATE_Defaults"] = value;
            }
        }
    }
}
