////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// Copyright (c) Microsoft Corporation.  All rights reserved.
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

#include "spot_hardware_native.cpp"
#include "spot_hardware_native_Microsoft_SPOT_Hardware_AnalogInput.cpp"
#include "spot_hardware_native_Microsoft_SPOT_Hardware_AnalogOutput.cpp"
#include "spot_hardware_native_Microsoft_SPOT_Hardware_Battery.cpp"
#include "spot_hardware_native_Microsoft_SPOT_Hardware_Battery__ChargerModel.cpp"
#include "spot_hardware_native_Microsoft_SPOT_Hardware_Cpu.cpp"
#include "spot_hardware_native_Microsoft_SPOT_EventSink.cpp"
#include "spot_hardware_native_Microsoft_SPOT_Hardware_HardwareProvider.cpp"
#include "spot_hardware_native_Microsoft_SPOT_Hardware_I2CDevice.cpp"
#include "spot_hardware_native_Microsoft_SPOT_Hardware_I2CDevice__Configuration.cpp"
#include "spot_hardware_native_Microsoft_SPOT_Hardware_InputPort.cpp"
#include "spot_hardware_native_Microsoft_SPOT_Hardware_InterruptPort.cpp"
#include "spot_hardware_native_Microsoft_SPOT_Hardware_OutputPort.cpp"
#include "spot_hardware_native_Microsoft_SPOT_Hardware_Port.cpp"
#include "spot_hardware_native_Microsoft_SPOT_Hardware_PowerState.cpp"
#include "spot_hardware_native_Microsoft_SPOT_Hardware_SPI.cpp"
#include "spot_hardware_native_Microsoft_SPOT_Hardware_SPI__Configuration.cpp"
#include "spot_hardware_native_Microsoft_SPOT_Hardware_TristatePort.cpp"
#include "spot_hardware_native_Microsoft_SPOT_Hardware_NativeEventDispatcher_mshl.cpp"
#include "spot_hardware_native_Microsoft_SPOT_Hardware_Watchdog.cpp"
#include "spot_hardware_native_Microsoft_SPOT_Hardware_LargeBuffer.cpp"
