//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.21006.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MFDpwsTestCaseGenerator {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MFDpwsTestCaseGenerator.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Project DefaultTargets=&quot;Build&quot; xmlns=&quot;http://schemas.microsoft.com/developer/msbuild/2003&quot; ToolsVersion=&quot;4.0&quot;&gt;
        ///  &lt;PropertyGroup&gt;
        ///    &lt;OutputType&gt;Library&lt;/OutputType&gt;
        ///    &lt;ProjectTypeGuids&gt;{b69e3092-b931-443c-abe7-7e7b65f2a37f};{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}&lt;/ProjectTypeGuids&gt;
        ///    &lt;ProductVersion&gt;9.0.21022&lt;/ProductVersion&gt;
        ///    &lt;SchemaVersion&gt;2.0&lt;/SchemaVersion&gt;
        ///    &lt;TinyCLR_ClientOnly&gt;true&lt;/TinyCLR_ClientOnly&gt;
        ///  &lt;/PropertyGroup&gt;
        ///  &lt;Import Project=&quot;$(SPOCLIENT)\tools\Targets\Microsoft.SPOT.Te [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DevProjectTemplate {
            get {
                return ResourceManager.GetString("DevProjectTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Wix xmlns=&quot;http://schemas.microsoft.com/wix/2006/wi&quot;&gt;
        ///  &lt;Fragment Id=&quot;Fragment_DpwsTestFixtures&quot;&gt;
        ///    &lt;Feature Id=&quot;Feature_DpwsTestFixtures&quot;
        ///             Title=&quot;.NET Micro Framework Dpws Test Fixtures&quot;
        ///             Description=&quot;Test Fixtures for predefined web service definitions (.wsdl)&quot;
        ///             Display=&quot;hidden&quot;
        ///             Level=&quot;100&quot;&gt;
        ///       &lt;Condition Level=&quot;1&quot;&gt;SECRETCODE = &quot;What&quot;&lt;/Condition&gt;
        ///    &lt;/Feature&gt;
        ///  &lt;/Fragment&gt;
        ///&lt;/Wix&gt;.
        /// </summary>
        internal static string FeatureFragment {
            get {
                return ResourceManager.GetString("FeatureFragment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Wix xmlns=&quot;http://schemas.microsoft.com/wix/2006/wi&quot;&gt;
        ///  &lt;Module Id=&quot;Module_DPWSCodeGen&quot;
        ///    Language=&quot;1033&quot;
        ///    Version=&quot;1.0.0.0&quot;&gt;
        ///
        ///    &lt;Package
        ///      Id=&quot;3362f9b4-591f-41e9-8d1b-59bb53f0ea6e&quot;
        ///      Keywords=&quot;Installer&quot;
        ///      Description=&quot;.NET Micro Framework DPWS Code Gen Tests&quot;
        ///      Comments=&quot; enu; Copyright (C) Microsoft Corporation, All rights reserved.&quot;
        ///      Manufacturer=&quot;Microsoft Corporation&quot;
        ///      InstallerVersion=&quot;200&quot;
        ///      Languages=&quot;1033&quot;
        ///      SummaryCodepage=&quot;1252&quot; /&gt;
        ///
        ///    &lt;? [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MergeFragment {
            get {
                return ResourceManager.GetString("MergeFragment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Project DefaultTargets=&quot;Build&quot; xmlns=&quot;http://schemas.microsoft.com/developer/msbuild/2003&quot; ToolsVersion=&quot;4.0&quot;&gt;
        ///  &lt;PropertyGroup&gt;
        ///    &lt;OutputType&gt;Library&lt;/OutputType&gt;
        ///    &lt;ProjectTypeGuids&gt;{b69e3092-b931-443c-abe7-7e7b65f2a37f};{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}&lt;/ProjectTypeGuids&gt;
        ///    &lt;ProductVersion&gt;9.0.21022&lt;/ProductVersion&gt;
        ///    &lt;SchemaVersion&gt;2.0&lt;/SchemaVersion&gt;
        ///    &lt;NetMfTargetsBaseDir Condition=&quot;&apos;$(NetMfTargetsBaseDir)&apos;==&apos;&apos;&quot;&gt;$(MSBuild [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SDKProjectTemplate {
            get {
                return ResourceManager.GetString("SDKProjectTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Project DefaultTargets=&quot;Build&quot; xmlns=&quot;http://schemas.microsoft.com/developer/msbuild/2003&quot; ToolsVersion=&quot;4.0&quot;&gt;
        ///  &lt;PropertyGroup&gt;
        ///    &lt;DirectoryRef&gt;SamplesDir&lt;/DirectoryRef&gt;
        ///  &lt;/PropertyGroup&gt;
        ///  &lt;Import Project=&quot;$(SPOCLIENT)\tools\Targets\Microsoft.SPOT.WiX.Targets&quot; /&gt;
        ///&lt;/Project&gt;.
        /// </summary>
        internal static string SlnProjTemplate {
            get {
                return ResourceManager.GetString("SlnProjTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Project DefaultTargets=&quot;TinyCLR_Build&quot; xmlns=&quot;http://schemas.microsoft.com/developer/msbuild/2003&quot; ToolsVersion=&quot;4.0&quot;&gt;
        ///  &lt;Import Project=&quot;$(SPOCLIENT)\tools\targets\Microsoft.SPOT.Build.Setup.Targets&quot;/&gt;
        ///  &lt;PropertyGroup&gt;
        ///    &lt;OUTPUT_MSM_FILE&gt;DpwsTestFixtures.msm&lt;/OUTPUT_MSM_FILE&gt;
        ///    &lt;OUTPUT_MSM&gt;$(BUILD_TEST_TREE_SERVER)\msm\$(OUTPUT_MSM_FILE)&lt;/OUTPUT_MSM&gt;
        ///    &lt;LinkAllWiXObjects&gt;true&lt;/LinkAllWiXObjects&gt;
        ///  &lt;/PropertyGroup&gt;
        ///  &lt;Import Project=&quot;$(SPOCLIENT)\tools\Targets\Microsoft.SPOT.WiX.Targets&quot; /&gt;
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WixProjTemplate {
            get {
                return ResourceManager.GetString("WixProjTemplate", resourceCulture);
            }
        }
    }
}
