//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.SPOT.Debugger {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DiagnosticStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DiagnosticStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.SPOT.Debugger.DiagnosticStrings", typeof(DiagnosticStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding pe file {0} to deployment bundle.
        /// </summary>
        internal static string AddingPEtoBundle {
            get {
                return ResourceManager.GetString("AddingPEtoBundle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempting deployment....
        /// </summary>
        internal static string AtemptingDeployment {
            get {
                return ResourceManager.GetString("AtemptingDeployment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempting to attach to the device for debugging....
        /// </summary>
        internal static string Attach {
            get {
                return ResourceManager.GetString("Attach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attach failed..
        /// </summary>
        internal static string AttachFailed {
            get {
                return ResourceManager.GetString("AttachFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attach failed because  an internal error caused the process to terminate..
        /// </summary>
        internal static string AttachFailedProcessDied {
            get {
                return ResourceManager.GetString("AttachFailedProcessDied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attaching debugger engine....
        /// </summary>
        internal static string AttachingEngine {
            get {
                return ResourceManager.GetString("AttachingEngine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attaching to device....
        /// </summary>
        internal static string AttachingToDevice {
            get {
                return ResourceManager.GetString("AttachingToDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CorDebugProcess not properly initialized (m_pid == 0).
        /// </summary>
        internal static string BogusCorDebugProcess {
            get {
                return ResourceManager.GetString("BogusCorDebugProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ... cannot attach debugger engine!.
        /// </summary>
        internal static string CannotAttachEngine {
            get {
                return ResourceManager.GetString("CannotAttachEngine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verifying that the debugger target is initialized and ready for debugging..
        /// </summary>
        internal static string CheckTarget {
            get {
                return ResourceManager.GetString("CheckTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not reconnect to the debugging target after rebooting it..
        /// </summary>
        internal static string CouldNotReconnect {
            get {
                return ResourceManager.GetString("CouldNotReconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debugger engine could not attach to debugging target..
        /// </summary>
        internal static string DebugEngineAttachmentFailure {
            get {
                return ResourceManager.GetString("DebugEngineAttachmentFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The debugger engine thread has terminated unexpectedly with error &apos;{0}&apos;..
        /// </summary>
        internal static string DebuggerThreadTerminated {
            get {
                return ResourceManager.GetString("DebuggerThreadTerminated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device debugging starting....
        /// </summary>
        internal static string DebuggingStarting {
            get {
                return ResourceManager.GetString("DebuggingStarting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The debugging target could not be found..
        /// </summary>
        internal static string DebuggingTargetNotFound {
            get {
                return ResourceManager.GetString("DebuggingTargetNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Looking for the debugging target {0} to connect to (will time out in {1} seconds)....
        /// </summary>
        internal static string DebuggingTargetWait {
            get {
                return ResourceManager.GetString("DebuggingTargetWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deployment to the device was not successful..
        /// </summary>
        internal static string DeployFailed {
            get {
                return ResourceManager.GetString("DeployFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deployment error: the debugging failed to initialize because of device errors..
        /// </summary>
        internal static string DeploymentErrorDeviceErrors {
            get {
                return ResourceManager.GetString("DeploymentErrorDeviceErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deployment error: failed to (re)connect debugger engine to debugging target..
        /// </summary>
        internal static string DeploymentErrorReconnect {
            get {
                return ResourceManager.GetString("DeploymentErrorReconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deployment to the device was successful..
        /// </summary>
        internal static string DeploySucceeded {
            get {
                return ResourceManager.GetString("DeploySucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device &quot;{0}&quot; identified.
        /// </summary>
        internal static string DeviceFound {
            get {
                return ResourceManager.GetString("DeviceFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device &quot;{0}&quot; was not found.
        /// </summary>
        internal static string DeviceNotFound {
            get {
                return ResourceManager.GetString("DeviceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The debugger engine is listening to debug events from the debugging target.
        /// </summary>
        internal static string DispatchEvents {
            get {
                return ResourceManager.GetString("DispatchEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The debugger engine failed to receive any debug events from the debugging target.
        /// </summary>
        internal static string DispatchEventsFailed {
            get {
                return ResourceManager.GetString("DispatchEventsFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launching emulator with command line: &apos;{0}&apos;.
        /// </summary>
        internal static string EmulatorCommandLine {
            get {
                return ResourceManager.GetString("EmulatorCommandLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ... debugger engine attached!.
        /// </summary>
        internal static string EngineAttached {
            get {
                return ResourceManager.GetString("EngineAttached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found Assembly {0} {1}.
        /// </summary>
        internal static string FoundAssembly {
            get {
                return ResourceManager.GetString("FoundAssembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found device port &apos;{0}&apos; with ID &apos;{1}&apos; for transport &apos;{2}&apos;.
        /// </summary>
        internal static string FoundDevicePort {
            get {
                return ResourceManager.GetString("FoundDevicePort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Micro Framework installed on the device is of a version ({0}) incompatible with that of your project, which is {1}.
        /// </summary>
        internal static string FxVersionMismatch {
            get {
                return ResourceManager.GetString("FxVersionMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The debugging target and the debugger engine failed to initialize because of unspecified device errors..
        /// </summary>
        internal static string InitializationFailed {
            get {
                return ResourceManager.GetString("InitializationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The initialization of the debugging process failed..
        /// </summary>
        internal static string InitializeProcessFailed {
            get {
                return ResourceManager.GetString("InitializeProcessFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The initialization of the debugging process failed because an internal error caused the process to terminate..
        /// </summary>
        internal static string InitializeProcessFailedProcessDied {
            get {
                return ResourceManager.GetString("InitializeProcessFailedProcessDied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning: Attempting to deploy to an invalid port {0}..
        /// </summary>
        internal static string InvalidPort {
            get {
                return ResourceManager.GetString("InvalidPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempting to connect to device &apos;{0}:{1}&apos; Iteration {2}.
        /// </summary>
        internal static string Iteration {
            get {
                return ResourceManager.GetString("Iteration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The debugging target runtime is loading the application assemblies and starting execution..
        /// </summary>
        internal static string LoadAssemblies {
            get {
                return ResourceManager.GetString("LoadAssemblies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating information about assemblies on the debugging target..
        /// </summary>
        internal static string LoadedAssembliesInformation {
            get {
                return ResourceManager.GetString("LoadedAssembliesInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Looking for a device on transport &apos;{0}&apos;.
        /// </summary>
        internal static string LookingUpDevice {
            get {
                return ResourceManager.GetString("LookingUpDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opening port {0}.
        /// </summary>
        internal static string OpeningPort {
            get {
                return ResourceManager.GetString("OpeningPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port {0} not found!.
        /// </summary>
        internal static string PortNotFound {
            get {
                return ResourceManager.GetString("PortNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Querying device assemblies....
        /// </summary>
        internal static string QueryingDeviceAssemblies {
            get {
                return ResourceManager.GetString("QueryingDeviceAssemblies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The debugging target is not in an initialized state; rebooting....
        /// </summary>
        internal static string Rebooting {
            get {
                return ResourceManager.GetString("Rebooting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restarting interpreter....
        /// </summary>
        internal static string RestartingClr {
            get {
                return ResourceManager.GetString("RestartingClr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating thread list.
        /// </summary>
        internal static string RunningThreadsInformation {
            get {
                return ResourceManager.GetString("RunningThreadsInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preparing to deploy assemblies to the device..
        /// </summary>
        internal static string StartDeploy {
            get {
                return ResourceManager.GetString("StartDeploy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deployment of assemblies is starting. .
        /// </summary>
        internal static string StartDeployAssemblies {
            get {
                return ResourceManager.GetString("StartDeployAssemblies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Looking for the debugging target {0} to connect to (will time out in {1} seconds)....
        /// </summary>
        internal static string StartDeviceSearch {
            get {
                return ResourceManager.GetString("StartDeviceSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting device deployment....
        /// </summary>
        internal static string StartingDeviceDeployment {
            get {
                return ResourceManager.GetString("StartingDeviceDeployment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The debugging target initialized successfully..
        /// </summary>
        internal static string TargetInitializeSuccess {
            get {
                return ResourceManager.GetString("TargetInitializeSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to communicate with device {0}.
        /// </summary>
        internal static string UnableToCommunicate {
            get {
                return ResourceManager.GetString("UnableToCommunicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for VS debugger to wake up debuggee thread.
        /// </summary>
        internal static string WaitingForWakeup {
            get {
                return ResourceManager.GetString("WaitingForWakeup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for device to initialize....
        /// </summary>
        internal static string WaitingInitialize {
            get {
                return ResourceManager.GetString("WaitingInitialize", resourceCulture);
            }
        }
    }
}
