////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// Copyright (c) Microsoft Corporation.  All rights reserved.
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

using System;
using System.Reflection;
using Microsoft.SPOT.Platform.Test;

namespace Microsoft.SPOT.Platform.Tests
{

    public class Master
    {
        public static void Main()
        {
            string[] args = { "BasicCoverageTests", "BasicOtherTests" , "ClassClassTests", "ClassStructTests" , "StructClassTests", "StructStructTests" };
            MFTestRunner runner = new MFTestRunner(args);
        }
    }
//Baseline Doc for Conversions
//..\conformance\6_conversions\boxing (byte.cs) -- passed
//..\conformance\6_conversions\boxing (char.cs) -- passed
//..\conformance\6_conversions\boxing (double.cs) -- passed
//..\conformance\6_conversions\boxing (float.cs) -- passed
//..\conformance\6_conversions\boxing (int.cs) -- passed
//..\conformance\6_conversions\boxing (long.cs) -- passed
//..\conformance\6_conversions\boxing (sbyte.cs) -- passed
//..\conformance\6_conversions\boxing (short.cs) -- passed
//..\conformance\6_conversions\boxing (uint.cs) -- passed
//..\conformance\6_conversions\boxing (ulong.cs) -- passed
//..\conformance\6_conversions\boxing (ushort.cs) -- passed
//..\conformance\6_conversions\boxing (struct_to_ValType.cs) -- passed
//..\conformance\6_conversions\boxing (ValType_to_struct.cs) -- passed
//..\conformance\6_conversions\impref (ref_obj.cs) -- passed
//..\conformance\6_conversions\impref (class_class.cs) -- passed
//..\conformance\6_conversions\impref (class_inter.cs) -- passed
//..\conformance\6_conversions\impref (struct_inter.cs) -- passed
//..\conformance\6_conversions\impref (array_array.cs) -- passed
//..\conformance\6_conversions\impref (array_cloneable.cs) -- passed
//..\conformance\6_conversions\impref (null_ref.cs) -- passed
//..\conformance\6_conversions\impref (delegate_to_System.Delegate.cs) -- passed
//..\conformance\6_conversions\impref (delegate_to_System.ICloneable.cs) -- skipped
//..\conformance\6_conversions\expref (obj_ref.cs) -- passed
//..\conformance\6_conversions\expref (obj_ref_exc.cs) -- passed
//..\conformance\6_conversions\expref (class_class.cs) -- passed
//..\conformance\6_conversions\expref (class_class_exc.cs) -- passed
//..\conformance\6_conversions\expref (inter_struct.cs) -- passed
//..\conformance\6_conversions\expref (inter_struct_exc.cs) -- passed
//..\conformance\6_conversions\expref (class_inter.cs) -- passed
//..\conformance\6_conversions\expref (class_inter_exc.cs) -- passed
//..\conformance\6_conversions\expref (inter_class.cs) -- passed
//..\conformance\6_conversions\expref (inter_class2.cs) -- passed
//..\conformance\6_conversions\expref (inter_class2_exc1.cs) -- passed
//..\conformance\6_conversions\expref (inter_class2_exc2.cs) -- passed
//..\conformance\6_conversions\expref (inter_class_exc.cs) -- passed
//..\conformance\6_conversions\expref (inter_class_sealed.cs) -- passed
//..\conformance\6_conversions\expref (inter_class_sealed_exc.cs) -- passed
//..\conformance\6_conversions\expref (inter_inter.cs) -- passed
//..\conformance\6_conversions\expref (inter_inter_exc.cs) -- passed
//..\conformance\6_conversions\expenum (byte_to_byte_enum_rtime_s.cs) -- passed
//..\conformance\6_conversions\expenum (byte_to_int_enum_rtime_s.cs) -- passed
//..\conformance\6_conversions\expenum (byte_to_long_enum_rtime_s.cs) -- passed
//..\conformance\6_conversions\expenum (byte_to_sbyte_enum_rtime_s.cs) -- passed
//..\conformance\6_conversions\expenum (byte_to_short_enum_rtime_s.cs) -- passed
//..\conformance\6_conversions\expenum (byte_to_uint_enum_rtime_s.cs) -- passed
//..\conformance\6_conversions\expenum (byte_to_ulong_enum_rtime_s.cs) -- passed
//..\conformance\6_conversions\expenum (byte_to_ushort_enum_rtime_s.cs) -- passed
//..\conformance\6_conversions\expenum (double_to_byte_enum_rtime_s.cs) -- passed
//..\conformance\6_conversions\expenum (double_to_int_enum_rtime_s.cs) -- passed
//..\conformance\6_conversions\expenum (double_to_long_enum_rtime_s.cs) -- passed
//..\conformance\6_conversions\expenum (double_to_sbyte_enum_rtime_s.cs) -- passed
//..\conformance\6_conversions\expenum (double_to_short_enum_rtime_s.cs) -- passed
//..\conformance\6_conversions\expenum (double_to_uint_enum_rtime_s.cs) -- passed
//..\conformance\6_conversions\expenum (double_to_ulong_enum_rtime_s.cs) -- passed
//..\conformance\6_conversions\expenum (double_to_ushort_enum_rtime_s.cs) -- passed
//..\conformance\6_conversions\expenum (float_to_byte_enum_rtime_s.cs) -- passed
//..\conformance\6_conversions\expenum (float_to_int_enum_rtime_s.cs) -- passed
//..\conformance\6_conversions\expenum (float_to_long_enum_rtime_s.cs) -- passed
//..\conformance\6_conversions\expenum (float_to_sbyte_enum_rtime_s.cs) -- passed
//..\conformance\6_conversions\expenum (float_to_short_enum_rtime_s.cs) -- passed
//..\conformance\6_conversions\expenum (float_to_uint_enum_rtime_s.cs) -- passed
//..\conformance\6_conversions\expenum (float_to_ulong_enum_rtime_s.cs) -- passed
//..\conformance\6_conversions\expenum (float_to_ushort_enum_rtime_s.cs) -- passed
//..\conformance\6_conversions\expenum (short_enum_to_float_rtime_s.cs) -- passed
//..\conformance\6_conversions\expenum (short_enum_to_int_rtime_s.cs) -- passed
//..\conformance\6_conversions\expenum (int_to_byte_enum_rtime_s.cs) -- passed
//..\conformance\6_conversions\expenum (int_to_int_enum_rtime_s.cs) -- passed
//..\conformance\6_conversions\expenum (int_to_long_enum_rtime_s.cs) -- passed
//..\conformance\6_conversions\expenum (int_to_sbyte_enum_rtime_s.cs) -- passed
//..\conformance\6_conversions\expenum (int_to_short_enum_rtime_s.cs) -- passed
//..\conformance\6_conversions\expenum (int_to_uint_enum_rtime_s.cs) -- passed
//..\conformance\6_conversions\expenum (int_to_ulong_enum_rtime_s.cs) -- passed
//..\conformance\6_conversions\expenum (int_to_ushort_enum_rtime_s.cs) -- passed
//..\conformance\6_conversions\expenum (long_to_byte_enum_rtime_s.cs) -- passed
//..\conformance\6_conversions\expenum (long_to_int_enum_rtime_s.cs) -- passed
//..\conformance\6_conversions\expenum (long_to_long_enum_rtime_s.cs) -- passed
//..\conformance\6_conversions\expenum (long_to_sbyte_enum_rtime_s.cs) -- passed
//..\conformance\6_conversions\expenum (long_to_short_enum_rtime_s.cs) -- passed
//..\conformance\6_conversions\expenum (long_to_uint_enum_rtime_s.cs) -- passed
//..\conformance\6_conversions\expenum (long_to_ulong_enum_rtime_s.cs) -- passed
//..\conformance\6_conversions\expenum (long_to_ushort_enum_rtime_s.cs) -- passed
//..\conformance\6_conversions\expenum (sbyte_to_byte_enum_rtime_s.cs) -- passed
//..\conformance\6_conversions\expenum (sbyte_to_int_enum_rtime_s.cs) -- passed
//..\conformance\6_conversions\expenum (sbyte_to_long_enum_rtime_s.cs) -- passed
//..\conformance\6_conversions\expenum (sbyte_to_sbyte_enum_rtime_s.cs) -- passed
//..\conformance\6_conversions\expenum (sbyte_to_short_enum_rtime_s.cs) -- passed
//..\conformance\6_conversions\expenum (sbyte_to_uint_enum_rtime_s.cs) -- passed
//..\conformance\6_conversions\expenum (sbyte_to_ulong_enum_rtime_s.cs) -- passed
//..\conformance\6_conversions\expenum (sbyte_to_ushort_enum_rtime_s.cs) -- passed
//..\conformance\6_conversions\expenum (short_to_byte_enum_rtime_s.cs) -- passed
//..\conformance\6_conversions\expenum (short_to_int_enum_rtime_s.cs) -- passed
//..\conformance\6_conversions\expenum (short_to_long_enum_rtime_s.cs) -- passed
//..\conformance\6_conversions\expenum (short_to_sbyte_enum_rtime_s.cs) -- passed
//..\conformance\6_conversions\expenum (short_to_short_enum_rtime_s.cs) -- passed
//..\conformance\6_conversions\expenum (short_to_uint_enum_rtime_s.cs) -- passed
//..\conformance\6_conversions\expenum (short_to_ulong_enum_rtime_s.cs) -- passed
//..\conformance\6_conversions\expenum (short_to_ushort_enum_rtime_s.cs) -- passed
//..\conformance\6_conversions\expenum (uint_to_byte_enum_rtime_s.cs) -- passed
//..\conformance\6_conversions\expenum (uint_to_int_enum_rtime_s.cs) -- passed
//..\conformance\6_conversions\expenum (uint_to_long_enum_rtime_s.cs) -- passed
//..\conformance\6_conversions\expenum (uint_to_sbyte_enum_rtime_s.cs) -- passed
//..\conformance\6_conversions\expenum (uint_to_short_enum_rtime_s.cs) -- passed
//..\conformance\6_conversions\expenum (uint_to_uint_enum_rtime_s.cs) -- passed
//..\conformance\6_conversions\expenum (uint_to_ulong_enum_rtime_s.cs) -- passed
//..\conformance\6_conversions\expenum (uint_to_ushort_enum_rtime_s.cs) -- passed
//..\conformance\6_conversions\expenum (ulong_to_byte_enum_rtime_s.cs) -- passed
//..\conformance\6_conversions\expenum (ulong_to_int_enum_rtime_s.cs) -- passed
//..\conformance\6_conversions\expenum (ulong_to_long_enum_rtime_s.cs) -- passed
//..\conformance\6_conversions\expenum (ulong_to_sbyte_enum_rtime_s.cs) -- passed
//..\conformance\6_conversions\expenum (ulong_to_short_enum_rtime_s.cs) -- passed
//..\conformance\6_conversions\expenum (ulong_to_uint_enum_rtime_s.cs) -- passed
//..\conformance\6_conversions\expenum (ulong_to_ulong_enum_rtime_s.cs) -- passed
//..\conformance\6_conversions\expenum (ulong_to_ushort_enum_rtime_s.cs) -- passed
//..\conformance\6_conversions\expenum (ushort_to_byte_enum_rtime_s.cs) -- passed
//..\conformance\6_conversions\expenum (ushort_to_int_enum_rtime_s.cs) -- passed
//..\conformance\6_conversions\expenum (ushort_to_long_enum_rtime_s.cs) -- passed
//..\conformance\6_conversions\expenum (ushort_to_sbyte_enum_rtime_s.cs) -- passed
//..\conformance\6_conversions\expenum (ushort_to_short_enum_rtime_s.cs) -- passed
//..\conformance\6_conversions\expenum (ushort_to_uint_enum_rtime_s.cs) -- passed
//..\conformance\6_conversions\expenum (ushort_to_ulong_enum_rtime_s.cs) -- passed
//..\conformance\6_conversions\expenum (ushort_to_ushort_enum_rtime_s.cs) -- passed
//..\conformance\6_conversions\expenum (int_enum_to_ushort_rtime_s.cs) -- passed
//..\conformance\6_conversions\expenum (long_enum_to_byte_rtime_s.cs) -- passed
//..\conformance\6_conversions\expenum (long_enum_to_double_rtime_s.cs) -- passed
//..\conformance\6_conversions\expenum (long_enum_to_float_rtime_s.cs) -- passed
//..\conformance\6_conversions\expenum (long_enum_to_int_rtime_s.cs) -- passed
//..\conformance\6_conversions\expenum (long_enum_to_long_rtime_s.cs) -- passed
//..\conformance\6_conversions\expenum (long_enum_to_sbyte_rtime_s.cs) -- passed
//..\conformance\6_conversions\expenum (long_enum_to_short_rtime_s.cs) -- passed
//..\conformance\6_conversions\expenum (long_enum_to_uint_rtime_s.cs) -- passed
//..\conformance\6_conversions\expenum (long_enum_to_ulong_rtime_s.cs) -- passed
//..\conformance\6_conversions\expenum (long_enum_to_ushort_rtime_s.cs) -- passed
//..\conformance\6_conversions\expenum (sbyte_enum_to_byte_rtime_s.cs) -- passed
//..\conformance\6_conversions\expenum (sbyte_enum_to_double_rtime_s.cs) -- passed
//..\conformance\6_conversions\expenum (sbyte_enum_to_float_rtime_s.cs) -- passed
//..\conformance\6_conversions\expenum (sbyte_enum_to_int_rtime_s.cs) -- passed
//..\conformance\6_conversions\expenum (sbyte_enum_to_long_rtime_s.cs) -- passed
//..\conformance\6_conversions\expenum (sbyte_enum_to_sbyte_rtime_s.cs) -- passed
//..\conformance\6_conversions\expenum (sbyte_enum_to_short_rtime_s.cs) -- passed
//..\conformance\6_conversions\expenum (sbyte_enum_to_uint_rtime_s.cs) -- passed
//..\conformance\6_conversions\expenum (sbyte_enum_to_ulong_rtime_s.cs) -- passed
//..\conformance\6_conversions\expenum (sbyte_enum_to_ushort_rtime_s.cs) -- passed
//..\conformance\6_conversions\expenum (short_enum_to_byte_rtime_s.cs) -- passed
//..\conformance\6_conversions\expenum (short_enum_to_double_rtime_s.cs) -- passed
//..\conformance\6_conversions\expenum (short_enum_to_long_rtime_s.cs) -- passed
//..\conformance\6_conversions\expenum (short_enum_to_sbyte_rtime_s.cs) -- passed
//..\conformance\6_conversions\expenum (short_enum_to_short_rtime_s.cs) -- passed
//..\conformance\6_conversions\expenum (short_enum_to_uint_rtime_s.cs) -- passed
//..\conformance\6_conversions\expenum (short_enum_to_ulong_rtime_s.cs) -- passed
//..\conformance\6_conversions\expenum (short_enum_to_ushort_rtime_s.cs) -- passed
//..\conformance\6_conversions\expenum (uint_enum_to_byte_rtime_s.cs) -- passed
//..\conformance\6_conversions\expenum (uint_enum_to_double_rtime_s.cs) -- passed
//..\conformance\6_conversions\expenum (uint_enum_to_float_rtime_s.cs) -- passed
//..\conformance\6_conversions\expenum (uint_enum_to_int_rtime_s.cs) -- passed
//..\conformance\6_conversions\expenum (uint_enum_to_long_rtime_s.cs) -- passed
//..\conformance\6_conversions\expenum (uint_enum_to_sbyte_rtime_s.cs) -- passed
//..\conformance\6_conversions\expenum (uint_enum_to_short_rtime_s.cs) -- passed
//..\conformance\6_conversions\expenum (uint_enum_to_uint_rtime_s.cs) -- passed
//..\conformance\6_conversions\expenum (uint_enum_to_ulong_rtime_s.cs) -- passed
//..\conformance\6_conversions\expenum (uint_enum_to_ushort_rtime_s.cs) -- passed
//..\conformance\6_conversions\expenum (ulong_enum_to_byte_rtime_s.cs) -- passed
//..\conformance\6_conversions\expenum (ulong_enum_to_double_rtime_s.cs) -- passed
//..\conformance\6_conversions\expenum (ulong_enum_to_float_rtime_s.cs) -- passed
//..\conformance\6_conversions\expenum (ulong_enum_to_int_rtime_s.cs) -- passed
//..\conformance\6_conversions\expenum (ulong_enum_to_long_rtime_s.cs) -- passed
//..\conformance\6_conversions\expenum (ulong_enum_to_sbyte_rtime_s.cs) -- passed
//..\conformance\6_conversions\expenum (ulong_enum_to_short_rtime_s.cs) -- passed
//..\conformance\6_conversions\expenum (ulong_enum_to_uint_rtime_s.cs) -- passed
//..\conformance\6_conversions\expenum (ulong_enum_to_ulong_rtime_s.cs) -- passed
//..\conformance\6_conversions\expenum (ulong_enum_to_ushort_rtime_s.cs) -- passed
//..\conformance\6_conversions\expenum (ushort_enum_to_byte_rtime_s.cs) -- passed
//..\conformance\6_conversions\expenum (ushort_enum_to_double_rtime_s.cs) -- passed
//..\conformance\6_conversions\expenum (ushort_enum_to_float_rtime_s.cs) -- passed
//..\conformance\6_conversions\expenum (ushort_enum_to_int_rtime_s.cs) -- passed
//..\conformance\6_conversions\expenum (ushort_enum_to_long_rtime_s.cs) -- passed
//..\conformance\6_conversions\expenum (ushort_enum_to_sbyte_rtime_s.cs) -- passed
//..\conformance\6_conversions\expenum (ushort_enum_to_short_rtime_s.cs) -- passed
//..\conformance\6_conversions\expenum (ushort_enum_to_uint_rtime_s.cs) -- passed
//..\conformance\6_conversions\expenum (ushort_enum_to_ulong_rtime_s.cs) -- passed
//..\conformance\6_conversions\expenum (ushort_enum_to_ushort_rtime_s.cs) -- passed
//..\conformance\6_conversions\expenum (byte_enum_to_byte_rtime_s.cs) -- passed
//..\conformance\6_conversions\expenum (byte_enum_to_double_rtime_s.cs) -- passed
//..\conformance\6_conversions\expenum (byte_enum_to_float_rtime_s.cs) -- passed
//..\conformance\6_conversions\expenum (byte_enum_to_int_rtime_s.cs) -- passed
//..\conformance\6_conversions\expenum (byte_enum_to_long_rtime_s.cs) -- passed
//..\conformance\6_conversions\expenum (byte_enum_to_sbyte_rtime_s.cs) -- passed
//..\conformance\6_conversions\expenum (byte_enum_to_short_rtime_s.cs) -- passed
//..\conformance\6_conversions\expenum (byte_enum_to_uint_rtime_s.cs) -- passed
//..\conformance\6_conversions\expenum (byte_enum_to_ulong_rtime_s.cs) -- passed
//..\conformance\6_conversions\expenum (byte_enum_to_ushort_rtime_s.cs) -- passed
//..\conformance\6_conversions\expenum (int_enum_to_byte_rtime_s.cs) -- passed
//..\conformance\6_conversions\expenum (int_enum_to_double_rtime_s.cs) -- passed
//..\conformance\6_conversions\expenum (int_enum_to_float_rtime_s.cs) -- passed
//..\conformance\6_conversions\expenum (int_enum_to_int_rtime_s.cs) -- passed
//..\conformance\6_conversions\expenum (int_enum_to_long_rtime_s.cs) -- passed
//..\conformance\6_conversions\expenum (int_enum_to_sbyte_rtime_s.cs) -- passed
//..\conformance\6_conversions\expenum (int_enum_to_short_rtime_s.cs) -- passed
//..\conformance\6_conversions\expenum (int_enum_to_uint_rtime_s.cs) -- passed
//..\conformance\6_conversions\expenum (int_enum_to_ulong_rtime_s.cs) -- passed
//..\conformance\6_conversions\expenum (int_enum_to_ulong_enum_rtime_s.cs) -- passed
//..\conformance\6_conversions\expenum (int_enum_to_ushort_enum_rtime_s.cs) -- passed
//..\conformance\6_conversions\expenum (long_enum_to_byte_enum_rtime_s.cs) -- passed
//..\conformance\6_conversions\expenum (long_enum_to_int_enum_rtime_s.cs) -- passed
//..\conformance\6_conversions\expenum (long_enum_to_long_enum_rtime_s.cs) -- passed
//..\conformance\6_conversions\expenum (long_enum_to_sbyte_enum_rtime_s.cs) -- passed
//..\conformance\6_conversions\expenum (long_enum_to_short_enum_rtime_s.cs) -- passed
//..\conformance\6_conversions\expenum (long_enum_to_uint_enum_rtime_s.cs) -- passed
//..\conformance\6_conversions\expenum (long_enum_to_ulong_enum_rtime_s.cs) -- passed
//..\conformance\6_conversions\expenum (long_enum_to_ushort_enum_rtime_s.cs) -- passed
//..\conformance\6_conversions\expenum (sbyte_enum_to_byte_enum_rtime_s.cs) -- passed
//..\conformance\6_conversions\expenum (sbyte_enum_to_int_enum_rtime_s.cs) -- passed
//..\conformance\6_conversions\expenum (sbyte_enum_to_long_enum_rtime_s.cs) -- passed
//..\conformance\6_conversions\expenum (sbyte_enum_to_sbyte_enum_rtime_s.cs) -- passed
//..\conformance\6_conversions\expenum (sbyte_enum_to_short_enum_rtime_s.cs) -- passed
//..\conformance\6_conversions\expenum (sbyte_enum_to_uint_enum_rtime_s.cs) -- passed
//..\conformance\6_conversions\expenum (sbyte_enum_to_ulong_enum_rtime_s.cs) -- passed
//..\conformance\6_conversions\expenum (sbyte_enum_to_ushort_enum_rtime_s.cs) -- passed
//..\conformance\6_conversions\expenum (short_enum_to_byte_enum_rtime_s.cs) -- passed
//..\conformance\6_conversions\expenum (short_enum_to_int_enum_rtime_s.cs) -- passed
//..\conformance\6_conversions\expenum (short_enum_to_long_enum_rtime_s.cs) -- passed
//..\conformance\6_conversions\expenum (short_enum_to_sbyte_enum_rtime_s.cs) -- passed
//..\conformance\6_conversions\expenum (short_enum_to_short_enum_rtime_s.cs) -- passed
//..\conformance\6_conversions\expenum (short_enum_to_uint_enum_rtime_s.cs) -- passed
//..\conformance\6_conversions\expenum (short_enum_to_ulong_enum_rtime_s.cs) -- passed
//..\conformance\6_conversions\expenum (short_enum_to_ushort_enum_rtime_s.cs) -- passed
//..\conformance\6_conversions\expenum (uint_enum_to_byte_enum_rtime_s.cs) -- passed
//..\conformance\6_conversions\expenum (uint_enum_to_int_enum_rtime_s.cs) -- passed
//..\conformance\6_conversions\expenum (uint_enum_to_long_enum_rtime_s.cs) -- passed
//..\conformance\6_conversions\expenum (uint_enum_to_sbyte_enum_rtime_s.cs) -- passed
//..\conformance\6_conversions\expenum (uint_enum_to_short_enum_rtime_s.cs) -- passed
//..\conformance\6_conversions\expenum (uint_enum_to_uint_enum_rtime_s.cs) -- passed
//..\conformance\6_conversions\expenum (uint_enum_to_ulong_enum_rtime_s.cs) -- passed
//..\conformance\6_conversions\expenum (uint_enum_to_ushort_enum_rtime_s.cs) -- passed
//..\conformance\6_conversions\expenum (ulong_enum_to_byte_enum_rtime_s.cs) -- passed
//..\conformance\6_conversions\expenum (ulong_enum_to_int_enum_rtime_s.cs) -- passed
//..\conformance\6_conversions\expenum (ulong_enum_to_long_enum_rtime_s.cs) -- passed
//..\conformance\6_conversions\expenum (ulong_enum_to_sbyte_enum_rtime_s.cs) -- passed
//..\conformance\6_conversions\expenum (ulong_enum_to_short_enum_rtime_s.cs) -- passed
//..\conformance\6_conversions\expenum (ulong_enum_to_uint_enum_rtime_s.cs) -- passed
//..\conformance\6_conversions\expenum (ulong_enum_to_ulong_enum_rtime_s.cs) -- passed
//..\conformance\6_conversions\expenum (ulong_enum_to_ushort_enum_rtime_s.cs) -- passed
//..\conformance\6_conversions\expenum (ushort_enum_to_byte_enum_rtime_s.cs) -- passed
//..\conformance\6_conversions\expenum (ushort_enum_to_int_enum_rtime_s.cs) -- passed
//..\conformance\6_conversions\expenum (ushort_enum_to_long_enum_rtime_s.cs) -- passed
//..\conformance\6_conversions\expenum (ushort_enum_to_sbyte_enum_rtime_s.cs) -- passed
//..\conformance\6_conversions\expenum (ushort_enum_to_short_enum_rtime_s.cs) -- passed
//..\conformance\6_conversions\expenum (ushort_enum_to_uint_enum_rtime_s.cs) -- passed
//..\conformance\6_conversions\expenum (ushort_enum_to_ulong_enum_rtime_s.cs) -- passed
//..\conformance\6_conversions\expenum (ushort_enum_to_ushort_enum_rtime_s.cs) -- passed
//..\conformance\6_conversions\expenum (byte_enum_to_byte_enum_rtime_s.cs) -- passed
//..\conformance\6_conversions\expenum (byte_enum_to_int_enum_rtime_s.cs) -- passed
//..\conformance\6_conversions\expenum (byte_enum_to_long_enum_rtime_s.cs) -- passed
//..\conformance\6_conversions\expenum (byte_enum_to_sbyte_enum_rtime_s.cs) -- passed
//..\conformance\6_conversions\expenum (byte_enum_to_short_enum_rtime_s.cs) -- passed
//..\conformance\6_conversions\expenum (byte_enum_to_uint_enum_rtime_s.cs) -- passed
//..\conformance\6_conversions\expenum (byte_enum_to_ulong_enum_rtime_s.cs) -- passed
//..\conformance\6_conversions\expenum (byte_enum_to_ushort_enum_rtime_s.cs) -- passed
//..\conformance\6_conversions\expenum (int_enum_to_byte_enum_rtime_s.cs) -- passed
//..\conformance\6_conversions\expenum (int_enum_to_int_enum_rtime_s.cs) -- passed
//..\conformance\6_conversions\expenum (int_enum_to_long_enum_rtime_s.cs) -- passed
//..\conformance\6_conversions\expenum (int_enum_to_sbyte_enum_rtime_s.cs) -- passed
//..\conformance\6_conversions\expenum (int_enum_to_short_enum_rtime_s.cs) -- passed
//..\conformance\6_conversions\expenum (int_enum_to_uint_enum_rtime_s.cs) -- passed
//..\conformance\6_conversions\impenum (IComparable001.cs) -- skipped
//..\conformance\6_conversions\impenum (IComparable002.cs) -- skipped
//..\conformance\6_conversions\impenum (IComparable003.cs) -- skipped
//..\conformance\6_conversions\impenum (IComparable004.cs) -- skipped
//..\conformance\6_conversions\impenum (zero.cs) -- passed
//..\conformance\6_conversions\expenum\extended (byte_ebyte_E_1.cs) -- failed
//..\conformance\6_conversions\expenum\extended (byte_ebyte_E_2.cs) -- failed
//..\conformance\6_conversions\expenum\extended (byte_ebyte_E_3.cs) -- failed
//..\conformance\6_conversions\expenum\extended (byte_esbyte_E_1.cs) -- failed
//..\conformance\6_conversions\expenum\extended (byte_esbyte_E_2.cs) -- failed
//..\conformance\6_conversions\expenum\extended (byte_eushort_E_1.cs) -- failed
//..\conformance\6_conversions\expenum\extended (byte_euint_E_1.cs) -- failed
//..\conformance\6_conversions\expenum\extended (byte_eulong_E_1.cs) -- failed
//..\conformance\6_conversions\expenum\extended (byte_eshort_E_1.cs) -- failed
//..\conformance\6_conversions\expenum\extended (byte_eint_E_1.cs) -- failed
//..\conformance\6_conversions\expenum\extended (byte_elong_E_1.cs) -- failed
//..\conformance\6_conversions\expenum\extended (double_ebyte_E_1.cs) -- failed
//..\conformance\6_conversions\expenum\extended (double_ebyte_E_2.cs) -- failed
//..\conformance\6_conversions\expenum\extended (double_ebyte_E_3.cs) -- failed
//..\conformance\6_conversions\expenum\extended (double_ebyte_E_4.cs) -- passed
//..\conformance\6_conversions\expenum\extended (double_esbyte_E_1.cs) -- failed
//..\conformance\6_conversions\expenum\extended (double_esbyte_E_2.cs) -- failed
//..\conformance\6_conversions\expenum\extended (double_esbyte_E_3.cs) -- failed
//..\conformance\6_conversions\expenum\extended (double_esbyte_E_4.cs) -- passed
//..\conformance\6_conversions\expenum\extended (double_eushort_E_1.cs) -- failed
//..\conformance\6_conversions\expenum\extended (double_eushort_E_2.cs) -- failed
//..\conformance\6_conversions\expenum\extended (double_eushort_E_3.cs) -- failed
//..\conformance\6_conversions\expenum\extended (double_eushort_E_4.cs) -- passed
//..\conformance\6_conversions\expenum\extended (double_euint_E_1.cs) -- failed
//..\conformance\6_conversions\expenum\extended (double_euint_E_2.cs) -- failed
//..\conformance\6_conversions\expenum\extended (double_euint_E_3.cs) -- failed
//..\conformance\6_conversions\expenum\extended (double_euint_E_4.cs) -- passed
//..\conformance\6_conversions\expenum\extended (double_eulong_E_1.cs) -- failed
//..\conformance\6_conversions\expenum\extended (double_eshort_E_1.cs) -- failed
//..\conformance\6_conversions\expenum\extended (double_eshort_E_2.cs) -- failed
//..\conformance\6_conversions\expenum\extended (double_eshort_E_3.cs) -- failed
//..\conformance\6_conversions\expenum\extended (double_eshort_E_4.cs) -- passed
//..\conformance\6_conversions\expenum\extended (double_eint_E_1.cs) -- failed
//..\conformance\6_conversions\expenum\extended (double_eint_E_2.cs) -- failed
//..\conformance\6_conversions\expenum\extended (double_eint_E_3.cs) -- failed
//..\conformance\6_conversions\expenum\extended (double_eint_E_4.cs) -- passed
//..\conformance\6_conversions\expenum\extended (double_elong_E_1.cs) -- failed
//..\conformance\6_conversions\expenum\extended (ebyte_byte_E_1.cs) -- failed
//..\conformance\6_conversions\expenum\extended (ebyte_byte_E_2.cs) -- failed
//..\conformance\6_conversions\expenum\extended (ebyte_byte_E_3.cs) -- failed
//..\conformance\6_conversions\expenum\extended (ebyte_sbyte_E_1.cs) -- failed
//..\conformance\6_conversions\expenum\extended (ebyte_sbyte_E_2.cs) -- failed
//..\conformance\6_conversions\expenum\extended (ebyte_ushort_E_1.cs) -- failed
//..\conformance\6_conversions\expenum\extended (ebyte_uint_E_1.cs) -- failed
//..\conformance\6_conversions\expenum\extended (ebyte_ulong_E_1.cs) -- failed
//..\conformance\6_conversions\expenum\extended (ebyte_short_E_1.cs) -- failed
//..\conformance\6_conversions\expenum\extended (ebyte_int_E_1.cs) -- failed
//..\conformance\6_conversions\expenum\extended (ebyte_long_E_1.cs) -- failed
//..\conformance\6_conversions\expenum\extended (ebyte_float_E_1.cs) -- failed
//..\conformance\6_conversions\expenum\extended (ebyte_double_E_1.cs) -- failed
//..\conformance\6_conversions\expenum\extended (ebyte_esbyte_E_1.cs) -- failed
//..\conformance\6_conversions\expenum\extended (ebyte_esbyte_E_2.cs) -- failed
//..\conformance\6_conversions\expenum\extended (ebyte_eushort_E_1.cs) -- failed
//..\conformance\6_conversions\expenum\extended (ebyte_euint_E_1.cs) -- failed
//..\conformance\6_conversions\expenum\extended (ebyte_eulong_E_1.cs) -- failed
//..\conformance\6_conversions\expenum\extended (ebyte_eshort_E_1.cs) -- failed
//..\conformance\6_conversions\expenum\extended (ebyte_eint_E_1.cs) -- failed
//..\conformance\6_conversions\expenum\extended (ebyte_elong_E_1.cs) -- failed
//..\conformance\6_conversions\expenum\extended (eint_byte_E_1.cs) -- failed
//..\conformance\6_conversions\expenum\extended (eint_byte_E_2.cs) -- failed
//..\conformance\6_conversions\expenum\extended (eint_byte_E_3.cs) -- failed
//..\conformance\6_conversions\expenum\extended (eint_byte_E_4.cs) -- failed
//..\conformance\6_conversions\expenum\extended (eint_sbyte_E_1.cs) -- failed
//..\conformance\6_conversions\expenum\extended (eint_sbyte_E_2.cs) -- failed
//..\conformance\6_conversions\expenum\extended (eint_sbyte_E_3.cs) -- failed
//..\conformance\6_conversions\expenum\extended (eint_sbyte_E_4.cs) -- failed
//..\conformance\6_conversions\expenum\extended (eint_ushort_E_1.cs) -- failed
//..\conformance\6_conversions\expenum\extended (eint_ushort_E_2.cs) -- failed
//..\conformance\6_conversions\expenum\extended (eint_ushort_E_3.cs) -- failed
//..\conformance\6_conversions\expenum\extended (eint_ushort_E_4.cs) -- failed
//..\conformance\6_conversions\expenum\extended (eint_uint_E_1.cs) -- failed
//..\conformance\6_conversions\expenum\extended (eint_uint_E_2.cs) -- failed
//..\conformance\6_conversions\expenum\extended (eint_uint_E_3.cs) -- failed
//..\conformance\6_conversions\expenum\extended (eint_ulong_E_1.cs) -- failed
//..\conformance\6_conversions\expenum\extended (eint_short_E_1.cs) -- failed
//..\conformance\6_conversions\expenum\extended (eint_short_E_2.cs) -- failed
//..\conformance\6_conversions\expenum\extended (eint_short_E_3.cs) -- failed
//..\conformance\6_conversions\expenum\extended (eint_short_E_4.cs) -- failed
//..\conformance\6_conversions\expenum\extended (eint_int_E_1.cs) -- failed
//..\conformance\6_conversions\expenum\extended (eint_int_E_2.cs) -- failed
//..\conformance\6_conversions\expenum\extended (eint_int_E_3.cs) -- failed
//..\conformance\6_conversions\expenum\extended (eint_long_E_1.cs) -- failed
//..\conformance\6_conversions\expenum\extended (eint_float_E_1.cs) -- failed
//..\conformance\6_conversions\expenum\extended (eint_double_E_1.cs) -- failed
//..\conformance\6_conversions\expenum\extended (eint_esbyte_E_1.cs) -- failed
//..\conformance\6_conversions\expenum\extended (eint_esbyte_E_2.cs) -- failed
//..\conformance\6_conversions\expenum\extended (eint_esbyte_E_3.cs) -- failed
//..\conformance\6_conversions\expenum\extended (eint_esbyte_E_4.cs) -- failed
//..\conformance\6_conversions\expenum\extended (eint_ebyte_E_1.cs) -- failed
//..\conformance\6_conversions\expenum\extended (eint_ebyte_E_2.cs) -- failed
//..\conformance\6_conversions\expenum\extended (eint_ebyte_E_3.cs) -- failed
//..\conformance\6_conversions\expenum\extended (eint_ebyte_E_4.cs) -- failed
//..\conformance\6_conversions\expenum\extended (eint_eushort_E_1.cs) -- failed
//..\conformance\6_conversions\expenum\extended (eint_eushort_E_2.cs) -- failed
//..\conformance\6_conversions\expenum\extended (eint_eushort_E_3.cs) -- failed
//..\conformance\6_conversions\expenum\extended (eint_eushort_E_4.cs) -- failed
//..\conformance\6_conversions\expenum\extended (eint_eshort_E_1.cs) -- failed
//..\conformance\6_conversions\expenum\extended (eint_eshort_E_2.cs) -- failed
//..\conformance\6_conversions\expenum\extended (eint_eshort_E_3.cs) -- failed
//..\conformance\6_conversions\expenum\extended (eint_eshort_E_4.cs) -- failed
//..\conformance\6_conversions\expenum\extended (eint_euint_E_1.cs) -- failed
//..\conformance\6_conversions\expenum\extended (eint_euint_E_2.cs) -- failed
//..\conformance\6_conversions\expenum\extended (eint_euint_E_3.cs) -- failed
//..\conformance\6_conversions\expenum\extended (eint_eulong_E_1.cs) -- failed
//..\conformance\6_conversions\expenum\extended (eint_elong_E_1.cs) -- failed
//..\conformance\6_conversions\expenum\extended (elong_byte_E_1.cs) -- failed
//..\conformance\6_conversions\expenum\extended (elong_byte_E_2.cs) -- failed
//..\conformance\6_conversions\expenum\extended (elong_byte_E_3.cs) -- failed
//..\conformance\6_conversions\expenum\extended (elong_byte_E_4.cs) -- failed
//..\conformance\6_conversions\expenum\extended (elong_sbyte_E_1.cs) -- failed
//..\conformance\6_conversions\expenum\extended (elong_sbyte_E_2.cs) -- failed
//..\conformance\6_conversions\expenum\extended (elong_sbyte_E_3.cs) -- failed
//..\conformance\6_conversions\expenum\extended (elong_sbyte_E_4.cs) -- failed
//..\conformance\6_conversions\expenum\extended (elong_ushort_E_1.cs) -- failed
//..\conformance\6_conversions\expenum\extended (elong_ushort_E_2.cs) -- failed
//..\conformance\6_conversions\expenum\extended (elong_ushort_E_3.cs) -- failed
//..\conformance\6_conversions\expenum\extended (elong_ushort_E_4.cs) -- failed
//..\conformance\6_conversions\expenum\extended (elong_uint_E_1.cs) -- failed
//..\conformance\6_conversions\expenum\extended (elong_uint_E_2.cs) -- failed
//..\conformance\6_conversions\expenum\extended (elong_uint_E_3.cs) -- failed
//..\conformance\6_conversions\expenum\extended (elong_uint_E_4.cs) -- failed
//..\conformance\6_conversions\expenum\extended (elong_ulong_E_1.cs) -- failed
//..\conformance\6_conversions\expenum\extended (elong_ulong_E_2.cs) -- failed
//..\conformance\6_conversions\expenum\extended (elong_short_E_1.cs) -- failed
//..\conformance\6_conversions\expenum\extended (elong_short_E_2.cs) -- failed
//..\conformance\6_conversions\expenum\extended (elong_short_E_3.cs) -- failed
//..\conformance\6_conversions\expenum\extended (elong_short_E_4.cs) -- failed
//..\conformance\6_conversions\expenum\extended (elong_int_E_1.cs) -- failed
//..\conformance\6_conversions\expenum\extended (elong_int_E_2.cs) -- failed
//..\conformance\6_conversions\expenum\extended (elong_int_E_3.cs) -- failed
//..\conformance\6_conversions\expenum\extended (elong_int_E_4.cs) -- failed
//..\conformance\6_conversions\expenum\extended (elong_long_E_1.cs) -- failed
//..\conformance\6_conversions\expenum\extended (elong_long_E_2.cs) -- failed
//..\conformance\6_conversions\expenum\extended (elong_long_E_3.cs) -- failed
//..\conformance\6_conversions\expenum\extended (elong_float_E_1.cs) -- failed
//..\conformance\6_conversions\expenum\extended (elong_double_E_1.cs) -- failed
//..\conformance\6_conversions\expenum\extended (elong_esbyte_E_1.cs) -- failed
//..\conformance\6_conversions\expenum\extended (elong_esbyte_E_2.cs) -- failed
//..\conformance\6_conversions\expenum\extended (elong_esbyte_E_3.cs) -- failed
//..\conformance\6_conversions\expenum\extended (elong_esbyte_E_4.cs) -- failed
//..\conformance\6_conversions\expenum\extended (elong_ebyte_E_1.cs) -- failed
//..\conformance\6_conversions\expenum\extended (elong_ebyte_E_2.cs) -- failed
//..\conformance\6_conversions\expenum\extended (elong_ebyte_E_3.cs) -- failed
//..\conformance\6_conversions\expenum\extended (elong_ebyte_E_4.cs) -- failed
//..\conformance\6_conversions\expenum\extended (elong_eushort_E_1.cs) -- failed
//..\conformance\6_conversions\expenum\extended (elong_eushort_E_2.cs) -- failed
//..\conformance\6_conversions\expenum\extended (elong_eushort_E_3.cs) -- failed
//..\conformance\6_conversions\expenum\extended (elong_eushort_E_4.cs) -- failed
//..\conformance\6_conversions\expenum\extended (elong_eshort_E_1.cs) -- failed
//..\conformance\6_conversions\expenum\extended (elong_eshort_E_2.cs) -- failed
//..\conformance\6_conversions\expenum\extended (elong_eshort_E_3.cs) -- failed
//..\conformance\6_conversions\expenum\extended (elong_eshort_E_4.cs) -- failed
//..\conformance\6_conversions\expenum\extended (elong_eint_E_1.cs) -- failed
//..\conformance\6_conversions\expenum\extended (elong_eint_E_2.cs) -- failed
//..\conformance\6_conversions\expenum\extended (elong_eint_E_3.cs) -- failed
//..\conformance\6_conversions\expenum\extended (elong_eint_E_4.cs) -- failed
//..\conformance\6_conversions\expenum\extended (elong_euint_E_1.cs) -- failed
//..\conformance\6_conversions\expenum\extended (elong_euint_E_2.cs) -- failed
//..\conformance\6_conversions\expenum\extended (elong_euint_E_3.cs) -- failed
//..\conformance\6_conversions\expenum\extended (elong_euint_E_4.cs) -- failed
//..\conformance\6_conversions\expenum\extended (elong_eulong_E_1.cs) -- failed
//..\conformance\6_conversions\expenum\extended (elong_eulong_E_2.cs) -- failed
//..\conformance\6_conversions\expenum\extended (esbyte_byte_E_1.cs) -- failed
//..\conformance\6_conversions\expenum\extended (esbyte_byte_E_2.cs) -- failed
//..\conformance\6_conversions\expenum\extended (esbyte_byte_E_3.cs) -- failed
//..\conformance\6_conversions\expenum\extended (esbyte_sbyte_E_1.cs) -- failed
//..\conformance\6_conversions\expenum\extended (esbyte_sbyte_E_2.cs) -- failed
//..\conformance\6_conversions\expenum\extended (esbyte_sbyte_E_3.cs) -- failed
//..\conformance\6_conversions\expenum\extended (esbyte_ushort_E_1.cs) -- failed
//..\conformance\6_conversions\expenum\extended (esbyte_uint_E_1.cs) -- failed
//..\conformance\6_conversions\expenum\extended (esbyte_ulong_E_1.cs) -- failed
//..\conformance\6_conversions\expenum\extended (esbyte_short_E_1.cs) -- failed
//..\conformance\6_conversions\expenum\extended (esbyte_int_E_1.cs) -- failed
//..\conformance\6_conversions\expenum\extended (esbyte_long_E_1.cs) -- failed
//..\conformance\6_conversions\expenum\extended (esbyte_float_E_1.cs) -- failed
//..\conformance\6_conversions\expenum\extended (esbyte_double_E_1.cs) -- failed
//..\conformance\6_conversions\expenum\extended (esbyte_ebyte_E_1.cs) -- failed
//..\conformance\6_conversions\expenum\extended (esbyte_ebyte_E_2.cs) -- failed
//..\conformance\6_conversions\expenum\extended (esbyte_ebyte_E_3.cs) -- failed
//..\conformance\6_conversions\expenum\extended (esbyte_eushort_E_1.cs) -- failed
//..\conformance\6_conversions\expenum\extended (esbyte_euint_E_1.cs) -- failed
//..\conformance\6_conversions\expenum\extended (esbyte_eulong_E_1.cs) -- failed
//..\conformance\6_conversions\expenum\extended (esbyte_eshort_E_1.cs) -- failed
//..\conformance\6_conversions\expenum\extended (esbyte_eint_E_1.cs) -- failed
//..\conformance\6_conversions\expenum\extended (esbyte_elong_E_1.cs) -- failed
//..\conformance\6_conversions\expenum\extended (eshort_byte_E_1.cs) -- failed
//..\conformance\6_conversions\expenum\extended (eshort_byte_E_2.cs) -- failed
//..\conformance\6_conversions\expenum\extended (eshort_byte_E_3.cs) -- failed
//..\conformance\6_conversions\expenum\extended (eshort_byte_E_4.cs) -- failed
//..\conformance\6_conversions\expenum\extended (eshort_sbyte_E_1.cs) -- failed
//..\conformance\6_conversions\expenum\extended (eshort_sbyte_E_2.cs) -- failed
//..\conformance\6_conversions\expenum\extended (eshort_sbyte_E_3.cs) -- failed
//..\conformance\6_conversions\expenum\extended (eshort_sbyte_E_4.cs) -- failed
//..\conformance\6_conversions\expenum\extended (eshort_ushort_E_1.cs) -- failed
//..\conformance\6_conversions\expenum\extended (eshort_ushort_E_2.cs) -- failed
//..\conformance\6_conversions\expenum\extended (eshort_ushort_E_3.cs) -- failed
//..\conformance\6_conversions\expenum\extended (eshort_uint_E_1.cs) -- failed
//..\conformance\6_conversions\expenum\extended (eshort_ulong_E_1.cs) -- failed
//..\conformance\6_conversions\expenum\extended (eshort_short_E_1.cs) -- failed
//..\conformance\6_conversions\expenum\extended (eshort_short_E_2.cs) -- failed
//..\conformance\6_conversions\expenum\extended (eshort_short_E_3.cs) -- failed
//..\conformance\6_conversions\expenum\extended (eshort_int_E_1.cs) -- failed
//..\conformance\6_conversions\expenum\extended (eshort_long_E_1.cs) -- failed
//..\conformance\6_conversions\expenum\extended (eshort_float_E_1.cs) -- failed
//..\conformance\6_conversions\expenum\extended (eshort_double_E_1.cs) -- failed
//..\conformance\6_conversions\expenum\extended (eshort_esbyte_E_1.cs) -- failed
//..\conformance\6_conversions\expenum\extended (eshort_esbyte_E_2.cs) -- failed
//..\conformance\6_conversions\expenum\extended (eshort_esbyte_E_3.cs) -- failed
//..\conformance\6_conversions\expenum\extended (eshort_esbyte_E_4.cs) -- failed
//..\conformance\6_conversions\expenum\extended (eshort_ebyte_E_1.cs) -- failed
//..\conformance\6_conversions\expenum\extended (eshort_ebyte_E_2.cs) -- failed
//..\conformance\6_conversions\expenum\extended (eshort_ebyte_E_3.cs) -- failed
//..\conformance\6_conversions\expenum\extended (eshort_ebyte_E_4.cs) -- failed
//..\conformance\6_conversions\expenum\extended (eshort_eushort_E_1.cs) -- failed
//..\conformance\6_conversions\expenum\extended (eshort_eushort_E_2.cs) -- failed
//..\conformance\6_conversions\expenum\extended (eshort_eushort_E_3.cs) -- failed
//..\conformance\6_conversions\expenum\extended (eshort_euint_E_1.cs) -- failed
//..\conformance\6_conversions\expenum\extended (eshort_eulong_E_1.cs) -- failed
//..\conformance\6_conversions\expenum\extended (eshort_eint_E_1.cs) -- failed
//..\conformance\6_conversions\expenum\extended (eshort_elong_E_1.cs) -- failed
//..\conformance\6_conversions\expenum\extended (euint_byte_E_1.cs) -- failed
//..\conformance\6_conversions\expenum\extended (euint_byte_E_2.cs) -- failed
//..\conformance\6_conversions\expenum\extended (euint_byte_E_3.cs) -- failed
//..\conformance\6_conversions\expenum\extended (euint_sbyte_E_1.cs) -- failed
//..\conformance\6_conversions\expenum\extended (euint_sbyte_E_2.cs) -- failed
//..\conformance\6_conversions\expenum\extended (euint_ushort_E_1.cs) -- failed
//..\conformance\6_conversions\expenum\extended (euint_ushort_E_2.cs) -- failed
//..\conformance\6_conversions\expenum\extended (euint_ushort_E_3.cs) -- failed
//..\conformance\6_conversions\expenum\extended (euint_uint_E_1.cs) -- failed
//..\conformance\6_conversions\expenum\extended (euint_uint_E_2.cs) -- failed
//..\conformance\6_conversions\expenum\extended (euint_uint_E_3.cs) -- failed
//..\conformance\6_conversions\expenum\extended (euint_ulong_E_1.cs) -- failed
//..\conformance\6_conversions\expenum\extended (euint_short_E_1.cs) -- failed
//..\conformance\6_conversions\expenum\extended (euint_short_E_2.cs) -- failed
//..\conformance\6_conversions\expenum\extended (euint_int_E_1.cs) -- failed
//..\conformance\6_conversions\expenum\extended (euint_int_E_2.cs) -- failed
//..\conformance\6_conversions\expenum\extended (euint_long_E_1.cs) -- failed
//..\conformance\6_conversions\expenum\extended (euint_float_E_1.cs) -- failed
//..\conformance\6_conversions\expenum\extended (euint_double_E_1.cs) -- failed
//..\conformance\6_conversions\expenum\extended (euint_esbyte_E_1.cs) -- failed
//..\conformance\6_conversions\expenum\extended (euint_esbyte_E_2.cs) -- failed
//..\conformance\6_conversions\expenum\extended (euint_ebyte_E_1.cs) -- failed
//..\conformance\6_conversions\expenum\extended (euint_ebyte_E_2.cs) -- failed
//..\conformance\6_conversions\expenum\extended (euint_ebyte_E_3.cs) -- failed
//..\conformance\6_conversions\expenum\extended (euint_eushort_E_1.cs) -- failed
//..\conformance\6_conversions\expenum\extended (euint_eushort_E_2.cs) -- failed
//..\conformance\6_conversions\expenum\extended (euint_eushort_E_3.cs) -- failed
//..\conformance\6_conversions\expenum\extended (euint_eshort_E_1.cs) -- failed
//..\conformance\6_conversions\expenum\extended (euint_eshort_E_2.cs) -- failed
//..\conformance\6_conversions\expenum\extended (euint_eint_E_1.cs) -- failed
//..\conformance\6_conversions\expenum\extended (euint_eint_E_2.cs) -- failed
//..\conformance\6_conversions\expenum\extended (euint_eulong_E_1.cs) -- failed
//..\conformance\6_conversions\expenum\extended (euint_elong_E_1.cs) -- failed
//..\conformance\6_conversions\expenum\extended (eulong_byte_E_1.cs) -- failed
//..\conformance\6_conversions\expenum\extended (eulong_byte_E_2.cs) -- failed
//..\conformance\6_conversions\expenum\extended (eulong_byte_E_3.cs) -- failed
//..\conformance\6_conversions\expenum\extended (eulong_sbyte_E_1.cs) -- failed
//..\conformance\6_conversions\expenum\extended (eulong_sbyte_E_2.cs) -- failed
//..\conformance\6_conversions\expenum\extended (eulong_ushort_E_1.cs) -- failed
//..\conformance\6_conversions\expenum\extended (eulong_ushort_E_2.cs) -- failed
//..\conformance\6_conversions\expenum\extended (eulong_ushort_E_3.cs) -- failed
//..\conformance\6_conversions\expenum\extended (eulong_uint_E_1.cs) -- failed
//..\conformance\6_conversions\expenum\extended (eulong_uint_E_2.cs) -- failed
//..\conformance\6_conversions\expenum\extended (eulong_uint_E_3.cs) -- failed
//..\conformance\6_conversions\expenum\extended (eulong_ulong_E_1.cs) -- failed
//..\conformance\6_conversions\expenum\extended (eulong_ulong_E_2.cs) -- failed
//..\conformance\6_conversions\expenum\extended (eulong_ulong_E_3.cs) -- failed
//..\conformance\6_conversions\expenum\extended (eulong_short_E_1.cs) -- failed
//..\conformance\6_conversions\expenum\extended (eulong_short_E_2.cs) -- failed
//..\conformance\6_conversions\expenum\extended (eulong_int_E_1.cs) -- failed
//..\conformance\6_conversions\expenum\extended (eulong_int_E_2.cs) -- failed
//..\conformance\6_conversions\expenum\extended (eulong_long_E_1.cs) -- failed
//..\conformance\6_conversions\expenum\extended (eulong_long_E_2.cs) -- failed
//..\conformance\6_conversions\expenum\extended (eulong_float_E_1.cs) -- failed
//..\conformance\6_conversions\expenum\extended (eulong_double_E_1.cs) -- failed
//..\conformance\6_conversions\expenum\extended (eulong_esbyte_E_1.cs) -- failed
//..\conformance\6_conversions\expenum\extended (eulong_esbyte_E_2.cs) -- failed
//..\conformance\6_conversions\expenum\extended (eulong_ebyte_E_1.cs) -- failed
//..\conformance\6_conversions\expenum\extended (eulong_ebyte_E_2.cs) -- failed
//..\conformance\6_conversions\expenum\extended (eulong_ebyte_E_3.cs) -- failed
//..\conformance\6_conversions\expenum\extended (eulong_eushort_E_1.cs) -- failed
//..\conformance\6_conversions\expenum\extended (eulong_eushort_E_2.cs) -- failed
//..\conformance\6_conversions\expenum\extended (eulong_eushort_E_3.cs) -- failed
//..\conformance\6_conversions\expenum\extended (eulong_eshort_E_1.cs) -- failed
//..\conformance\6_conversions\expenum\extended (eulong_eshort_E_2.cs) -- failed
//..\conformance\6_conversions\expenum\extended (eulong_eint_E_1.cs) -- failed
//..\conformance\6_conversions\expenum\extended (eulong_eint_E_2.cs) -- failed
//..\conformance\6_conversions\expenum\extended (eulong_euint_E_1.cs) -- failed
//..\conformance\6_conversions\expenum\extended (eulong_euint_E_2.cs) -- failed
//..\conformance\6_conversions\expenum\extended (eulong_euint_E_3.cs) -- failed
//..\conformance\6_conversions\expenum\extended (eulong_elong_E_1.cs) -- failed
//..\conformance\6_conversions\expenum\extended (eulong_elong_E_2.cs) -- failed
//..\conformance\6_conversions\expenum\extended (eushort_byte_E_1.cs) -- failed
//..\conformance\6_conversions\expenum\extended (eushort_byte_E_2.cs) -- failed
//..\conformance\6_conversions\expenum\extended (eushort_byte_E_3.cs) -- failed
//..\conformance\6_conversions\expenum\extended (eushort_sbyte_E_1.cs) -- failed
//..\conformance\6_conversions\expenum\extended (eushort_sbyte_E_2.cs) -- failed
//..\conformance\6_conversions\expenum\extended (eushort_ushort_E_1.cs) -- failed
//..\conformance\6_conversions\expenum\extended (eushort_ushort_E_2.cs) -- failed
//..\conformance\6_conversions\expenum\extended (eushort_ushort_E_3.cs) -- failed
//..\conformance\6_conversions\expenum\extended (eushort_uint_E_1.cs) -- failed
//..\conformance\6_conversions\expenum\extended (eushort_ulong_E_1.cs) -- failed
//..\conformance\6_conversions\expenum\extended (eushort_short_E_1.cs) -- failed
//..\conformance\6_conversions\expenum\extended (eushort_short_E_2.cs) -- failed
//..\conformance\6_conversions\expenum\extended (eushort_int_E_1.cs) -- failed
//..\conformance\6_conversions\expenum\extended (eushort_long_E_1.cs) -- failed
//..\conformance\6_conversions\expenum\extended (eushort_float_E_1.cs) -- failed
//..\conformance\6_conversions\expenum\extended (eushort_double_E_1.cs) -- failed
//..\conformance\6_conversions\expenum\extended (eushort_esbyte_E_1.cs) -- failed
//..\conformance\6_conversions\expenum\extended (eushort_esbyte_E_2.cs) -- failed
//..\conformance\6_conversions\expenum\extended (eushort_ebyte_E_1.cs) -- failed
//..\conformance\6_conversions\expenum\extended (eushort_ebyte_E_2.cs) -- failed
//..\conformance\6_conversions\expenum\extended (eushort_ebyte_E_3.cs) -- failed
//..\conformance\6_conversions\expenum\extended (eushort_eshort_E_1.cs) -- failed
//..\conformance\6_conversions\expenum\extended (eushort_eshort_E_2.cs) -- failed
//..\conformance\6_conversions\expenum\extended (eushort_euint_E_1.cs) -- failed
//..\conformance\6_conversions\expenum\extended (eushort_eulong_E_1.cs) -- failed
//..\conformance\6_conversions\expenum\extended (eushort_eint_E_1.cs) -- failed
//..\conformance\6_conversions\expenum\extended (eushort_elong_E_1.cs) -- failed
//..\conformance\6_conversions\expenum\extended (float_ebyte_E_1.cs) -- failed
//..\conformance\6_conversions\expenum\extended (float_ebyte_E_2.cs) -- failed
//..\conformance\6_conversions\expenum\extended (float_ebyte_E_3.cs) -- failed
//..\conformance\6_conversions\expenum\extended (float_ebyte_E_4.cs) -- passed
//..\conformance\6_conversions\expenum\extended (float_esbyte_E_1.cs) -- failed
//..\conformance\6_conversions\expenum\extended (float_esbyte_E_2.cs) -- failed
//..\conformance\6_conversions\expenum\extended (float_esbyte_E_3.cs) -- failed
//..\conformance\6_conversions\expenum\extended (float_esbyte_E_4.cs) -- passed
//..\conformance\6_conversions\expenum\extended (float_eushort_E_1.cs) -- failed
//..\conformance\6_conversions\expenum\extended (float_eushort_E_2.cs) -- failed
//..\conformance\6_conversions\expenum\extended (float_eushort_E_3.cs) -- failed
//..\conformance\6_conversions\expenum\extended (float_eushort_E_4.cs) -- passed
//..\conformance\6_conversions\expenum\extended (float_euint_E_1.cs) -- failed
//..\conformance\6_conversions\expenum\extended (float_eulong_E_1.cs) -- failed
//..\conformance\6_conversions\expenum\extended (float_eshort_E_1.cs) -- failed
//..\conformance\6_conversions\expenum\extended (float_eshort_E_2.cs) -- failed
//..\conformance\6_conversions\expenum\extended (float_eshort_E_3.cs) -- failed
//..\conformance\6_conversions\expenum\extended (float_eshort_E_4.cs) -- passed
//..\conformance\6_conversions\expenum\extended (float_eint_E_1.cs) -- failed
//..\conformance\6_conversions\expenum\extended (float_elong_E_1.cs) -- failed
//..\conformance\6_conversions\expenum\extended (int_ebyte_E_1.cs) -- failed
//..\conformance\6_conversions\expenum\extended (int_ebyte_E_2.cs) -- failed
//..\conformance\6_conversions\expenum\extended (int_ebyte_E_3.cs) -- failed
//..\conformance\6_conversions\expenum\extended (int_ebyte_E_4.cs) -- failed
//..\conformance\6_conversions\expenum\extended (int_esbyte_E_1.cs) -- failed
//..\conformance\6_conversions\expenum\extended (int_esbyte_E_2.cs) -- failed
//..\conformance\6_conversions\expenum\extended (int_esbyte_E_3.cs) -- failed
//..\conformance\6_conversions\expenum\extended (int_esbyte_E_4.cs) -- failed
//..\conformance\6_conversions\expenum\extended (int_eushort_E_1.cs) -- failed
//..\conformance\6_conversions\expenum\extended (int_eushort_E_2.cs) -- failed
//..\conformance\6_conversions\expenum\extended (int_eushort_E_3.cs) -- failed
//..\conformance\6_conversions\expenum\extended (int_eushort_E_4.cs) -- failed
//..\conformance\6_conversions\expenum\extended (int_euint_E_1.cs) -- failed
//..\conformance\6_conversions\expenum\extended (int_euint_E_2.cs) -- failed
//..\conformance\6_conversions\expenum\extended (int_euint_E_3.cs) -- failed
//..\conformance\6_conversions\expenum\extended (int_eulong_E_1.cs) -- failed
//..\conformance\6_conversions\expenum\extended (int_eshort_E_1.cs) -- failed
//..\conformance\6_conversions\expenum\extended (int_eshort_E_2.cs) -- failed
//..\conformance\6_conversions\expenum\extended (int_eshort_E_3.cs) -- failed
//..\conformance\6_conversions\expenum\extended (int_eshort_E_4.cs) -- failed
//..\conformance\6_conversions\expenum\extended (int_eint_E_1.cs) -- failed
//..\conformance\6_conversions\expenum\extended (int_eint_E_2.cs) -- failed
//..\conformance\6_conversions\expenum\extended (int_eint_E_3.cs) -- failed
//..\conformance\6_conversions\expenum\extended (int_elong_E_1.cs) -- failed
//..\conformance\6_conversions\expenum\extended (long_ebyte_E_1.cs) -- failed
//..\conformance\6_conversions\expenum\extended (long_ebyte_E_2.cs) -- failed
//..\conformance\6_conversions\expenum\extended (long_ebyte_E_3.cs) -- failed
//..\conformance\6_conversions\expenum\extended (long_ebyte_E_4.cs) -- failed
//..\conformance\6_conversions\expenum\extended (long_esbyte_E_1.cs) -- failed
//..\conformance\6_conversions\expenum\extended (long_esbyte_E_2.cs) -- failed
//..\conformance\6_conversions\expenum\extended (long_esbyte_E_3.cs) -- failed
//..\conformance\6_conversions\expenum\extended (long_esbyte_E_4.cs) -- failed
//..\conformance\6_conversions\expenum\extended (long_eushort_E_1.cs) -- failed
//..\conformance\6_conversions\expenum\extended (long_eushort_E_2.cs) -- failed
//..\conformance\6_conversions\expenum\extended (long_eushort_E_3.cs) -- failed
//..\conformance\6_conversions\expenum\extended (long_eushort_E_4.cs) -- failed
//..\conformance\6_conversions\expenum\extended (long_euint_E_1.cs) -- failed
//..\conformance\6_conversions\expenum\extended (long_euint_E_2.cs) -- failed
//..\conformance\6_conversions\expenum\extended (long_euint_E_3.cs) -- failed
//..\conformance\6_conversions\expenum\extended (long_euint_E_4.cs) -- failed
//..\conformance\6_conversions\expenum\extended (long_eulong_E_1.cs) -- failed
//..\conformance\6_conversions\expenum\extended (long_eulong_E_2.cs) -- failed
//..\conformance\6_conversions\expenum\extended (long_eshort_E_1.cs) -- failed
//..\conformance\6_conversions\expenum\extended (long_eshort_E_2.cs) -- failed
//..\conformance\6_conversions\expenum\extended (long_eshort_E_3.cs) -- failed
//..\conformance\6_conversions\expenum\extended (long_eshort_E_4.cs) -- failed
//..\conformance\6_conversions\expenum\extended (long_eint_E_1.cs) -- failed
//..\conformance\6_conversions\expenum\extended (long_eint_E_2.cs) -- failed
//..\conformance\6_conversions\expenum\extended (long_eint_E_3.cs) -- failed
//..\conformance\6_conversions\expenum\extended (long_eint_E_4.cs) -- failed
//..\conformance\6_conversions\expenum\extended (long_elong_E_1.cs) -- failed
//..\conformance\6_conversions\expenum\extended (long_elong_E_2.cs) -- failed
//..\conformance\6_conversions\expenum\extended (long_elong_E_3.cs) -- failed
//..\conformance\6_conversions\expenum\extended (short_ebyte_E_1.cs) -- failed
//..\conformance\6_conversions\expenum\extended (short_ebyte_E_2.cs) -- failed
//..\conformance\6_conversions\expenum\extended (short_ebyte_E_3.cs) -- failed
//..\conformance\6_conversions\expenum\extended (short_ebyte_E_4.cs) -- failed
//..\conformance\6_conversions\expenum\extended (short_esbyte_E_1.cs) -- failed
//..\conformance\6_conversions\expenum\extended (short_esbyte_E_2.cs) -- failed
//..\conformance\6_conversions\expenum\extended (short_esbyte_E_3.cs) -- failed
//..\conformance\6_conversions\expenum\extended (short_esbyte_E_4.cs) -- failed
//..\conformance\6_conversions\expenum\extended (short_eushort_E_1.cs) -- failed
//..\conformance\6_conversions\expenum\extended (short_eushort_E_2.cs) -- failed
//..\conformance\6_conversions\expenum\extended (short_eushort_E_3.cs) -- failed
//..\conformance\6_conversions\expenum\extended (short_euint_E_1.cs) -- failed
//..\conformance\6_conversions\expenum\extended (short_eulong_E_1.cs) -- failed
//..\conformance\6_conversions\expenum\extended (short_eshort_E_1.cs) -- failed
//..\conformance\6_conversions\expenum\extended (short_eshort_E_2.cs) -- failed
//..\conformance\6_conversions\expenum\extended (short_eshort_E_3.cs) -- failed
//..\conformance\6_conversions\expenum\extended (short_eint_E_1.cs) -- failed
//..\conformance\6_conversions\expenum\extended (short_elong_E_1.cs) -- failed
//..\conformance\6_conversions\expenum\extended (uint_ebyte_E_1.cs) -- failed
//..\conformance\6_conversions\expenum\extended (uint_ebyte_E_2.cs) -- failed
//..\conformance\6_conversions\expenum\extended (uint_ebyte_E_3.cs) -- failed
//..\conformance\6_conversions\expenum\extended (uint_esbyte_E_1.cs) -- failed
//..\conformance\6_conversions\expenum\extended (uint_esbyte_E_2.cs) -- failed
//..\conformance\6_conversions\expenum\extended (uint_eushort_E_1.cs) -- failed
//..\conformance\6_conversions\expenum\extended (uint_eushort_E_2.cs) -- failed
//..\conformance\6_conversions\expenum\extended (uint_eushort_E_3.cs) -- failed
//..\conformance\6_conversions\expenum\extended (uint_euint_E_1.cs) -- failed
//..\conformance\6_conversions\expenum\extended (uint_euint_E_2.cs) -- failed
//..\conformance\6_conversions\expenum\extended (uint_euint_E_3.cs) -- failed
//..\conformance\6_conversions\expenum\extended (uint_eulong_E_1.cs) -- failed
//..\conformance\6_conversions\expenum\extended (uint_eshort_E_1.cs) -- failed
//..\conformance\6_conversions\expenum\extended (uint_eshort_E_2.cs) -- failed
//..\conformance\6_conversions\expenum\extended (uint_eint_E_1.cs) -- failed
//..\conformance\6_conversions\expenum\extended (uint_eint_E_2.cs) -- failed
//..\conformance\6_conversions\expenum\extended (uint_elong_E_1.cs) -- failed
//..\conformance\6_conversions\expenum\extended (ulong_ebyte_E_1.cs) -- failed
//..\conformance\6_conversions\expenum\extended (ulong_ebyte_E_2.cs) -- failed
//..\conformance\6_conversions\expenum\extended (ulong_ebyte_E_3.cs) -- failed
//..\conformance\6_conversions\expenum\extended (ulong_esbyte_E_1.cs) -- failed
//..\conformance\6_conversions\expenum\extended (ulong_esbyte_E_2.cs) -- failed
//..\conformance\6_conversions\expenum\extended (ulong_eushort_E_1.cs) -- failed
//..\conformance\6_conversions\expenum\extended (ulong_eushort_E_2.cs) -- failed
//..\conformance\6_conversions\expenum\extended (ulong_eushort_E_3.cs) -- failed
//..\conformance\6_conversions\expenum\extended (ulong_euint_E_1.cs) -- failed
//..\conformance\6_conversions\expenum\extended (ulong_euint_E_2.cs) -- failed
//..\conformance\6_conversions\expenum\extended (ulong_euint_E_3.cs) -- failed
//..\conformance\6_conversions\expenum\extended (ulong_eulong_E_1.cs) -- failed
//..\conformance\6_conversions\expenum\extended (ulong_eulong_E_2.cs) -- failed
//..\conformance\6_conversions\expenum\extended (ulong_eulong_E_3.cs) -- failed
//..\conformance\6_conversions\expenum\extended (ulong_eshort_E_1.cs) -- failed
//..\conformance\6_conversions\expenum\extended (ulong_eshort_E_2.cs) -- failed
//..\conformance\6_conversions\expenum\extended (ulong_eint_E_1.cs) -- failed
//..\conformance\6_conversions\expenum\extended (ulong_eint_E_2.cs) -- failed
//..\conformance\6_conversions\expenum\extended (ulong_elong_E_1.cs) -- failed
//..\conformance\6_conversions\expenum\extended (ulong_elong_E_2.cs) -- failed
//..\conformance\6_conversions\expenum\extended (ushort_ebyte_E_1.cs) -- failed
//..\conformance\6_conversions\expenum\extended (ushort_ebyte_E_2.cs) -- failed
//..\conformance\6_conversions\expenum\extended (ushort_ebyte_E_3.cs) -- failed
//..\conformance\6_conversions\expenum\extended (ushort_esbyte_E_1.cs) -- failed
//..\conformance\6_conversions\expenum\extended (ushort_esbyte_E_2.cs) -- failed
//..\conformance\6_conversions\expenum\extended (ushort_eushort_E_1.cs) -- failed
//..\conformance\6_conversions\expenum\extended (ushort_eushort_E_2.cs) -- failed
//..\conformance\6_conversions\expenum\extended (ushort_eushort_E_3.cs) -- failed
//..\conformance\6_conversions\expenum\extended (ushort_euint_E_1.cs) -- failed
//..\conformance\6_conversions\expenum\extended (ushort_eulong_E_1.cs) -- failed
//..\conformance\6_conversions\expenum\extended (ushort_eshort_E_1.cs) -- failed
//..\conformance\6_conversions\expenum\extended (ushort_eshort_E_2.cs) -- failed
//..\conformance\6_conversions\expenum\extended (ushort_eint_E_1.cs) -- failed
//..\conformance\6_conversions\expenum\extended (ushort_elong_E_1.cs) -- failed
//..\conformance\6_conversions\user\classclass (SBase_TBase_Source_i_e.cs) -- passed
//..\conformance\6_conversions\user\classclass (SBase_TBase_Source_e_e.cs) -- passed
//..\conformance\6_conversions\user\classclass (SBase_TBase_Dest_i_e.cs) -- passed
//..\conformance\6_conversions\user\classclass (SBase_TBase_Dest_e_e.cs) -- passed
//..\conformance\6_conversions\user\classclass (SBase_T_Source_i_i.cs) -- passed
//..\conformance\6_conversions\user\classclass (SBase_T_Source_i_e.cs) -- passed
//..\conformance\6_conversions\user\classclass (SBase_T_Source_e_e.cs) -- passed
//..\conformance\6_conversions\user\classclass (SBase_T_Dest_i_i.cs) -- passed
//..\conformance\6_conversions\user\classclass (SBase_T_Dest_i_e.cs) -- passed
//..\conformance\6_conversions\user\classclass (SBase_T_Dest_e_e.cs) -- passed
//..\conformance\6_conversions\user\classclass (SBase_TDer_Source_i_i.cs) -- passed
//..\conformance\6_conversions\user\classclass (SBase_TDer_Source_i_e.cs) -- passed
//..\conformance\6_conversions\user\classclass (SBase_TDer_Source_e_e.cs) -- passed
//..\conformance\6_conversions\user\classclass (S_TBase_Source_i_e.cs) -- passed
//..\conformance\6_conversions\user\classclass (S_TBase_Source_e_e.cs) -- passed
//..\conformance\6_conversions\user\classclass (S_TBase_Dest_i_e.cs) -- passed
//..\conformance\6_conversions\user\classclass (S_TBase_Dest_e_e.cs) -- passed
//..\conformance\6_conversions\user\classclass (S_T_Source_i_i.cs) -- passed
//..\conformance\6_conversions\user\classclass (S_T_Source_i_e.cs) -- passed
//..\conformance\6_conversions\user\classclass (S_T_Source_e_e.cs) -- passed
//..\conformance\6_conversions\user\classclass (S_T_Dest_i_i.cs) -- passed
//..\conformance\6_conversions\user\classclass (S_T_Dest_i_e.cs) -- passed
//..\conformance\6_conversions\user\classclass (S_T_Dest_e_e.cs) -- passed
//..\conformance\6_conversions\user\classclass (S_TDer_Source_i_i.cs) -- passed
//..\conformance\6_conversions\user\classclass (S_TDer_Source_i_e.cs) -- passed
//..\conformance\6_conversions\user\classclass (S_TDer_Source_e_e.cs) -- passed
//..\conformance\6_conversions\user\classclass (SDer_TBase_Dest_i_e.cs) -- passed
//..\conformance\6_conversions\user\classclass (SDer_TBase_Dest_e_e.cs) -- passed
//..\conformance\6_conversions\user\classclass (SDer_T_Dest_i_e.cs) -- passed
//..\conformance\6_conversions\user\classclass (SDer_T_Dest_e_e.cs) -- passed
//..\conformance\6_conversions\user\classstruct (SBase_T_Source_i_i.cs) -- passed
//..\conformance\6_conversions\user\classstruct (SBase_T_Source_i_e.cs) -- passed
//..\conformance\6_conversions\user\classstruct (SBase_T_Source_e_e.cs) -- passed
//..\conformance\6_conversions\user\classstruct (SBase_T_Dest_i_i.cs) -- passed
//..\conformance\6_conversions\user\classstruct (SBase_T_Dest_i_e.cs) -- passed
//..\conformance\6_conversions\user\classstruct (SBase_T_Dest_e_e.cs) -- passed
//..\conformance\6_conversions\user\classstruct (S_T_Source_i_i.cs) -- passed
//..\conformance\6_conversions\user\classstruct (S_T_Source_i_e.cs) -- passed
//..\conformance\6_conversions\user\classstruct (S_T_Source_e_e.cs) -- passed
//..\conformance\6_conversions\user\classstruct (S_T_Dest_i_i.cs) -- passed
//..\conformance\6_conversions\user\classstruct (S_T_Dest_i_e.cs) -- passed
//..\conformance\6_conversions\user\classstruct (S_T_Dest_e_e.cs) -- passed
//..\conformance\6_conversions\user\classstruct (SDer_T_Dest_i_e.cs) -- passed
//..\conformance\6_conversions\user\classstruct (SDer_T_Dest_e_e.cs) -- passed
//..\conformance\6_conversions\user\classstruct (null_to_struct_e.cs) -- passed
//..\conformance\6_conversions\user\classstruct (null_to_struct_i.cs) -- passed
//..\conformance\6_conversions\user\structclass (S_TBase_Source_i_e.cs) -- passed
//..\conformance\6_conversions\user\structclass (S_TBase_Source_e_e.cs) -- passed
//..\conformance\6_conversions\user\structclass (S_TBase_Dest_i_e.cs) -- passed
//..\conformance\6_conversions\user\structclass (S_TBase_Dest_e_e.cs) -- passed
//..\conformance\6_conversions\user\structclass (S_T_Source_i_i.cs) -- passed
//..\conformance\6_conversions\user\structclass (S_T_Source_i_e.cs) -- passed
//..\conformance\6_conversions\user\structclass (S_T_Source_e_e.cs) -- passed
//..\conformance\6_conversions\user\structclass (S_T_Dest_i_i.cs) -- passed
//..\conformance\6_conversions\user\structclass (S_T_Dest_i_e.cs) -- passed
//..\conformance\6_conversions\user\structclass (S_T_Dest_e_e.cs) -- passed
//..\conformance\6_conversions\user\structclass (S_TDer_Source_i_i.cs) -- passed
//..\conformance\6_conversions\user\structclass (S_TDer_Source_i_e.cs) -- passed
//..\conformance\6_conversions\user\structclass (S_TDer_Source_e_e.cs) -- passed
//..\conformance\6_conversions\user\structstruct (S_T_Source_i_i.cs) -- passed
//..\conformance\6_conversions\user\structstruct (S_T_Source_i_e.cs) -- passed
//..\conformance\6_conversions\user\structstruct (S_T_Source_e_e.cs) -- passed
//..\conformance\6_conversions\user\structstruct (S_T_Dest_i_i.cs) -- passed
//..\conformance\6_conversions\user\structstruct (S_T_Dest_i_e.cs) -- passed
//..\conformance\6_conversions\user\structstruct (S_T_Dest_e_e.cs) -- passed
//..\conformance\6_conversions\user\basic\coverage (byte_i_i_tc.cs) -- passed
//..\conformance\6_conversions\user\basic\coverage (byte_i_e_tc.cs) -- passed
//..\conformance\6_conversions\user\basic\coverage (byte_e_e_tc.cs) -- passed
//..\conformance\6_conversions\user\basic\coverage (byte_i_i_fc.cs) -- passed
//..\conformance\6_conversions\user\basic\coverage (byte_i_e_fc.cs) -- passed
//..\conformance\6_conversions\user\basic\coverage (byte_e_e_fc.cs) -- passed
//..\conformance\6_conversions\user\basic\coverage (char_i_i_tc.cs) -- passed
//..\conformance\6_conversions\user\basic\coverage (char_i_e_tc.cs) -- passed
//..\conformance\6_conversions\user\basic\coverage (char_e_e_tc.cs) -- passed
//..\conformance\6_conversions\user\basic\coverage (char_i_i_fc.cs) -- passed
//..\conformance\6_conversions\user\basic\coverage (char_i_e_fc.cs) -- passed
//..\conformance\6_conversions\user\basic\coverage (char_e_e_fc.cs) -- passed
//..\conformance\6_conversions\user\basic\coverage (double_i_i_tc.cs) -- passed
//..\conformance\6_conversions\user\basic\coverage (double_i_e_tc.cs) -- passed
//..\conformance\6_conversions\user\basic\coverage (double_e_e_tc.cs) -- passed
//..\conformance\6_conversions\user\basic\coverage (double_i_i_fc.cs) -- passed
//..\conformance\6_conversions\user\basic\coverage (double_i_e_fc.cs) -- passed
//..\conformance\6_conversions\user\basic\coverage (double_e_e_fc.cs) -- passed
//..\conformance\6_conversions\user\basic\coverage (float_i_i_tc.cs) -- passed
//..\conformance\6_conversions\user\basic\coverage (float_i_e_tc.cs) -- passed
//..\conformance\6_conversions\user\basic\coverage (float_e_e_tc.cs) -- passed
//..\conformance\6_conversions\user\basic\coverage (float_i_i_fc.cs) -- passed
//..\conformance\6_conversions\user\basic\coverage (float_i_e_fc.cs) -- passed
//..\conformance\6_conversions\user\basic\coverage (float_e_e_fc.cs) -- passed
//..\conformance\6_conversions\user\basic\coverage (int_i_i_tc.cs) -- passed
//..\conformance\6_conversions\user\basic\coverage (int_i_e_tc.cs) -- passed
//..\conformance\6_conversions\user\basic\coverage (int_e_e_tc.cs) -- passed
//..\conformance\6_conversions\user\basic\coverage (int_i_i_fc.cs) -- passed
//..\conformance\6_conversions\user\basic\coverage (int_i_e_fc.cs) -- passed
//..\conformance\6_conversions\user\basic\coverage (int_e_e_fc.cs) -- passed
//..\conformance\6_conversions\user\basic\coverage (long_i_i_tc.cs) -- passed
//..\conformance\6_conversions\user\basic\coverage (long_i_e_tc.cs) -- passed
//..\conformance\6_conversions\user\basic\coverage (long_e_e_tc.cs) -- passed
//..\conformance\6_conversions\user\basic\coverage (long_i_i_fc.cs) -- passed
//..\conformance\6_conversions\user\basic\coverage (long_i_e_fc.cs) -- passed
//..\conformance\6_conversions\user\basic\coverage (long_e_e_fc.cs) -- passed
//..\conformance\6_conversions\user\basic\coverage (sbyte_i_i_tc.cs) -- passed
//..\conformance\6_conversions\user\basic\coverage (sbyte_i_e_tc.cs) -- passed
//..\conformance\6_conversions\user\basic\coverage (sbyte_e_e_tc.cs) -- passed
//..\conformance\6_conversions\user\basic\coverage (sbyte_i_i_fc.cs) -- passed
//..\conformance\6_conversions\user\basic\coverage (sbyte_i_e_fc.cs) -- passed
//..\conformance\6_conversions\user\basic\coverage (sbyte_e_e_fc.cs) -- passed
//..\conformance\6_conversions\user\basic\coverage (short_i_i_tc.cs) -- passed
//..\conformance\6_conversions\user\basic\coverage (short_i_e_tc.cs) -- passed
//..\conformance\6_conversions\user\basic\coverage (short_e_e_tc.cs) -- passed
//..\conformance\6_conversions\user\basic\coverage (short_i_i_fc.cs) -- passed
//..\conformance\6_conversions\user\basic\coverage (short_i_e_fc.cs) -- passed
//..\conformance\6_conversions\user\basic\coverage (short_e_e_fc.cs) -- passed
//..\conformance\6_conversions\user\basic\coverage (uint_i_i_tc.cs) -- passed
//..\conformance\6_conversions\user\basic\coverage (uint_i_e_tc.cs) -- passed
//..\conformance\6_conversions\user\basic\coverage (uint_e_e_tc.cs) -- passed
//..\conformance\6_conversions\user\basic\coverage (uint_i_i_fc.cs) -- passed
//..\conformance\6_conversions\user\basic\coverage (uint_i_e_fc.cs) -- passed
//..\conformance\6_conversions\user\basic\coverage (uint_e_e_fc.cs) -- passed
//..\conformance\6_conversions\user\basic\coverage (ulong_i_i_tc.cs) -- passed
//..\conformance\6_conversions\user\basic\coverage (ulong_i_e_tc.cs) -- passed
//..\conformance\6_conversions\user\basic\coverage (ulong_e_e_tc.cs) -- passed
//..\conformance\6_conversions\user\basic\coverage (ulong_i_i_fc.cs) -- passed
//..\conformance\6_conversions\user\basic\coverage (ulong_i_e_fc.cs) -- passed
//..\conformance\6_conversions\user\basic\coverage (ulong_e_e_fc.cs) -- passed
//..\conformance\6_conversions\user\basic\coverage (ushort_i_i_tc.cs) -- passed
//..\conformance\6_conversions\user\basic\coverage (ushort_i_e_tc.cs) -- passed
//..\conformance\6_conversions\user\basic\coverage (ushort_e_e_tc.cs) -- passed
//..\conformance\6_conversions\user\basic\coverage (ushort_i_i_fc.cs) -- passed
//..\conformance\6_conversions\user\basic\coverage (ushort_i_e_fc.cs) -- passed
//..\conformance\6_conversions\user\basic\coverage (ushort_e_e_fc.cs) -- passed
//..\conformance\6_conversions\user\basic\selection (byte_i_i_tc.cs) -- passed
//..\conformance\6_conversions\user\basic\selection (byte_i_e_tc.cs) -- passed
//..\conformance\6_conversions\user\basic\selection (byte_e_e_tc.cs) -- passed
//..\conformance\6_conversions\user\basic\selection (byte_i_i_fc.cs) -- passed
//..\conformance\6_conversions\user\basic\selection (byte_i_e_fc.cs) -- passed
//..\conformance\6_conversions\user\basic\selection (byte_e_e_fc.cs) -- passed
//..\conformance\6_conversions\user\basic\selection (char_i_i_tc.cs) -- passed
//..\conformance\6_conversions\user\basic\selection (char_i_e_tc.cs) -- passed
//..\conformance\6_conversions\user\basic\selection (char_e_e_tc.cs) -- passed
//..\conformance\6_conversions\user\basic\selection (char_i_i_fc.cs) -- passed
//..\conformance\6_conversions\user\basic\selection (char_i_e_fc.cs) -- passed
//..\conformance\6_conversions\user\basic\selection (char_e_e_fc.cs) -- passed
//..\conformance\6_conversions\user\basic\selection (double_i_i_tc.cs) -- passed
//..\conformance\6_conversions\user\basic\selection (double_i_e_tc.cs) -- passed
//..\conformance\6_conversions\user\basic\selection (double_e_e_tc.cs) -- passed
//..\conformance\6_conversions\user\basic\selection (double_i_i_fc.cs) -- passed
//..\conformance\6_conversions\user\basic\selection (double_i_e_fc.cs) -- passed
//..\conformance\6_conversions\user\basic\selection (double_e_e_fc.cs) -- passed
//..\conformance\6_conversions\user\basic\selection (float_i_i_tc.cs) -- passed
//..\conformance\6_conversions\user\basic\selection (float_i_e_tc.cs) -- passed
//..\conformance\6_conversions\user\basic\selection (float_e_e_tc.cs) -- passed
//..\conformance\6_conversions\user\basic\selection (float_i_i_fc.cs) -- passed
//..\conformance\6_conversions\user\basic\selection (float_i_e_fc.cs) -- passed
//..\conformance\6_conversions\user\basic\selection (float_e_e_fc.cs) -- passed
//..\conformance\6_conversions\user\basic\selection (int_i_i_tc.cs) -- passed
//..\conformance\6_conversions\user\basic\selection (int_i_e_tc.cs) -- passed
//..\conformance\6_conversions\user\basic\selection (int_e_e_tc.cs) -- passed
//..\conformance\6_conversions\user\basic\selection (int_i_i_fc.cs) -- passed
//..\conformance\6_conversions\user\basic\selection (int_i_e_fc.cs) -- passed
//..\conformance\6_conversions\user\basic\selection (int_e_e_fc.cs) -- passed
//..\conformance\6_conversions\user\basic\selection (long_i_i_tc.cs) -- passed
//..\conformance\6_conversions\user\basic\selection (long_i_e_tc.cs) -- passed
//..\conformance\6_conversions\user\basic\selection (long_e_e_tc.cs) -- passed
//..\conformance\6_conversions\user\basic\selection (long_i_i_fc.cs) -- passed
//..\conformance\6_conversions\user\basic\selection (long_i_e_fc.cs) -- passed
//..\conformance\6_conversions\user\basic\selection (long_e_e_fc.cs) -- passed
//..\conformance\6_conversions\user\basic\selection (sbyte_i_i_tc.cs) -- passed
//..\conformance\6_conversions\user\basic\selection (sbyte_i_e_tc.cs) -- passed
//..\conformance\6_conversions\user\basic\selection (sbyte_e_e_tc.cs) -- passed
//..\conformance\6_conversions\user\basic\selection (sbyte_i_i_fc.cs) -- passed
//..\conformance\6_conversions\user\basic\selection (sbyte_i_e_fc.cs) -- passed
//..\conformance\6_conversions\user\basic\selection (sbyte_e_e_fc.cs) -- passed
//..\conformance\6_conversions\user\basic\selection (short_i_i_tc.cs) -- passed
//..\conformance\6_conversions\user\basic\selection (short_i_e_tc.cs) -- passed
//..\conformance\6_conversions\user\basic\selection (short_e_e_tc.cs) -- passed
//..\conformance\6_conversions\user\basic\selection (short_i_i_fc.cs) -- passed
//..\conformance\6_conversions\user\basic\selection (short_i_e_fc.cs) -- passed
//..\conformance\6_conversions\user\basic\selection (short_e_e_fc.cs) -- passed
//..\conformance\6_conversions\user\basic\selection (uint_i_i_tc.cs) -- passed
//..\conformance\6_conversions\user\basic\selection (uint_i_e_tc.cs) -- passed
//..\conformance\6_conversions\user\basic\selection (uint_e_e_tc.cs) -- passed
//..\conformance\6_conversions\user\basic\selection (uint_i_i_fc.cs) -- passed
//..\conformance\6_conversions\user\basic\selection (uint_i_e_fc.cs) -- passed
//..\conformance\6_conversions\user\basic\selection (uint_e_e_fc.cs) -- passed
//..\conformance\6_conversions\user\basic\selection (ulong_i_i_tc.cs) -- passed
//..\conformance\6_conversions\user\basic\selection (ulong_i_e_tc.cs) -- passed
//..\conformance\6_conversions\user\basic\selection (ulong_e_e_tc.cs) -- passed
//..\conformance\6_conversions\user\basic\selection (ulong_i_i_fc.cs) -- passed
//..\conformance\6_conversions\user\basic\selection (ulong_i_e_fc.cs) -- passed
//..\conformance\6_conversions\user\basic\selection (ulong_e_e_fc.cs) -- passed
//..\conformance\6_conversions\user\basic\selection (ushort_i_i_tc.cs) -- passed
//..\conformance\6_conversions\user\basic\selection (ushort_i_e_tc.cs) -- passed
//..\conformance\6_conversions\user\basic\selection (ushort_e_e_tc.cs) -- passed
//..\conformance\6_conversions\user\basic\selection (ushort_i_i_fc.cs) -- passed
//..\conformance\6_conversions\user\basic\selection (ushort_i_e_fc.cs) -- passed
//..\conformance\6_conversions\user\basic\selection (ushort_e_e_fc.cs) -- passed
//..\conformance\6_conversions\user\basic\other (choose1.cs) -- passed
//..\conformance\6_conversions\user\basic\other (choose2.cs) -- passed
//..\conformance\6_conversions\basic (byte_byte_I_0.cs) -- passed
//..\conformance\6_conversions\basic (byte_byte_E_0.cs) -- passed
//..\conformance\6_conversions\basic (byte_short_I_0.cs) -- passed
//..\conformance\6_conversions\basic (byte_short_E_0.cs) -- passed
//..\conformance\6_conversions\basic (byte_ushort_I_0.cs) -- passed
//..\conformance\6_conversions\basic (byte_ushort_E_0.cs) -- passed
//..\conformance\6_conversions\basic (byte_int_I_0.cs) -- passed
//..\conformance\6_conversions\basic (byte_int_E_0.cs) -- passed
//..\conformance\6_conversions\basic (byte_uint_I_0.cs) -- passed
//..\conformance\6_conversions\basic (byte_uint_E_0.cs) -- passed
//..\conformance\6_conversions\basic (byte_long_I_0.cs) -- passed
//..\conformance\6_conversions\basic (byte_long_E_0.cs) -- passed
//..\conformance\6_conversions\basic (byte_ulong_I_0.cs) -- passed
//..\conformance\6_conversions\basic (byte_ulong_E_0.cs) -- passed
//..\conformance\6_conversions\basic (byte_float_I_0.cs) -- passed
//..\conformance\6_conversions\basic (byte_float_E_0.cs) -- passed
//..\conformance\6_conversions\basic (byte_double_I_0.cs) -- passed
//..\conformance\6_conversions\basic (byte_double_E_0.cs) -- passed
//..\conformance\6_conversions\basic (byte_sbyte_E_1.cs) -- passed
//..\conformance\6_conversions\basic (byte_sbyte_E_2.cs) -- passed
//..\conformance\6_conversions\basic (byte_char_E_1.cs) -- passed
//..\conformance\6_conversions\basic (char_char_I_0.cs) -- passed
//..\conformance\6_conversions\basic (char_char_E_0.cs) -- passed
//..\conformance\6_conversions\basic (char_ushort_I_0.cs) -- passed
//..\conformance\6_conversions\basic (char_ushort_E_0.cs) -- passed
//..\conformance\6_conversions\basic (char_int_I_0.cs) -- passed
//..\conformance\6_conversions\basic (char_int_E_0.cs) -- passed
//..\conformance\6_conversions\basic (char_uint_I_0.cs) -- passed
//..\conformance\6_conversions\basic (char_uint_E_0.cs) -- passed
//..\conformance\6_conversions\basic (char_long_I_0.cs) -- passed
//..\conformance\6_conversions\basic (char_long_E_0.cs) -- passed
//..\conformance\6_conversions\basic (char_ulong_I_0.cs) -- passed
//..\conformance\6_conversions\basic (char_ulong_E_0.cs) -- passed
//..\conformance\6_conversions\basic (char_float_I_0.cs) -- passed
//..\conformance\6_conversions\basic (char_float_E_0.cs) -- passed
//..\conformance\6_conversions\basic (char_double_I_0.cs) -- passed
//..\conformance\6_conversions\basic (char_double_E_0.cs) -- passed
//..\conformance\6_conversions\basic (char_sbyte_E_1.cs) -- passed
//..\conformance\6_conversions\basic (char_sbyte_E_2.cs) -- passed
//..\conformance\6_conversions\basic (char_byte_E_1.cs) -- passed
//..\conformance\6_conversions\basic (char_byte_E_2.cs) -- passed
//..\conformance\6_conversions\basic (char_byte_E_3.cs) -- passed
//..\conformance\6_conversions\basic (char_short_E_1.cs) -- passed
//..\conformance\6_conversions\basic (char_short_E_2.cs) -- passed
//..\conformance\6_conversions\basic (double_double_I_0.cs) -- passed
//..\conformance\6_conversions\basic (double_double_E_0.cs) -- passed
//..\conformance\6_conversions\basic (double_byte_E_1.cs) -- passed
//..\conformance\6_conversions\basic (double_byte_E_2.cs) -- passed
//..\conformance\6_conversions\basic (double_byte_E_3.cs) -- passed
//..\conformance\6_conversions\basic (double_sbyte_E_1.cs) -- passed
//..\conformance\6_conversions\basic (double_sbyte_E_2.cs) -- passed
//..\conformance\6_conversions\basic (double_sbyte_E_3.cs) -- passed
//..\conformance\6_conversions\basic (double_char_E_1.cs) -- passed
//..\conformance\6_conversions\basic (double_char_E_2.cs) -- passed
//..\conformance\6_conversions\basic (double_char_E_3.cs) -- passed
//..\conformance\6_conversions\basic (double_short_E_1.cs) -- passed
//..\conformance\6_conversions\basic (double_short_E_2.cs) -- passed
//..\conformance\6_conversions\basic (double_short_E_3.cs) -- passed
//..\conformance\6_conversions\basic (double_ushort_E_1.cs) -- passed
//..\conformance\6_conversions\basic (double_ushort_E_2.cs) -- passed
//..\conformance\6_conversions\basic (double_ushort_E_3.cs) -- passed
//..\conformance\6_conversions\basic (double_int_E_1.cs) -- passed
//..\conformance\6_conversions\basic (double_int_E_2.cs) -- passed
//..\conformance\6_conversions\basic (double_int_E_3.cs) -- passed
//..\conformance\6_conversions\basic (double_uint_E_1.cs) -- passed
//..\conformance\6_conversions\basic (double_uint_E_2.cs) -- passed
//..\conformance\6_conversions\basic (double_uint_E_3.cs) -- passed
//..\conformance\6_conversions\basic (double_long_E_1.cs) -- passed
//..\conformance\6_conversions\basic (double_ulong_E_1.cs) -- passed
//..\conformance\6_conversions\basic (double_float_E_1.cs) -- passed
//..\conformance\6_conversions\basic (double_float_E_2.cs) -- passed
//..\conformance\6_conversions\basic (double_float_E_3.cs) -- passed
//..\conformance\6_conversions\basic (float_float_I_0.cs) -- passed
//..\conformance\6_conversions\basic (float_float_E_0.cs) -- passed
//..\conformance\6_conversions\basic (float_double_I_0.cs) -- passed
//..\conformance\6_conversions\basic (float_double_E_0.cs) -- passed
//..\conformance\6_conversions\basic (float_byte_E_1.cs) -- passed
//..\conformance\6_conversions\basic (float_byte_E_2.cs) -- passed
//..\conformance\6_conversions\basic (float_byte_E_3.cs) -- passed
//..\conformance\6_conversions\basic (float_sbyte_E_1.cs) -- passed
//..\conformance\6_conversions\basic (float_sbyte_E_2.cs) -- passed
//..\conformance\6_conversions\basic (float_sbyte_E_3.cs) -- passed
//..\conformance\6_conversions\basic (float_char_E_1.cs) -- passed
//..\conformance\6_conversions\basic (float_char_E_2.cs) -- passed
//..\conformance\6_conversions\basic (float_char_E_3.cs) -- passed
//..\conformance\6_conversions\basic (float_short_E_1.cs) -- passed
//..\conformance\6_conversions\basic (float_short_E_2.cs) -- passed
//..\conformance\6_conversions\basic (float_short_E_3.cs) -- passed
//..\conformance\6_conversions\basic (float_ushort_E_1.cs) -- passed
//..\conformance\6_conversions\basic (float_ushort_E_2.cs) -- passed
//..\conformance\6_conversions\basic (float_ushort_E_3.cs) -- passed
//..\conformance\6_conversions\basic (float_int_E_1.cs) -- passed
//..\conformance\6_conversions\basic (float_uint_E_1.cs) -- passed
//..\conformance\6_conversions\basic (float_long_E_1.cs) -- passed
//..\conformance\6_conversions\basic (float_ulong_E_1.cs) -- passed
//..\conformance\6_conversions\basic (int_int_I_0.cs) -- passed
//..\conformance\6_conversions\basic (int_int_E_0.cs) -- passed
//..\conformance\6_conversions\basic (int_long_I_0.cs) -- passed
//..\conformance\6_conversions\basic (int_long_E_0.cs) -- passed
//..\conformance\6_conversions\basic (int_float_I_0.cs) -- passed
//..\conformance\6_conversions\basic (int_float_E_0.cs) -- passed
//..\conformance\6_conversions\basic (int_double_I_0.cs) -- passed
//..\conformance\6_conversions\basic (int_double_E_0.cs) -- passed
//..\conformance\6_conversions\basic (int_sbyte_E_1.cs) -- passed
//..\conformance\6_conversions\basic (int_sbyte_E_2.cs) -- passed
//..\conformance\6_conversions\basic (int_sbyte_E_3.cs) -- passed
//..\conformance\6_conversions\basic (int_sbyte_E_4.cs) -- passed
//..\conformance\6_conversions\basic (int_byte_E_1.cs) -- passed
//..\conformance\6_conversions\basic (int_byte_E_2.cs) -- passed
//..\conformance\6_conversions\basic (int_byte_E_3.cs) -- passed
//..\conformance\6_conversions\basic (int_byte_E_4.cs) -- passed
//..\conformance\6_conversions\basic (int_short_E_1.cs) -- passed
//..\conformance\6_conversions\basic (int_short_E_2.cs) -- passed
//..\conformance\6_conversions\basic (int_short_E_3.cs) -- passed
//..\conformance\6_conversions\basic (int_short_E_4.cs) -- passed
//..\conformance\6_conversions\basic (int_ushort_E_1.cs) -- passed
//..\conformance\6_conversions\basic (int_ushort_E_2.cs) -- passed
//..\conformance\6_conversions\basic (int_ushort_E_3.cs) -- passed
//..\conformance\6_conversions\basic (int_ushort_E_4.cs) -- passed
//..\conformance\6_conversions\basic (int_uint_E_1.cs) -- passed
//..\conformance\6_conversions\basic (int_uint_E_2.cs) -- passed
//..\conformance\6_conversions\basic (int_uint_E_3.cs) -- passed
//..\conformance\6_conversions\basic (int_ulong_E_1.cs) -- passed
//..\conformance\6_conversions\basic (int_char_E_1.cs) -- passed
//..\conformance\6_conversions\basic (int_char_E_2.cs) -- passed
//..\conformance\6_conversions\basic (int_char_E_3.cs) -- passed
//..\conformance\6_conversions\basic (int_char_E_4.cs) -- passed
//..\conformance\6_conversions\basic (long_long_I_0.cs) -- passed
//..\conformance\6_conversions\basic (long_long_E_0.cs) -- passed
//..\conformance\6_conversions\basic (long_float_I_0.cs) -- passed
//..\conformance\6_conversions\basic (long_float_E_0.cs) -- passed
//..\conformance\6_conversions\basic (long_double_I_0.cs) -- passed
//..\conformance\6_conversions\basic (long_double_E_0.cs) -- passed
//..\conformance\6_conversions\basic (long_sbyte_E_1.cs) -- passed
//..\conformance\6_conversions\basic (long_sbyte_E_2.cs) -- passed
//..\conformance\6_conversions\basic (long_sbyte_E_3.cs) -- passed
//..\conformance\6_conversions\basic (long_sbyte_E_4.cs) -- passed
//..\conformance\6_conversions\basic (long_byte_E_1.cs) -- passed
//..\conformance\6_conversions\basic (long_byte_E_2.cs) -- passed
//..\conformance\6_conversions\basic (long_byte_E_3.cs) -- passed
//..\conformance\6_conversions\basic (long_byte_E_4.cs) -- passed
//..\conformance\6_conversions\basic (long_short_E_1.cs) -- passed
//..\conformance\6_conversions\basic (long_short_E_2.cs) -- passed
//..\conformance\6_conversions\basic (long_short_E_3.cs) -- passed
//..\conformance\6_conversions\basic (long_short_E_4.cs) -- passed
//..\conformance\6_conversions\basic (long_ushort_E_1.cs) -- passed
//..\conformance\6_conversions\basic (long_ushort_E_2.cs) -- passed
//..\conformance\6_conversions\basic (long_ushort_E_3.cs) -- passed
//..\conformance\6_conversions\basic (long_ushort_E_4.cs) -- passed
//..\conformance\6_conversions\basic (long_int_E_1.cs) -- passed
//..\conformance\6_conversions\basic (long_int_E_2.cs) -- passed
//..\conformance\6_conversions\basic (long_int_E_3.cs) -- passed
//..\conformance\6_conversions\basic (long_int_E_4.cs) -- passed
//..\conformance\6_conversions\basic (long_uint_E_1.cs) -- passed
//..\conformance\6_conversions\basic (long_uint_E_2.cs) -- passed
//..\conformance\6_conversions\basic (long_uint_E_3.cs) -- passed
//..\conformance\6_conversions\basic (long_uint_E_4.cs) -- passed
//..\conformance\6_conversions\basic (long_ulong_E_1.cs) -- passed
//..\conformance\6_conversions\basic (long_ulong_E_2.cs) -- passed
//..\conformance\6_conversions\basic (long_char_E_1.cs) -- passed
//..\conformance\6_conversions\basic (long_char_E_2.cs) -- passed
//..\conformance\6_conversions\basic (long_char_E_3.cs) -- passed
//..\conformance\6_conversions\basic (long_char_E_4.cs) -- passed
//..\conformance\6_conversions\basic (sbyte_sbyte_I_0.cs) -- passed
//..\conformance\6_conversions\basic (sbyte_sbyte_E_0.cs) -- passed
//..\conformance\6_conversions\basic (sbyte_short_I_0.cs) -- passed
//..\conformance\6_conversions\basic (sbyte_short_E_0.cs) -- passed
//..\conformance\6_conversions\basic (sbyte_int_I_0.cs) -- passed
//..\conformance\6_conversions\basic (sbyte_int_E_0.cs) -- passed
//..\conformance\6_conversions\basic (sbyte_long_I_0.cs) -- passed
//..\conformance\6_conversions\basic (sbyte_long_E_0.cs) -- passed
//..\conformance\6_conversions\basic (sbyte_float_I_0.cs) -- passed
//..\conformance\6_conversions\basic (sbyte_float_E_0.cs) -- passed
//..\conformance\6_conversions\basic (sbyte_double_I_0.cs) -- passed
//..\conformance\6_conversions\basic (sbyte_double_E_0.cs) -- passed
//..\conformance\6_conversions\basic (sbyte_byte_E_1.cs) -- passed
//..\conformance\6_conversions\basic (sbyte_byte_E_2.cs) -- passed
//..\conformance\6_conversions\basic (sbyte_byte_E_3.cs) -- passed
//..\conformance\6_conversions\basic (sbyte_ushort_E_1.cs) -- passed
//..\conformance\6_conversions\basic (sbyte_uint_E_1.cs) -- passed
//..\conformance\6_conversions\basic (sbyte_ulong_E_1.cs) -- passed
//..\conformance\6_conversions\basic (sbyte_char_E_1.cs) -- passed
//..\conformance\6_conversions\basic (short_short_I_0.cs) -- passed
//..\conformance\6_conversions\basic (short_short_E_0.cs) -- passed
//..\conformance\6_conversions\basic (short_int_I_0.cs) -- passed
//..\conformance\6_conversions\basic (short_int_E_0.cs) -- passed
//..\conformance\6_conversions\basic (short_long_I_0.cs) -- passed
//..\conformance\6_conversions\basic (short_long_E_0.cs) -- passed
//..\conformance\6_conversions\basic (short_float_I_0.cs) -- passed
//..\conformance\6_conversions\basic (short_float_E_0.cs) -- passed
//..\conformance\6_conversions\basic (short_double_I_0.cs) -- passed
//..\conformance\6_conversions\basic (short_double_E_0.cs) -- passed
//..\conformance\6_conversions\basic (short_short_I_1.cs) -- passed
//..\conformance\6_conversions\basic (short_short_E_1.cs) -- passed
//..\conformance\6_conversions\basic (short_int_I_1.cs) -- passed
//..\conformance\6_conversions\basic (short_int_E_1.cs) -- passed
//..\conformance\6_conversions\basic (short_long_I_1.cs) -- passed
//..\conformance\6_conversions\basic (short_long_E_1.cs) -- passed
//..\conformance\6_conversions\basic (short_float_I_1.cs) -- passed
//..\conformance\6_conversions\basic (short_float_E_1.cs) -- passed
//..\conformance\6_conversions\basic (short_double_I_1.cs) -- passed
//..\conformance\6_conversions\basic (short_double_E_1.cs) -- passed
//..\conformance\6_conversions\basic (short_decimal_I_1.cs) -- passed
//..\conformance\6_conversions\basic (short_decimal_E_1.cs) -- passed
//..\conformance\6_conversions\basic (short_sbyte_E_1.cs) -- passed
//..\conformance\6_conversions\basic (short_sbyte_E_2.cs) -- passed
//..\conformance\6_conversions\basic (short_sbyte_E_3.cs) -- passed
//..\conformance\6_conversions\basic (short_sbyte_E_4.cs) -- passed
//..\conformance\6_conversions\basic (short_byte_E_1.cs) -- passed
//..\conformance\6_conversions\basic (short_byte_E_2.cs) -- passed
//..\conformance\6_conversions\basic (short_byte_E_3.cs) -- passed
//..\conformance\6_conversions\basic (short_byte_E_4.cs) -- passed
//..\conformance\6_conversions\basic (short_ushort_E_1.cs) -- passed
//..\conformance\6_conversions\basic (short_ushort_E_2.cs) -- passed
//..\conformance\6_conversions\basic (short_ushort_E_3.cs) -- passed
//..\conformance\6_conversions\basic (short_uint_E_1.cs) -- passed
//..\conformance\6_conversions\basic (short_ulong_E_1.cs) -- passed
//..\conformance\6_conversions\basic (short_char_E_1.cs) -- passed
//..\conformance\6_conversions\basic (short_char_E_2.cs) -- passed
//..\conformance\6_conversions\basic (short_char_E_3.cs) -- passed
//..\conformance\6_conversions\basic (uint_uint_I_0.cs) -- passed
//..\conformance\6_conversions\basic (uint_uint_E_0.cs) -- passed
//..\conformance\6_conversions\basic (uint_long_I_0.cs) -- passed
//..\conformance\6_conversions\basic (uint_long_E_0.cs) -- passed
//..\conformance\6_conversions\basic (uint_ulong_I_0.cs) -- passed
//..\conformance\6_conversions\basic (uint_ulong_E_0.cs) -- passed
//..\conformance\6_conversions\basic (uint_float_I_0.cs) -- passed
//..\conformance\6_conversions\basic (uint_float_E_0.cs) -- passed
//..\conformance\6_conversions\basic (uint_double_I_0.cs) -- passed
//..\conformance\6_conversions\basic (uint_double_E_0.cs) -- passed
//..\conformance\6_conversions\basic (uint_sbyte_E_1.cs) -- passed
//..\conformance\6_conversions\basic (uint_sbyte_E_2.cs) -- passed
//..\conformance\6_conversions\basic (uint_byte_E_1.cs) -- passed
//..\conformance\6_conversions\basic (uint_byte_E_2.cs) -- passed
//..\conformance\6_conversions\basic (uint_byte_E_3.cs) -- passed
//..\conformance\6_conversions\basic (uint_short_E_1.cs) -- passed
//..\conformance\6_conversions\basic (uint_short_E_2.cs) -- passed
//..\conformance\6_conversions\basic (uint_ushort_E_1.cs) -- passed
//..\conformance\6_conversions\basic (uint_ushort_E_2.cs) -- passed
//..\conformance\6_conversions\basic (uint_ushort_E_3.cs) -- passed
//..\conformance\6_conversions\basic (uint_int_E_1.cs) -- passed
//..\conformance\6_conversions\basic (uint_int_E_2.cs) -- passed
//..\conformance\6_conversions\basic (uint_char_E_1.cs) -- passed
//..\conformance\6_conversions\basic (uint_char_E_2.cs) -- passed
//..\conformance\6_conversions\basic (uint_char_E_3.cs) -- passed
//..\conformance\6_conversions\basic (ulong_float_I_0.cs) -- passed
//..\conformance\6_conversions\basic (ulong_float_E_0.cs) -- passed
//..\conformance\6_conversions\basic (ulong_double_I_0.cs) -- passed
//..\conformance\6_conversions\basic (ulong_double_E_0.cs) -- passed
//..\conformance\6_conversions\basic (ulong_ulong_I_0.cs) -- passed
//..\conformance\6_conversions\basic (ulong_ulong_E_0.cs) -- passed
//..\conformance\6_conversions\basic (ulong_sbyte_E_1.cs) -- passed
//..\conformance\6_conversions\basic (ulong_sbyte_E_2.cs) -- passed
//..\conformance\6_conversions\basic (ulong_byte_E_1.cs) -- passed
//..\conformance\6_conversions\basic (ulong_byte_E_2.cs) -- passed
//..\conformance\6_conversions\basic (ulong_byte_E_3.cs) -- passed
//..\conformance\6_conversions\basic (ulong_short_E_1.cs) -- passed
//..\conformance\6_conversions\basic (ulong_short_E_2.cs) -- passed
//..\conformance\6_conversions\basic (ulong_ushort_E_1.cs) -- passed
//..\conformance\6_conversions\basic (ulong_ushort_E_2.cs) -- passed
//..\conformance\6_conversions\basic (ulong_ushort_E_3.cs) -- passed
//..\conformance\6_conversions\basic (ulong_int_E_1.cs) -- passed
//..\conformance\6_conversions\basic (ulong_int_E_2.cs) -- passed
//..\conformance\6_conversions\basic (ulong_uint_E_1.cs) -- passed
//..\conformance\6_conversions\basic (ulong_uint_E_2.cs) -- passed
//..\conformance\6_conversions\basic (ulong_uint_E_3.cs) -- passed
//..\conformance\6_conversions\basic (ulong_long_E_1.cs) -- passed
//..\conformance\6_conversions\basic (ulong_long_E_2.cs) -- passed
//..\conformance\6_conversions\basic (ulong_char_E_1.cs) -- passed
//..\conformance\6_conversions\basic (ulong_char_E_2.cs) -- passed
//..\conformance\6_conversions\basic (ulong_char_E_3.cs) -- passed
//..\conformance\6_conversions\basic (ushort_ushort_I_0.cs) -- passed
//..\conformance\6_conversions\basic (ushort_ushort_E_0.cs) -- passed
//..\conformance\6_conversions\basic (ushort_int_I_0.cs) -- passed
//..\conformance\6_conversions\basic (ushort_int_E_0.cs) -- passed
//..\conformance\6_conversions\basic (ushort_uint_I_0.cs) -- passed
//..\conformance\6_conversions\basic (ushort_uint_E_0.cs) -- passed
//..\conformance\6_conversions\basic (ushort_long_I_0.cs) -- passed
//..\conformance\6_conversions\basic (ushort_long_E_0.cs) -- passed
//..\conformance\6_conversions\basic (ushort_ulong_I_0.cs) -- passed
//..\conformance\6_conversions\basic (ushort_ulong_E_0.cs) -- passed
//..\conformance\6_conversions\basic (ushort_float_I_0.cs) -- passed
//..\conformance\6_conversions\basic (ushort_float_E_0.cs) -- passed
//..\conformance\6_conversions\basic (ushort_double_I_0.cs) -- passed
//..\conformance\6_conversions\basic (ushort_double_E_0.cs) -- passed
//..\conformance\6_conversions\basic (ushort_sbyte_E_1.cs) -- passed
//..\conformance\6_conversions\basic (ushort_sbyte_E_2.cs) -- passed
//..\conformance\6_conversions\basic (ushort_byte_E_1.cs) -- passed
//..\conformance\6_conversions\basic (ushort_byte_E_2.cs) -- passed
//..\conformance\6_conversions\basic (ushort_byte_E_3.cs) -- passed
//..\conformance\6_conversions\basic (ushort_short_E_1.cs) -- passed
//..\conformance\6_conversions\basic (ushort_short_E_2.cs) -- passed
//..\conformance\6_conversions\basic (ushort_char_E_1.cs) -- passed
//..\conformance\6_conversions\basic (ushort_char_E_2.cs) -- passed
//..\conformance\6_conversions\basic (ushort_char_E_3.cs) -- passed
//..\conformance\6_conversions\signun (byte_sbyte_0.cs) -- passed
//..\conformance\6_conversions\signun (byte_sbyte_1.cs) -- passed
//..\conformance\6_conversions\signun (sbyte_byte_0.cs) -- passed
//..\conformance\6_conversions\signun (sbyte_byte_1.cs) -- passed
//..\conformance\6_conversions\signun (ushort_short_0.cs) -- passed
//..\conformance\6_conversions\signun (ushort_short_1.cs) -- passed
//..\conformance\6_conversions\signun (short_ushort_0.cs) -- passed
//..\conformance\6_conversions\signun (short_ushort_1.cs) -- passed
//..\conformance\6_conversions\signun (uint_int_0.cs) -- passed
//..\conformance\6_conversions\signun (uint_int_1.cs) -- passed
//..\conformance\6_conversions\signun (int_uint_0.cs) -- passed
//..\conformance\6_conversions\signun (int_uint_1.cs) -- passed
//..\conformance\6_conversions\signun (ulong_long_0.cs) -- passed
//..\conformance\6_conversions\signun (ulong_long_1.cs) -- passed
//..\conformance\6_conversions\signun (long_ulong_0.cs) -- passed
//..\conformance\6_conversions\signun (long_ulong_1.cs) -- passed
//..\conformance\6_conversions\constant (int_sbyte_0.cs) -- passed
//..\conformance\6_conversions\constant (int_sbyte_1.cs) -- passed
//..\conformance\6_conversions\constant (int_sbyte_2.cs) -- passed
//..\conformance\6_conversions\constant (int_byte_5.cs) -- passed
//..\conformance\6_conversions\constant (int_byte_6.cs) -- passed
//..\conformance\6_conversions\constant (int_byte_7.cs) -- passed
//..\conformance\6_conversions\constant (int_short_10.cs) -- passed
//..\conformance\6_conversions\constant (int_short_11.cs) -- passed
//..\conformance\6_conversions\constant (int_short_12.cs) -- passed
//..\conformance\6_conversions\constant (int_ushort_15.cs) -- passed
//..\conformance\6_conversions\constant (int_ushort_16.cs) -- passed
//..\conformance\6_conversions\constant (int_ushort_17.cs) -- passed
//..\conformance\6_conversions\constant (int_uint_20.cs) -- passed
//..\conformance\6_conversions\constant (int_uint_21.cs) -- passed
//..\conformance\6_conversions\constant (int_uint_22.cs) -- passed
//..\conformance\6_conversions\constant (int_ulong_25.cs) -- passed
//..\conformance\6_conversions\constant (int_ulong_26.cs) -- passed
//..\conformance\6_conversions\constant (int_ulong_27.cs) -- passed


}
