//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=2.0.50727.1432.
// 

using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.ComponentModel;
using System.Diagnostics;
using System.Xml.Serialization;

namespace XsdScatterfileSchemaObject {
    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.1432")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(AnonymousType=true, Namespace="http://schemas.microsoft.com/netmf/ScatterfileSchema.xsd")]
    [XmlRoot(Namespace="http://schemas.microsoft.com/netmf/ScatterfileSchema.xsd", IsNullable=false)]
    public partial class ScatterFile {
        
        private List<Set> setField;
        
        private List<If> ifField;
        
        private List<IfDefined> ifDefinedField;
        
        private List<IfNotDefined> ifNotDefinedField;
        
        private List<LoadRegion> loadRegionField;
        
        /// <remarks/>
        [XmlElement("Set")]
        public List<Set> Set {
            get {
                return this.setField;
            }
            set {
                this.setField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement("If")]
        public List<If> If {
            get {
                return this.ifField;
            }
            set {
                this.ifField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement("IfDefined")]
        public List<IfDefined> IfDefined {
            get {
                return this.ifDefinedField;
            }
            set {
                this.ifDefinedField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement("IfNotDefined")]
        public List<IfNotDefined> IfNotDefined {
            get {
                return this.ifNotDefinedField;
            }
            set {
                this.ifNotDefinedField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement("LoadRegion")]
        public List<LoadRegion> LoadRegion {
            get {
                return this.loadRegionField;
            }
            set {
                this.loadRegionField = value;
            }
        }
    }
    
    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.1432")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(Namespace="http://schemas.microsoft.com/netmf/ScatterfileSchema.xsd")]
    public partial class Set {
        
        private string nameField;
        
        private string valueField;
        
        /// <remarks/>
        [XmlAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.1432")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(Namespace="http://schemas.microsoft.com/netmf/ScatterfileSchema.xsd")]
    public partial class Error {
        
        private string messageField;
        
        /// <remarks/>
        [XmlAttribute()]
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
    }
    
    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.1432")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(Namespace="http://schemas.microsoft.com/netmf/ScatterfileSchema.xsd")]
    public partial class IfNotDefined {
        
        private List<FileMapping> fileMappingField;
        
        private List<LoadRegion> loadRegionField;
        
        private List<ExecRegion> execRegionField;
        
        private List<IfDefined> ifDefinedField;
        
        private List<IfNotDefined> ifNotDefined1Field;
        
        private List<If> ifField;
        
        private string nameField;
        
        /// <remarks/>
        [XmlElement("FileMapping")]
        public List<FileMapping> FileMapping {
            get {
                return this.fileMappingField;
            }
            set {
                this.fileMappingField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement("LoadRegion")]
        public List<LoadRegion> LoadRegion {
            get {
                return this.loadRegionField;
            }
            set {
                this.loadRegionField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement("ExecRegion")]
        public List<ExecRegion> ExecRegion {
            get {
                return this.execRegionField;
            }
            set {
                this.execRegionField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement("IfDefined")]
        public List<IfDefined> IfDefined {
            get {
                return this.ifDefinedField;
            }
            set {
                this.ifDefinedField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement("IfNotDefined")]
        public List<IfNotDefined> IfNotDefined1 {
            get {
                return this.ifNotDefined1Field;
            }
            set {
                this.ifNotDefined1Field = value;
            }
        }
        
        /// <remarks/>
        [XmlElement("If")]
        public List<If> If {
            get {
                return this.ifField;
            }
            set {
                this.ifField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.1432")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(Namespace="http://schemas.microsoft.com/netmf/ScatterfileSchema.xsd")]
    public partial class FileMapping {
        
        private string nameField;
        
        private string optionsField;
        
        /// <remarks/>
        [XmlAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string Options {
            get {
                return this.optionsField;
            }
            set {
                this.optionsField = value;
            }
        }
    }
    
    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.1432")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(Namespace="http://schemas.microsoft.com/netmf/ScatterfileSchema.xsd")]
    public partial class LoadRegion {
        
        private List<ExecRegion> execRegionField;
        
        private List<If> ifField;
        
        private List<IfDefined> ifDefinedField;
        
        private List<IfNotDefined> ifNotDefinedField;
        
        private string nameField;
        
        private string baseField;
        
        private string optionsField;
        
        private string sizeField;
        
        /// <remarks/>
        [XmlElement("ExecRegion")]
        public List<ExecRegion> ExecRegion {
            get {
                return this.execRegionField;
            }
            set {
                this.execRegionField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement("If")]
        public List<If> If {
            get {
                return this.ifField;
            }
            set {
                this.ifField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement("IfDefined")]
        public List<IfDefined> IfDefined {
            get {
                return this.ifDefinedField;
            }
            set {
                this.ifDefinedField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement("IfNotDefined")]
        public List<IfNotDefined> IfNotDefined {
            get {
                return this.ifNotDefinedField;
            }
            set {
                this.ifNotDefinedField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string Base {
            get {
                return this.baseField;
            }
            set {
                this.baseField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string Options {
            get {
                return this.optionsField;
            }
            set {
                this.optionsField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string Size {
            get {
                return this.sizeField;
            }
            set {
                this.sizeField = value;
            }
        }
    }
    
    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.1432")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(Namespace="http://schemas.microsoft.com/netmf/ScatterfileSchema.xsd")]
    public partial class ExecRegion {
        
        private List<FileMapping> fileMappingField;
        
        private List<If> ifField;
        
        private List<IfDefined> ifDefinedField;
        
        private List<IfNotDefined> ifNotDefinedField;
        
        private string nameField;
        
        private string baseField;
        
        private string optionsField;
        
        private string sizeField;
        
        /// <remarks/>
        [XmlElement("FileMapping")]
        public List<FileMapping> FileMapping {
            get {
                return this.fileMappingField;
            }
            set {
                this.fileMappingField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement("If")]
        public List<If> If {
            get {
                return this.ifField;
            }
            set {
                this.ifField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement("IfDefined")]
        public List<IfDefined> IfDefined {
            get {
                return this.ifDefinedField;
            }
            set {
                this.ifDefinedField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement("IfNotDefined")]
        public List<IfNotDefined> IfNotDefined {
            get {
                return this.ifNotDefinedField;
            }
            set {
                this.ifNotDefinedField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string Base {
            get {
                return this.baseField;
            }
            set {
                this.baseField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string Options {
            get {
                return this.optionsField;
            }
            set {
                this.optionsField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string Size {
            get {
                return this.sizeField;
            }
            set {
                this.sizeField = value;
            }
        }
    }
    
    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.1432")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(Namespace="http://schemas.microsoft.com/netmf/ScatterfileSchema.xsd")]
    public partial class If {
        
        private List<Set> setField;
        
        private List<If> if1Field;
        
        private List<IfDefined> ifDefinedField;
        
        private List<IfNotDefined> ifNotDefinedField;
        
        private Error errorField;
        
        private List<FileMapping> fileMappingField;
        
        private List<LoadRegion> loadRegionField;
        
        private List<ExecRegion> execRegionField;
        
        private string nameField;
        
        private string valueField;
        
        private string inField;
        
        /// <remarks/>
        [XmlElement("Set")]
        public List<Set> Set {
            get {
                return this.setField;
            }
            set {
                this.setField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement("If")]
        public List<If> If1 {
            get {
                return this.if1Field;
            }
            set {
                this.if1Field = value;
            }
        }
        
        /// <remarks/>
        [XmlElement("IfDefined")]
        public List<IfDefined> IfDefined {
            get {
                return this.ifDefinedField;
            }
            set {
                this.ifDefinedField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement("IfNotDefined")]
        public List<IfNotDefined> IfNotDefined {
            get {
                return this.ifNotDefinedField;
            }
            set {
                this.ifNotDefinedField = value;
            }
        }
        
        /// <remarks/>
        public Error Error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement("FileMapping")]
        public List<FileMapping> FileMapping {
            get {
                return this.fileMappingField;
            }
            set {
                this.fileMappingField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement("LoadRegion")]
        public List<LoadRegion> LoadRegion {
            get {
                return this.loadRegionField;
            }
            set {
                this.loadRegionField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement("ExecRegion")]
        public List<ExecRegion> ExecRegion {
            get {
                return this.execRegionField;
            }
            set {
                this.execRegionField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string In {
            get {
                return this.inField;
            }
            set {
                this.inField = value;
            }
        }
    }
    
    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.1432")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(Namespace="http://schemas.microsoft.com/netmf/ScatterfileSchema.xsd")]
    public partial class IfDefined {
        
        private List<FileMapping> fileMappingField;
        
        private List<LoadRegion> loadRegionField;
        
        private List<ExecRegion> execRegionField;
        
        private List<IfDefined> ifDefined1Field;
        
        private List<IfNotDefined> ifNotDefinedField;
        
        private List<If> ifField;
        
        private string nameField;
        
        /// <remarks/>
        [XmlElement("FileMapping")]
        public List<FileMapping> FileMapping {
            get {
                return this.fileMappingField;
            }
            set {
                this.fileMappingField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement("LoadRegion")]
        public List<LoadRegion> LoadRegion {
            get {
                return this.loadRegionField;
            }
            set {
                this.loadRegionField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement("ExecRegion")]
        public List<ExecRegion> ExecRegion {
            get {
                return this.execRegionField;
            }
            set {
                this.execRegionField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement("IfDefined")]
        public List<IfDefined> IfDefined1 {
            get {
                return this.ifDefined1Field;
            }
            set {
                this.ifDefined1Field = value;
            }
        }
        
        /// <remarks/>
        [XmlElement("IfNotDefined")]
        public List<IfNotDefined> IfNotDefined {
            get {
                return this.ifNotDefinedField;
            }
            set {
                this.ifNotDefinedField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement("If")]
        public List<If> If {
            get {
                return this.ifField;
            }
            set {
                this.ifField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
}
