#ifndef _CMSIS_RTOS_PROCESSOR_SELECTOR_H_
#define _CMSIS_RTOS_PROCESSOR_SELECTOR_H_ 1
#include "cmsis_os.h"

#define PLATFORM_ARM 1 
#define PLATFORM_ARM_OS_PORT 1

#endif //_CMSIS_RTOS_PROCESSOR_SELECTOR_H_
