////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// Copyright (c) Microsoft Corporation.  All rights reserved.
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

#include "system_xml.h"

const CLR_UINT16 c_XmlCharType[] =
{
    /*  000 0x00    "\0"        */  XmlCharType_NCNameInvalid | XmlCharType_None,
    /*  001 0x01    illegal     */  XmlCharType_NCNameInvalid | XmlCharType_None,
    /*  002 0x02    illegal     */  XmlCharType_NCNameInvalid | XmlCharType_None,
    /*  003 0x03    illegal     */  XmlCharType_NCNameInvalid | XmlCharType_None,
    /*  004 0x04    illegal     */  XmlCharType_NCNameInvalid | XmlCharType_None,
    /*  005 0x05    illegal     */  XmlCharType_NCNameInvalid | XmlCharType_None,
    /*  006 0x06    illegal     */  XmlCharType_NCNameInvalid | XmlCharType_None,
    /*  007 0x07    illegal     */  XmlCharType_NCNameInvalid | XmlCharType_None,
    /*  008 0x08    illegal     */  XmlCharType_NCNameInvalid | XmlCharType_None,
    /*  009 0x09    "\t"        */  XmlCharType_NCNameInvalid | XmlCharType_Space | XmlCharType_Whitespace | XmlCharType_Text | XmlCharType_CDATA | XmlCharType_Comment | XmlCharType_PI,
    /*  010 0x0A    "\n"        */  XmlCharType_NCNameInvalid | XmlCharType_Space | XmlCharType_Whitespace | XmlCharType_Text | XmlCharType_CDATA | XmlCharType_Comment | XmlCharType_PI,
    /*  011 0x0B    illegal     */  XmlCharType_NCNameInvalid | XmlCharType_None,
    /*  012 0x0C    illegal     */  XmlCharType_NCNameInvalid | XmlCharType_None,
    /*  013 0x0D    "\r"        */  XmlCharType_NCNameInvalid | XmlCharType_Space,
    /*  014 0x0E    illegal     */  XmlCharType_NCNameInvalid | XmlCharType_None,
    /*  015 0x0F    illegal     */  XmlCharType_NCNameInvalid | XmlCharType_None,
    /*  016 0x10    illegal     */  XmlCharType_NCNameInvalid | XmlCharType_None,
    /*  017 0x11    illegal     */  XmlCharType_NCNameInvalid | XmlCharType_None,
    /*  018 0x12    illegal     */  XmlCharType_NCNameInvalid | XmlCharType_None,
    /*  019 0x13    illegal     */  XmlCharType_NCNameInvalid | XmlCharType_None,
    /*  020 0x14    illegal     */  XmlCharType_NCNameInvalid | XmlCharType_None,
    /*  021 0x15    illegal     */  XmlCharType_NCNameInvalid | XmlCharType_None,
    /*  022 0x16    illegal     */  XmlCharType_NCNameInvalid | XmlCharType_None,
    /*  023 0x17    illegal     */  XmlCharType_NCNameInvalid | XmlCharType_None,
    /*  024 0x18    illegal     */  XmlCharType_NCNameInvalid | XmlCharType_None,
    /*  025 0x19    illegal     */  XmlCharType_NCNameInvalid | XmlCharType_None,
    /*  026 0x1A    illegal     */  XmlCharType_NCNameInvalid | XmlCharType_None,
    /*  027 0x1B    illegal     */  XmlCharType_NCNameInvalid | XmlCharType_None,
    /*  028 0x1C    illegal     */  XmlCharType_NCNameInvalid | XmlCharType_None,
    /*  029 0x1D    illegal     */  XmlCharType_NCNameInvalid | XmlCharType_None,
    /*  030 0x1E    illegal     */  XmlCharType_NCNameInvalid | XmlCharType_None,
    /*  031 0x1F    illegal     */  XmlCharType_NCNameInvalid | XmlCharType_None,
    /*  032 0x20    " "         */  XmlCharType_NCNameInvalid | XmlCharType_Space | XmlCharType_Whitespace | XmlCharType_AttributeDQuote | XmlCharType_AttributeSQuote | XmlCharType_Text | XmlCharType_CDATA | XmlCharType_Comment | XmlCharType_PI,
    /*  033 0x21    "!"         */  XmlCharType_NCNameInvalid | XmlCharType_AttributeDQuote | XmlCharType_AttributeSQuote | XmlCharType_Text | XmlCharType_CDATA | XmlCharType_Comment | XmlCharType_PI,
    /*  034 0x22    """         */  XmlCharType_NCNameInvalid | XmlCharType_AttributeSQuote | XmlCharType_Text | XmlCharType_CDATA | XmlCharType_Comment | XmlCharType_PI,
    /*  035 0x23    "#"         */  XmlCharType_NCNameInvalid | XmlCharType_AttributeDQuote | XmlCharType_AttributeSQuote | XmlCharType_Text | XmlCharType_CDATA | XmlCharType_Comment | XmlCharType_PI,
    /*  036 0x24    "$"         */  XmlCharType_NCNameInvalid | XmlCharType_AttributeDQuote | XmlCharType_AttributeSQuote | XmlCharType_Text | XmlCharType_CDATA | XmlCharType_Comment | XmlCharType_PI,
    /*  037 0x25    "%"         */  XmlCharType_NCNameInvalid | XmlCharType_AttributeDQuote | XmlCharType_AttributeSQuote | XmlCharType_Text | XmlCharType_CDATA | XmlCharType_Comment | XmlCharType_PI,
    /*  038 0x26    "&"         */  XmlCharType_NCNameInvalid | XmlCharType_CDATA | XmlCharType_Comment | XmlCharType_PI,
    /*  039 0x27    "'"         */  XmlCharType_NCNameInvalid | XmlCharType_AttributeDQuote | XmlCharType_Text | XmlCharType_CDATA | XmlCharType_Comment | XmlCharType_PI,
    /*  040 0x28    "("         */  XmlCharType_NCNameInvalid | XmlCharType_AttributeDQuote | XmlCharType_AttributeSQuote | XmlCharType_Text | XmlCharType_CDATA | XmlCharType_Comment | XmlCharType_PI,
    /*  041 0x29    ")"         */  XmlCharType_NCNameInvalid | XmlCharType_AttributeDQuote | XmlCharType_AttributeSQuote | XmlCharType_Text | XmlCharType_CDATA | XmlCharType_Comment | XmlCharType_PI,
    /*  042 0x2A    "*"         */  XmlCharType_NCNameInvalid | XmlCharType_AttributeDQuote | XmlCharType_AttributeSQuote | XmlCharType_Text | XmlCharType_CDATA | XmlCharType_Comment | XmlCharType_PI,
    /*  043 0x2B    "+"         */  XmlCharType_NCNameInvalid | XmlCharType_AttributeDQuote | XmlCharType_AttributeSQuote | XmlCharType_Text | XmlCharType_CDATA | XmlCharType_Comment | XmlCharType_PI,
    /*  044 0x2C    ","         */  XmlCharType_NCNameInvalid | XmlCharType_AttributeDQuote | XmlCharType_AttributeSQuote | XmlCharType_Text | XmlCharType_CDATA | XmlCharType_Comment | XmlCharType_PI,
    /*  045 0x2D    "-"         */  XmlCharType_NCNameChar1 | XmlCharType_AttributeDQuote | XmlCharType_AttributeSQuote | XmlCharType_Text | XmlCharType_CDATA | XmlCharType_PI,
    /*  046 0x2E    "."         */  XmlCharType_NCNameChar1 | XmlCharType_AttributeDQuote | XmlCharType_AttributeSQuote | XmlCharType_Text | XmlCharType_CDATA | XmlCharType_Comment | XmlCharType_PI,
    /*  047 0x2F    "/"         */  XmlCharType_NCNameInvalid | XmlCharType_Slash | XmlCharType_AttributeDQuote | XmlCharType_AttributeSQuote | XmlCharType_Text | XmlCharType_CDATA | XmlCharType_Comment | XmlCharType_PI,
    /*  048 0x30    "0"         */  XmlCharType_NCNameChar1 | XmlCharType_AttributeDQuote | XmlCharType_AttributeSQuote | XmlCharType_Text | XmlCharType_CDATA | XmlCharType_Comment | XmlCharType_PI,
    /*  049 0x31    "1"         */  XmlCharType_NCNameChar1 | XmlCharType_AttributeDQuote | XmlCharType_AttributeSQuote | XmlCharType_Text | XmlCharType_CDATA | XmlCharType_Comment | XmlCharType_PI,
    /*  050 0x32    "2"         */  XmlCharType_NCNameChar1 | XmlCharType_AttributeDQuote | XmlCharType_AttributeSQuote | XmlCharType_Text | XmlCharType_CDATA | XmlCharType_Comment | XmlCharType_PI,
    /*  051 0x33    "3"         */  XmlCharType_NCNameChar1 | XmlCharType_AttributeDQuote | XmlCharType_AttributeSQuote | XmlCharType_Text | XmlCharType_CDATA | XmlCharType_Comment | XmlCharType_PI,
    /*  052 0x34    "4"         */  XmlCharType_NCNameChar1 | XmlCharType_AttributeDQuote | XmlCharType_AttributeSQuote | XmlCharType_Text | XmlCharType_CDATA | XmlCharType_Comment | XmlCharType_PI,
    /*  053 0x35    "5"         */  XmlCharType_NCNameChar1 | XmlCharType_AttributeDQuote | XmlCharType_AttributeSQuote | XmlCharType_Text | XmlCharType_CDATA | XmlCharType_Comment | XmlCharType_PI,
    /*  054 0x36    "6"         */  XmlCharType_NCNameChar1 | XmlCharType_AttributeDQuote | XmlCharType_AttributeSQuote | XmlCharType_Text | XmlCharType_CDATA | XmlCharType_Comment | XmlCharType_PI,
    /*  055 0x37    "7"         */  XmlCharType_NCNameChar1 | XmlCharType_AttributeDQuote | XmlCharType_AttributeSQuote | XmlCharType_Text | XmlCharType_CDATA | XmlCharType_Comment | XmlCharType_PI,
    /*  056 0x38    "8"         */  XmlCharType_NCNameChar1 | XmlCharType_AttributeDQuote | XmlCharType_AttributeSQuote | XmlCharType_Text | XmlCharType_CDATA | XmlCharType_Comment | XmlCharType_PI,
    /*  057 0x39    "9"         */  XmlCharType_NCNameChar1 | XmlCharType_AttributeDQuote | XmlCharType_AttributeSQuote | XmlCharType_Text | XmlCharType_CDATA | XmlCharType_Comment | XmlCharType_PI,
    /*  058 0x3A    ":"         */  XmlCharType_NCNameInvalid | XmlCharType_Colon | XmlCharType_AttributeDQuote | XmlCharType_AttributeSQuote | XmlCharType_Text | XmlCharType_CDATA | XmlCharType_Comment | XmlCharType_PI,
    /*  059 0x3B    ";"         */  XmlCharType_NCNameInvalid | XmlCharType_AttributeDQuote | XmlCharType_AttributeSQuote | XmlCharType_Text | XmlCharType_CDATA | XmlCharType_Comment | XmlCharType_PI,
    /*  060 0x3C    "<"         */  XmlCharType_NCNameInvalid | XmlCharType_CDATA | XmlCharType_Comment | XmlCharType_PI,
    /*  061 0x3D    "="         */  XmlCharType_NCNameInvalid | XmlCharType_Equal | XmlCharType_AttributeDQuote | XmlCharType_AttributeSQuote | XmlCharType_Text | XmlCharType_CDATA | XmlCharType_Comment | XmlCharType_PI,
    /*  062 0x3E    ">"         */  XmlCharType_NCNameInvalid | XmlCharType_GT | XmlCharType_AttributeDQuote | XmlCharType_AttributeSQuote | XmlCharType_Text | XmlCharType_CDATA | XmlCharType_Comment | XmlCharType_PI,
    /*  063 0x3F    "?"         */  XmlCharType_NCNameInvalid | XmlCharType_Question | XmlCharType_AttributeDQuote | XmlCharType_AttributeSQuote | XmlCharType_Text | XmlCharType_CDATA | XmlCharType_Comment,
    /*  064 0x40    "@"         */  XmlCharType_NCNameInvalid | XmlCharType_AttributeDQuote | XmlCharType_AttributeSQuote | XmlCharType_Text | XmlCharType_CDATA | XmlCharType_Comment | XmlCharType_PI,
    /*  065 0x41    "A"         */  XmlCharType_NCNameStartChar1 | XmlCharType_AttributeDQuote | XmlCharType_AttributeSQuote | XmlCharType_Text | XmlCharType_CDATA | XmlCharType_Comment | XmlCharType_PI,
    /*  066 0x42    "B"         */  XmlCharType_NCNameStartChar1 | XmlCharType_AttributeDQuote | XmlCharType_AttributeSQuote | XmlCharType_Text | XmlCharType_CDATA | XmlCharType_Comment | XmlCharType_PI,
    /*  067 0x43    "C"         */  XmlCharType_NCNameStartChar1 | XmlCharType_AttributeDQuote | XmlCharType_AttributeSQuote | XmlCharType_Text | XmlCharType_CDATA | XmlCharType_Comment | XmlCharType_PI,
    /*  068 0x44    "D"         */  XmlCharType_NCNameStartChar1 | XmlCharType_AttributeDQuote | XmlCharType_AttributeSQuote | XmlCharType_Text | XmlCharType_CDATA | XmlCharType_Comment | XmlCharType_PI,
    /*  069 0x45    "E"         */  XmlCharType_NCNameStartChar1 | XmlCharType_AttributeDQuote | XmlCharType_AttributeSQuote | XmlCharType_Text | XmlCharType_CDATA | XmlCharType_Comment | XmlCharType_PI,
    /*  070 0x46    "F"         */  XmlCharType_NCNameStartChar1 | XmlCharType_AttributeDQuote | XmlCharType_AttributeSQuote | XmlCharType_Text | XmlCharType_CDATA | XmlCharType_Comment | XmlCharType_PI,
    /*  071 0x47    "G"         */  XmlCharType_NCNameStartChar1 | XmlCharType_AttributeDQuote | XmlCharType_AttributeSQuote | XmlCharType_Text | XmlCharType_CDATA | XmlCharType_Comment | XmlCharType_PI,
    /*  072 0x48    "H"         */  XmlCharType_NCNameStartChar1 | XmlCharType_AttributeDQuote | XmlCharType_AttributeSQuote | XmlCharType_Text | XmlCharType_CDATA | XmlCharType_Comment | XmlCharType_PI,
    /*  073 0x49    "I"         */  XmlCharType_NCNameStartChar1 | XmlCharType_AttributeDQuote | XmlCharType_AttributeSQuote | XmlCharType_Text | XmlCharType_CDATA | XmlCharType_Comment | XmlCharType_PI,
    /*  074 0x4A    "J"         */  XmlCharType_NCNameStartChar1 | XmlCharType_AttributeDQuote | XmlCharType_AttributeSQuote | XmlCharType_Text | XmlCharType_CDATA | XmlCharType_Comment | XmlCharType_PI,
    /*  075 0x4B    "K"         */  XmlCharType_NCNameStartChar1 | XmlCharType_AttributeDQuote | XmlCharType_AttributeSQuote | XmlCharType_Text | XmlCharType_CDATA | XmlCharType_Comment | XmlCharType_PI,
    /*  076 0x4C    "L"         */  XmlCharType_NCNameStartChar1 | XmlCharType_AttributeDQuote | XmlCharType_AttributeSQuote | XmlCharType_Text | XmlCharType_CDATA | XmlCharType_Comment | XmlCharType_PI,
    /*  077 0x4D    "M"         */  XmlCharType_NCNameStartChar1 | XmlCharType_AttributeDQuote | XmlCharType_AttributeSQuote | XmlCharType_Text | XmlCharType_CDATA | XmlCharType_Comment | XmlCharType_PI,
    /*  078 0x4E    "N"         */  XmlCharType_NCNameStartChar1 | XmlCharType_AttributeDQuote | XmlCharType_AttributeSQuote | XmlCharType_Text | XmlCharType_CDATA | XmlCharType_Comment | XmlCharType_PI,
    /*  079 0x4F    "O"         */  XmlCharType_NCNameStartChar1 | XmlCharType_AttributeDQuote | XmlCharType_AttributeSQuote | XmlCharType_Text | XmlCharType_CDATA | XmlCharType_Comment | XmlCharType_PI,
    /*  080 0x50    "P"         */  XmlCharType_NCNameStartChar1 | XmlCharType_AttributeDQuote | XmlCharType_AttributeSQuote | XmlCharType_Text | XmlCharType_CDATA | XmlCharType_Comment | XmlCharType_PI,
    /*  081 0x51    "Q"         */  XmlCharType_NCNameStartChar1 | XmlCharType_AttributeDQuote | XmlCharType_AttributeSQuote | XmlCharType_Text | XmlCharType_CDATA | XmlCharType_Comment | XmlCharType_PI,
    /*  082 0x52    "R"         */  XmlCharType_NCNameStartChar1 | XmlCharType_AttributeDQuote | XmlCharType_AttributeSQuote | XmlCharType_Text | XmlCharType_CDATA | XmlCharType_Comment | XmlCharType_PI,
    /*  083 0x53    "S"         */  XmlCharType_NCNameStartChar1 | XmlCharType_AttributeDQuote | XmlCharType_AttributeSQuote | XmlCharType_Text | XmlCharType_CDATA | XmlCharType_Comment | XmlCharType_PI,
    /*  084 0x54    "T"         */  XmlCharType_NCNameStartChar1 | XmlCharType_AttributeDQuote | XmlCharType_AttributeSQuote | XmlCharType_Text | XmlCharType_CDATA | XmlCharType_Comment | XmlCharType_PI,
    /*  085 0x55    "U"         */  XmlCharType_NCNameStartChar1 | XmlCharType_AttributeDQuote | XmlCharType_AttributeSQuote | XmlCharType_Text | XmlCharType_CDATA | XmlCharType_Comment | XmlCharType_PI,
    /*  086 0x56    "V"         */  XmlCharType_NCNameStartChar1 | XmlCharType_AttributeDQuote | XmlCharType_AttributeSQuote | XmlCharType_Text | XmlCharType_CDATA | XmlCharType_Comment | XmlCharType_PI,
    /*  087 0x57    "W"         */  XmlCharType_NCNameStartChar1 | XmlCharType_AttributeDQuote | XmlCharType_AttributeSQuote | XmlCharType_Text | XmlCharType_CDATA | XmlCharType_Comment | XmlCharType_PI,
    /*  088 0x58    "X"         */  XmlCharType_NCNameStartChar1 | XmlCharType_AttributeDQuote | XmlCharType_AttributeSQuote | XmlCharType_Text | XmlCharType_CDATA | XmlCharType_Comment | XmlCharType_PI,
    /*  089 0x59    "Y"         */  XmlCharType_NCNameStartChar1 | XmlCharType_AttributeDQuote | XmlCharType_AttributeSQuote | XmlCharType_Text | XmlCharType_CDATA | XmlCharType_Comment | XmlCharType_PI,
    /*  090 0x5A    "Z"         */  XmlCharType_NCNameStartChar1 | XmlCharType_AttributeDQuote | XmlCharType_AttributeSQuote | XmlCharType_Text | XmlCharType_CDATA | XmlCharType_Comment | XmlCharType_PI,
    /*  091 0x5B    "["         */  XmlCharType_NCNameInvalid | XmlCharType_AttributeDQuote | XmlCharType_AttributeSQuote | XmlCharType_Text | XmlCharType_CDATA | XmlCharType_Comment | XmlCharType_PI,
    /*  092 0x5C    "\"         */  XmlCharType_NCNameInvalid | XmlCharType_AttributeDQuote | XmlCharType_AttributeSQuote | XmlCharType_Text | XmlCharType_CDATA | XmlCharType_Comment | XmlCharType_PI,
    /*  093 0x5D    "]"         */  XmlCharType_NCNameInvalid | XmlCharType_AttributeDQuote | XmlCharType_AttributeSQuote | XmlCharType_Comment | XmlCharType_PI,
    /*  094 0x5E    "^"         */  XmlCharType_NCNameInvalid | XmlCharType_AttributeDQuote | XmlCharType_AttributeSQuote | XmlCharType_Text | XmlCharType_CDATA | XmlCharType_Comment | XmlCharType_PI,
    /*  095 0x5F    "_"         */  XmlCharType_NCNameStartChar1 | XmlCharType_AttributeDQuote | XmlCharType_AttributeSQuote | XmlCharType_Text | XmlCharType_CDATA | XmlCharType_Comment | XmlCharType_PI,
    /*  096 0x60    "`"         */  XmlCharType_NCNameInvalid | XmlCharType_AttributeDQuote | XmlCharType_AttributeSQuote | XmlCharType_Text | XmlCharType_CDATA | XmlCharType_Comment | XmlCharType_PI,
    /*  097 0x61    "a"         */  XmlCharType_NCNameStartChar1 | XmlCharType_AttributeDQuote | XmlCharType_AttributeSQuote | XmlCharType_Text | XmlCharType_CDATA | XmlCharType_Comment | XmlCharType_PI,
    /*  098 0x62    "b"         */  XmlCharType_NCNameStartChar1 | XmlCharType_AttributeDQuote | XmlCharType_AttributeSQuote | XmlCharType_Text | XmlCharType_CDATA | XmlCharType_Comment | XmlCharType_PI,
    /*  099 0x63    "c"         */  XmlCharType_NCNameStartChar1 | XmlCharType_AttributeDQuote | XmlCharType_AttributeSQuote | XmlCharType_Text | XmlCharType_CDATA | XmlCharType_Comment | XmlCharType_PI,
    /*  100 0x64    "d"         */  XmlCharType_NCNameStartChar1 | XmlCharType_AttributeDQuote | XmlCharType_AttributeSQuote | XmlCharType_Text | XmlCharType_CDATA | XmlCharType_Comment | XmlCharType_PI,
    /*  101 0x65    "e"         */  XmlCharType_NCNameStartChar1 | XmlCharType_AttributeDQuote | XmlCharType_AttributeSQuote | XmlCharType_Text | XmlCharType_CDATA | XmlCharType_Comment | XmlCharType_PI,
    /*  102 0x66    "f"         */  XmlCharType_NCNameStartChar1 | XmlCharType_AttributeDQuote | XmlCharType_AttributeSQuote | XmlCharType_Text | XmlCharType_CDATA | XmlCharType_Comment | XmlCharType_PI,
    /*  103 0x67    "g"         */  XmlCharType_NCNameStartChar1 | XmlCharType_AttributeDQuote | XmlCharType_AttributeSQuote | XmlCharType_Text | XmlCharType_CDATA | XmlCharType_Comment | XmlCharType_PI,
    /*  104 0x68    "h"         */  XmlCharType_NCNameStartChar1 | XmlCharType_AttributeDQuote | XmlCharType_AttributeSQuote | XmlCharType_Text | XmlCharType_CDATA | XmlCharType_Comment | XmlCharType_PI,
    /*  105 0x69    "i"         */  XmlCharType_NCNameStartChar1 | XmlCharType_AttributeDQuote | XmlCharType_AttributeSQuote | XmlCharType_Text | XmlCharType_CDATA | XmlCharType_Comment | XmlCharType_PI,
    /*  106 0x6A    "j"         */  XmlCharType_NCNameStartChar1 | XmlCharType_AttributeDQuote | XmlCharType_AttributeSQuote | XmlCharType_Text | XmlCharType_CDATA | XmlCharType_Comment | XmlCharType_PI,
    /*  107 0x6B    "k"         */  XmlCharType_NCNameStartChar1 | XmlCharType_AttributeDQuote | XmlCharType_AttributeSQuote | XmlCharType_Text | XmlCharType_CDATA | XmlCharType_Comment | XmlCharType_PI,
    /*  108 0x6C    "l"         */  XmlCharType_NCNameStartChar1 | XmlCharType_AttributeDQuote | XmlCharType_AttributeSQuote | XmlCharType_Text | XmlCharType_CDATA | XmlCharType_Comment | XmlCharType_PI,
    /*  109 0x6D    "m"         */  XmlCharType_NCNameStartChar1 | XmlCharType_AttributeDQuote | XmlCharType_AttributeSQuote | XmlCharType_Text | XmlCharType_CDATA | XmlCharType_Comment | XmlCharType_PI,
    /*  110 0x6E    "n"         */  XmlCharType_NCNameStartChar1 | XmlCharType_AttributeDQuote | XmlCharType_AttributeSQuote | XmlCharType_Text | XmlCharType_CDATA | XmlCharType_Comment | XmlCharType_PI,
    /*  111 0x6F    "o"         */  XmlCharType_NCNameStartChar1 | XmlCharType_AttributeDQuote | XmlCharType_AttributeSQuote | XmlCharType_Text | XmlCharType_CDATA | XmlCharType_Comment | XmlCharType_PI,
    /*  112 0x70    "p"         */  XmlCharType_NCNameStartChar1 | XmlCharType_AttributeDQuote | XmlCharType_AttributeSQuote | XmlCharType_Text | XmlCharType_CDATA | XmlCharType_Comment | XmlCharType_PI,
    /*  113 0x71    "q"         */  XmlCharType_NCNameStartChar1 | XmlCharType_AttributeDQuote | XmlCharType_AttributeSQuote | XmlCharType_Text | XmlCharType_CDATA | XmlCharType_Comment | XmlCharType_PI,
    /*  114 0x72    "r"         */  XmlCharType_NCNameStartChar1 | XmlCharType_AttributeDQuote | XmlCharType_AttributeSQuote | XmlCharType_Text | XmlCharType_CDATA | XmlCharType_Comment | XmlCharType_PI,
    /*  115 0x73    "s"         */  XmlCharType_NCNameStartChar1 | XmlCharType_AttributeDQuote | XmlCharType_AttributeSQuote | XmlCharType_Text | XmlCharType_CDATA | XmlCharType_Comment | XmlCharType_PI,
    /*  116 0x74    "t"         */  XmlCharType_NCNameStartChar1 | XmlCharType_AttributeDQuote | XmlCharType_AttributeSQuote | XmlCharType_Text | XmlCharType_CDATA | XmlCharType_Comment | XmlCharType_PI,
    /*  117 0x75    "u"         */  XmlCharType_NCNameStartChar1 | XmlCharType_AttributeDQuote | XmlCharType_AttributeSQuote | XmlCharType_Text | XmlCharType_CDATA | XmlCharType_Comment | XmlCharType_PI,
    /*  118 0x76    "v"         */  XmlCharType_NCNameStartChar1 | XmlCharType_AttributeDQuote | XmlCharType_AttributeSQuote | XmlCharType_Text | XmlCharType_CDATA | XmlCharType_Comment | XmlCharType_PI,
    /*  119 0x77    "w"         */  XmlCharType_NCNameStartChar1 | XmlCharType_AttributeDQuote | XmlCharType_AttributeSQuote | XmlCharType_Text | XmlCharType_CDATA | XmlCharType_Comment | XmlCharType_PI,
    /*  120 0x78    "x"         */  XmlCharType_NCNameStartChar1 | XmlCharType_AttributeDQuote | XmlCharType_AttributeSQuote | XmlCharType_Text | XmlCharType_CDATA | XmlCharType_Comment | XmlCharType_PI,
    /*  121 0x79    "y"         */  XmlCharType_NCNameStartChar1 | XmlCharType_AttributeDQuote | XmlCharType_AttributeSQuote | XmlCharType_Text | XmlCharType_CDATA | XmlCharType_Comment | XmlCharType_PI,
    /*  122 0x7A    "z"         */  XmlCharType_NCNameStartChar1 | XmlCharType_AttributeDQuote | XmlCharType_AttributeSQuote | XmlCharType_Text | XmlCharType_CDATA | XmlCharType_Comment | XmlCharType_PI,
    /*  123 0x7B    "{"         */  XmlCharType_NCNameInvalid | XmlCharType_AttributeDQuote | XmlCharType_AttributeSQuote | XmlCharType_Text | XmlCharType_CDATA | XmlCharType_Comment | XmlCharType_PI,
    /*  124 0x7C    "|"         */  XmlCharType_NCNameInvalid | XmlCharType_AttributeDQuote | XmlCharType_AttributeSQuote | XmlCharType_Text | XmlCharType_CDATA | XmlCharType_Comment | XmlCharType_PI,
    /*  125 0x7D    "}"         */  XmlCharType_NCNameInvalid | XmlCharType_AttributeDQuote | XmlCharType_AttributeSQuote | XmlCharType_Text | XmlCharType_CDATA | XmlCharType_Comment | XmlCharType_PI,
    /*  126 0x7E    "~"         */  XmlCharType_NCNameInvalid | XmlCharType_AttributeDQuote | XmlCharType_AttributeSQuote | XmlCharType_Text | XmlCharType_CDATA | XmlCharType_Comment | XmlCharType_PI,
    /*  127 0x7F    ""         */  XmlCharType_NCNameInvalid | XmlCharType_AttributeDQuote | XmlCharType_AttributeSQuote | XmlCharType_Text | XmlCharType_CDATA | XmlCharType_Comment | XmlCharType_PI,
    /*  128 0x80    multibyte   */  XmlCharType_NCNameInvalid | XmlCharType_AttributeDQuote | XmlCharType_AttributeSQuote | XmlCharType_Text | XmlCharType_CDATA | XmlCharType_Comment | XmlCharType_PI,
    /*  129 0x81    multibyte   */  XmlCharType_NCNameInvalid | XmlCharType_AttributeDQuote | XmlCharType_AttributeSQuote | XmlCharType_Text | XmlCharType_CDATA | XmlCharType_Comment | XmlCharType_PI,
    /*  130 0x82    multibyte   */  XmlCharType_NCNameInvalid | XmlCharType_AttributeDQuote | XmlCharType_AttributeSQuote | XmlCharType_Text | XmlCharType_CDATA | XmlCharType_Comment | XmlCharType_PI,
    /*  131 0x83    multibyte   */  XmlCharType_NCNameInvalid | XmlCharType_AttributeDQuote | XmlCharType_AttributeSQuote | XmlCharType_Text | XmlCharType_CDATA | XmlCharType_Comment | XmlCharType_PI,
    /*  132 0x84    multibyte   */  XmlCharType_NCNameInvalid | XmlCharType_AttributeDQuote | XmlCharType_AttributeSQuote | XmlCharType_Text | XmlCharType_CDATA | XmlCharType_Comment | XmlCharType_PI,
    /*  133 0x85    multibyte   */  XmlCharType_NCNameInvalid | XmlCharType_AttributeDQuote | XmlCharType_AttributeSQuote | XmlCharType_Text | XmlCharType_CDATA | XmlCharType_Comment | XmlCharType_PI,
    /*  134 0x86    multibyte   */  XmlCharType_NCNameInvalid | XmlCharType_AttributeDQuote | XmlCharType_AttributeSQuote | XmlCharType_Text | XmlCharType_CDATA | XmlCharType_Comment | XmlCharType_PI,
    /*  135 0x87    multibyte   */  XmlCharType_NCNameInvalid | XmlCharType_AttributeDQuote | XmlCharType_AttributeSQuote | XmlCharType_Text | XmlCharType_CDATA | XmlCharType_Comment | XmlCharType_PI,
    /*  136 0x88    multibyte   */  XmlCharType_NCNameInvalid | XmlCharType_AttributeDQuote | XmlCharType_AttributeSQuote | XmlCharType_Text | XmlCharType_CDATA | XmlCharType_Comment | XmlCharType_PI,
    /*  137 0x89    multibyte   */  XmlCharType_NCNameInvalid | XmlCharType_AttributeDQuote | XmlCharType_AttributeSQuote | XmlCharType_Text | XmlCharType_CDATA | XmlCharType_Comment | XmlCharType_PI,
    /*  138 0x8A    multibyte   */  XmlCharType_NCNameInvalid | XmlCharType_AttributeDQuote | XmlCharType_AttributeSQuote | XmlCharType_Text | XmlCharType_CDATA | XmlCharType_Comment | XmlCharType_PI,
    /*  139 0x8B    multibyte   */  XmlCharType_NCNameInvalid | XmlCharType_AttributeDQuote | XmlCharType_AttributeSQuote | XmlCharType_Text | XmlCharType_CDATA | XmlCharType_Comment | XmlCharType_PI,
    /*  140 0x8C    multibyte   */  XmlCharType_NCNameInvalid | XmlCharType_AttributeDQuote | XmlCharType_AttributeSQuote | XmlCharType_Text | XmlCharType_CDATA | XmlCharType_Comment | XmlCharType_PI,
    /*  141 0x8D    multibyte   */  XmlCharType_NCNameInvalid | XmlCharType_AttributeDQuote | XmlCharType_AttributeSQuote | XmlCharType_Text | XmlCharType_CDATA | XmlCharType_Comment | XmlCharType_PI,
    /*  142 0x8E    multibyte   */  XmlCharType_NCNameInvalid | XmlCharType_AttributeDQuote | XmlCharType_AttributeSQuote | XmlCharType_Text | XmlCharType_CDATA | XmlCharType_Comment | XmlCharType_PI,
    /*  143 0x8F    multibyte   */  XmlCharType_NCNameInvalid | XmlCharType_AttributeDQuote | XmlCharType_AttributeSQuote | XmlCharType_Text | XmlCharType_CDATA | XmlCharType_Comment | XmlCharType_PI,
    /*  144 0x90    multibyte   */  XmlCharType_NCNameInvalid | XmlCharType_AttributeDQuote | XmlCharType_AttributeSQuote | XmlCharType_Text | XmlCharType_CDATA | XmlCharType_Comment | XmlCharType_PI,
    /*  145 0x91    multibyte   */  XmlCharType_NCNameInvalid | XmlCharType_AttributeDQuote | XmlCharType_AttributeSQuote | XmlCharType_Text | XmlCharType_CDATA | XmlCharType_Comment | XmlCharType_PI,
    /*  146 0x92    multibyte   */  XmlCharType_NCNameInvalid | XmlCharType_AttributeDQuote | XmlCharType_AttributeSQuote | XmlCharType_Text | XmlCharType_CDATA | XmlCharType_Comment | XmlCharType_PI,
    /*  147 0x93    multibyte   */  XmlCharType_NCNameInvalid | XmlCharType_AttributeDQuote | XmlCharType_AttributeSQuote | XmlCharType_Text | XmlCharType_CDATA | XmlCharType_Comment | XmlCharType_PI,
    /*  148 0x94    multibyte   */  XmlCharType_NCNameInvalid | XmlCharType_AttributeDQuote | XmlCharType_AttributeSQuote | XmlCharType_Text | XmlCharType_CDATA | XmlCharType_Comment | XmlCharType_PI,
    /*  149 0x95    multibyte   */  XmlCharType_NCNameInvalid | XmlCharType_AttributeDQuote | XmlCharType_AttributeSQuote | XmlCharType_Text | XmlCharType_CDATA | XmlCharType_Comment | XmlCharType_PI,
    /*  150 0x96    multibyte   */  XmlCharType_NCNameInvalid | XmlCharType_AttributeDQuote | XmlCharType_AttributeSQuote | XmlCharType_Text | XmlCharType_CDATA | XmlCharType_Comment | XmlCharType_PI,
    /*  151 0x97    multibyte   */  XmlCharType_NCNameInvalid | XmlCharType_AttributeDQuote | XmlCharType_AttributeSQuote | XmlCharType_Text | XmlCharType_CDATA | XmlCharType_Comment | XmlCharType_PI,
    /*  152 0x98    multibyte   */  XmlCharType_NCNameInvalid | XmlCharType_AttributeDQuote | XmlCharType_AttributeSQuote | XmlCharType_Text | XmlCharType_CDATA | XmlCharType_Comment | XmlCharType_PI,
    /*  153 0x99    multibyte   */  XmlCharType_NCNameInvalid | XmlCharType_AttributeDQuote | XmlCharType_AttributeSQuote | XmlCharType_Text | XmlCharType_CDATA | XmlCharType_Comment | XmlCharType_PI,
    /*  154 0x9A    multibyte   */  XmlCharType_NCNameInvalid | XmlCharType_AttributeDQuote | XmlCharType_AttributeSQuote | XmlCharType_Text | XmlCharType_CDATA | XmlCharType_Comment | XmlCharType_PI,
    /*  155 0x9B    multibyte   */  XmlCharType_NCNameInvalid | XmlCharType_AttributeDQuote | XmlCharType_AttributeSQuote | XmlCharType_Text | XmlCharType_CDATA | XmlCharType_Comment | XmlCharType_PI,
    /*  156 0x9C    multibyte   */  XmlCharType_NCNameInvalid | XmlCharType_AttributeDQuote | XmlCharType_AttributeSQuote | XmlCharType_Text | XmlCharType_CDATA | XmlCharType_Comment | XmlCharType_PI,
    /*  157 0x9D    multibyte   */  XmlCharType_NCNameInvalid | XmlCharType_AttributeDQuote | XmlCharType_AttributeSQuote | XmlCharType_Text | XmlCharType_CDATA | XmlCharType_Comment | XmlCharType_PI,
    /*  158 0x9E    multibyte   */  XmlCharType_NCNameInvalid | XmlCharType_AttributeDQuote | XmlCharType_AttributeSQuote | XmlCharType_Text | XmlCharType_CDATA | XmlCharType_Comment | XmlCharType_PI,
    /*  159 0x9F    multibyte   */  XmlCharType_NCNameInvalid | XmlCharType_AttributeDQuote | XmlCharType_AttributeSQuote | XmlCharType_Text | XmlCharType_CDATA | XmlCharType_Comment | XmlCharType_PI,
    /*  160 0xA0    multibyte   */  XmlCharType_NCNameInvalid | XmlCharType_AttributeDQuote | XmlCharType_AttributeSQuote | XmlCharType_Text | XmlCharType_CDATA | XmlCharType_Comment | XmlCharType_PI,
    /*  161 0xA1    multibyte   */  XmlCharType_NCNameInvalid | XmlCharType_AttributeDQuote | XmlCharType_AttributeSQuote | XmlCharType_Text | XmlCharType_CDATA | XmlCharType_Comment | XmlCharType_PI,
    /*  162 0xA2    multibyte   */  XmlCharType_NCNameInvalid | XmlCharType_AttributeDQuote | XmlCharType_AttributeSQuote | XmlCharType_Text | XmlCharType_CDATA | XmlCharType_Comment | XmlCharType_PI,
    /*  163 0xA3    multibyte   */  XmlCharType_NCNameInvalid | XmlCharType_AttributeDQuote | XmlCharType_AttributeSQuote | XmlCharType_Text | XmlCharType_CDATA | XmlCharType_Comment | XmlCharType_PI,
    /*  164 0xA4    multibyte   */  XmlCharType_NCNameInvalid | XmlCharType_AttributeDQuote | XmlCharType_AttributeSQuote | XmlCharType_Text | XmlCharType_CDATA | XmlCharType_Comment | XmlCharType_PI,
    /*  165 0xA5    multibyte   */  XmlCharType_NCNameInvalid | XmlCharType_AttributeDQuote | XmlCharType_AttributeSQuote | XmlCharType_Text | XmlCharType_CDATA | XmlCharType_Comment | XmlCharType_PI,
    /*  166 0xA6    multibyte   */  XmlCharType_NCNameInvalid | XmlCharType_AttributeDQuote | XmlCharType_AttributeSQuote | XmlCharType_Text | XmlCharType_CDATA | XmlCharType_Comment | XmlCharType_PI,
    /*  167 0xA7    multibyte   */  XmlCharType_NCNameInvalid | XmlCharType_AttributeDQuote | XmlCharType_AttributeSQuote | XmlCharType_Text | XmlCharType_CDATA | XmlCharType_Comment | XmlCharType_PI,
    /*  168 0xA8    multibyte   */  XmlCharType_NCNameInvalid | XmlCharType_AttributeDQuote | XmlCharType_AttributeSQuote | XmlCharType_Text | XmlCharType_CDATA | XmlCharType_Comment | XmlCharType_PI,
    /*  169 0xA9    multibyte   */  XmlCharType_NCNameInvalid | XmlCharType_AttributeDQuote | XmlCharType_AttributeSQuote | XmlCharType_Text | XmlCharType_CDATA | XmlCharType_Comment | XmlCharType_PI,
    /*  170 0xAA    multibyte   */  XmlCharType_NCNameInvalid | XmlCharType_AttributeDQuote | XmlCharType_AttributeSQuote | XmlCharType_Text | XmlCharType_CDATA | XmlCharType_Comment | XmlCharType_PI,
    /*  171 0xAB    multibyte   */  XmlCharType_NCNameInvalid | XmlCharType_AttributeDQuote | XmlCharType_AttributeSQuote | XmlCharType_Text | XmlCharType_CDATA | XmlCharType_Comment | XmlCharType_PI,
    /*  172 0xAC    multibyte   */  XmlCharType_NCNameInvalid | XmlCharType_AttributeDQuote | XmlCharType_AttributeSQuote | XmlCharType_Text | XmlCharType_CDATA | XmlCharType_Comment | XmlCharType_PI,
    /*  173 0xAD    multibyte   */  XmlCharType_NCNameInvalid | XmlCharType_AttributeDQuote | XmlCharType_AttributeSQuote | XmlCharType_Text | XmlCharType_CDATA | XmlCharType_Comment | XmlCharType_PI,
    /*  174 0xAE    multibyte   */  XmlCharType_NCNameInvalid | XmlCharType_AttributeDQuote | XmlCharType_AttributeSQuote | XmlCharType_Text | XmlCharType_CDATA | XmlCharType_Comment | XmlCharType_PI,
    /*  175 0xAF    multibyte   */  XmlCharType_NCNameInvalid | XmlCharType_AttributeDQuote | XmlCharType_AttributeSQuote | XmlCharType_Text | XmlCharType_CDATA | XmlCharType_Comment | XmlCharType_PI,
    /*  176 0xB0    multibyte   */  XmlCharType_NCNameInvalid | XmlCharType_AttributeDQuote | XmlCharType_AttributeSQuote | XmlCharType_Text | XmlCharType_CDATA | XmlCharType_Comment | XmlCharType_PI,
    /*  177 0xB1    multibyte   */  XmlCharType_NCNameInvalid | XmlCharType_AttributeDQuote | XmlCharType_AttributeSQuote | XmlCharType_Text | XmlCharType_CDATA | XmlCharType_Comment | XmlCharType_PI,
    /*  178 0xB2    multibyte   */  XmlCharType_NCNameInvalid | XmlCharType_AttributeDQuote | XmlCharType_AttributeSQuote | XmlCharType_Text | XmlCharType_CDATA | XmlCharType_Comment | XmlCharType_PI,
    /*  179 0xB3    multibyte   */  XmlCharType_NCNameInvalid | XmlCharType_AttributeDQuote | XmlCharType_AttributeSQuote | XmlCharType_Text | XmlCharType_CDATA | XmlCharType_Comment | XmlCharType_PI,
    /*  180 0xB4    multibyte   */  XmlCharType_NCNameInvalid | XmlCharType_AttributeDQuote | XmlCharType_AttributeSQuote | XmlCharType_Text | XmlCharType_CDATA | XmlCharType_Comment | XmlCharType_PI,
    /*  181 0xB5    multibyte   */  XmlCharType_NCNameInvalid | XmlCharType_AttributeDQuote | XmlCharType_AttributeSQuote | XmlCharType_Text | XmlCharType_CDATA | XmlCharType_Comment | XmlCharType_PI,
    /*  182 0xB6    multibyte   */  XmlCharType_NCNameInvalid | XmlCharType_AttributeDQuote | XmlCharType_AttributeSQuote | XmlCharType_Text | XmlCharType_CDATA | XmlCharType_Comment | XmlCharType_PI,
    /*  183 0xB7    multibyte   */  XmlCharType_NCNameInvalid | XmlCharType_AttributeDQuote | XmlCharType_AttributeSQuote | XmlCharType_Text | XmlCharType_CDATA | XmlCharType_Comment | XmlCharType_PI,
    /*  184 0xB8    multibyte   */  XmlCharType_NCNameInvalid | XmlCharType_AttributeDQuote | XmlCharType_AttributeSQuote | XmlCharType_Text | XmlCharType_CDATA | XmlCharType_Comment | XmlCharType_PI,
    /*  185 0xB9    multibyte   */  XmlCharType_NCNameInvalid | XmlCharType_AttributeDQuote | XmlCharType_AttributeSQuote | XmlCharType_Text | XmlCharType_CDATA | XmlCharType_Comment | XmlCharType_PI,
    /*  186 0xBA    multibyte   */  XmlCharType_NCNameInvalid | XmlCharType_AttributeDQuote | XmlCharType_AttributeSQuote | XmlCharType_Text | XmlCharType_CDATA | XmlCharType_Comment | XmlCharType_PI,
    /*  187 0xBB    multibyte   */  XmlCharType_NCNameInvalid | XmlCharType_AttributeDQuote | XmlCharType_AttributeSQuote | XmlCharType_Text | XmlCharType_CDATA | XmlCharType_Comment | XmlCharType_PI,
    /*  188 0xBC    multibyte   */  XmlCharType_NCNameInvalid | XmlCharType_AttributeDQuote | XmlCharType_AttributeSQuote | XmlCharType_Text | XmlCharType_CDATA | XmlCharType_Comment | XmlCharType_PI,
    /*  189 0xBD    multibyte   */  XmlCharType_NCNameInvalid | XmlCharType_AttributeDQuote | XmlCharType_AttributeSQuote | XmlCharType_Text | XmlCharType_CDATA | XmlCharType_Comment | XmlCharType_PI,
    /*  190 0xBE    multibyte   */  XmlCharType_NCNameInvalid | XmlCharType_AttributeDQuote | XmlCharType_AttributeSQuote | XmlCharType_Text | XmlCharType_CDATA | XmlCharType_Comment | XmlCharType_PI,
    /*  191 0xBF    multibyte   */  XmlCharType_NCNameInvalid | XmlCharType_AttributeDQuote | XmlCharType_AttributeSQuote | XmlCharType_Text | XmlCharType_CDATA | XmlCharType_Comment | XmlCharType_PI,
    /*  192 0xC0    illegal     */  XmlCharType_NCNameInvalid | XmlCharType_None,
    /*  193 0xC1    illegal     */  XmlCharType_NCNameInvalid | XmlCharType_None,
    /*  194 0xC2    0080-00BF   */  XmlCharType_NCNameChar2Maybe | XmlCharType_AttributeDQuote | XmlCharType_AttributeSQuote | XmlCharType_Text | XmlCharType_CDATA | XmlCharType_Comment | XmlCharType_PI,
    /*  195 0xC3    00C0-00FF   */  XmlCharType_NCNameChar2Maybe | XmlCharType_AttributeDQuote | XmlCharType_AttributeSQuote | XmlCharType_Text | XmlCharType_CDATA | XmlCharType_Comment | XmlCharType_PI,
    /*  196 0xC4    0100-013F   */  XmlCharType_NCNameChar2 | XmlCharType_AttributeDQuote | XmlCharType_AttributeSQuote | XmlCharType_Text | XmlCharType_CDATA | XmlCharType_Comment | XmlCharType_PI,
    /*  197 0xC5    0140-017F   */  XmlCharType_NCNameChar2 | XmlCharType_AttributeDQuote | XmlCharType_AttributeSQuote | XmlCharType_Text | XmlCharType_CDATA | XmlCharType_Comment | XmlCharType_PI,
    /*  198 0xC6    0180-01BF   */  XmlCharType_NCNameChar2 | XmlCharType_AttributeDQuote | XmlCharType_AttributeSQuote | XmlCharType_Text | XmlCharType_CDATA | XmlCharType_Comment | XmlCharType_PI,
    /*  199 0xC7    01C0-01FF   */  XmlCharType_NCNameChar2 | XmlCharType_AttributeDQuote | XmlCharType_AttributeSQuote | XmlCharType_Text | XmlCharType_CDATA | XmlCharType_Comment | XmlCharType_PI,
    /*  200 0xC8    0200-023F   */  XmlCharType_NCNameChar2 | XmlCharType_AttributeDQuote | XmlCharType_AttributeSQuote | XmlCharType_Text | XmlCharType_CDATA | XmlCharType_Comment | XmlCharType_PI,
    /*  201 0xC9    0240-027F   */  XmlCharType_NCNameChar2 | XmlCharType_AttributeDQuote | XmlCharType_AttributeSQuote | XmlCharType_Text | XmlCharType_CDATA | XmlCharType_Comment | XmlCharType_PI,
    /*  202 0xCA    0280-02BF   */  XmlCharType_NCNameChar2 | XmlCharType_AttributeDQuote | XmlCharType_AttributeSQuote | XmlCharType_Text | XmlCharType_CDATA | XmlCharType_Comment | XmlCharType_PI,
    /*  203 0xCB    02C0-02FF   */  XmlCharType_NCNameChar2 | XmlCharType_AttributeDQuote | XmlCharType_AttributeSQuote | XmlCharType_Text | XmlCharType_CDATA | XmlCharType_Comment | XmlCharType_PI,
    /*  204 0xCC    0300-033F   */  XmlCharType_NCNameChar2Maybe | XmlCharType_AttributeDQuote | XmlCharType_AttributeSQuote | XmlCharType_Text | XmlCharType_CDATA | XmlCharType_Comment | XmlCharType_PI,
    /*  205 0xCD    0340-037F   */  XmlCharType_NCNameChar2Maybe | XmlCharType_AttributeDQuote | XmlCharType_AttributeSQuote | XmlCharType_Text | XmlCharType_CDATA | XmlCharType_Comment | XmlCharType_PI,
    /*  206 0xCE    0380-03BF   */  XmlCharType_NCNameChar2 | XmlCharType_AttributeDQuote | XmlCharType_AttributeSQuote | XmlCharType_Text | XmlCharType_CDATA | XmlCharType_Comment | XmlCharType_PI,
    /*  207 0xCF    03C0-03FF   */  XmlCharType_NCNameChar2 | XmlCharType_AttributeDQuote | XmlCharType_AttributeSQuote | XmlCharType_Text | XmlCharType_CDATA | XmlCharType_Comment | XmlCharType_PI,
    /*  208 0xD0    0400-043F   */  XmlCharType_NCNameChar2 | XmlCharType_AttributeDQuote | XmlCharType_AttributeSQuote | XmlCharType_Text | XmlCharType_CDATA | XmlCharType_Comment | XmlCharType_PI,
    /*  209 0xD1    0440-047F   */  XmlCharType_NCNameChar2 | XmlCharType_AttributeDQuote | XmlCharType_AttributeSQuote | XmlCharType_Text | XmlCharType_CDATA | XmlCharType_Comment | XmlCharType_PI,
    /*  210 0xD2    0480-04BF   */  XmlCharType_NCNameChar2 | XmlCharType_AttributeDQuote | XmlCharType_AttributeSQuote | XmlCharType_Text | XmlCharType_CDATA | XmlCharType_Comment | XmlCharType_PI,
    /*  211 0xD3    04C0-04FF   */  XmlCharType_NCNameChar2 | XmlCharType_AttributeDQuote | XmlCharType_AttributeSQuote | XmlCharType_Text | XmlCharType_CDATA | XmlCharType_Comment | XmlCharType_PI,
    /*  212 0xD4    0500-053F   */  XmlCharType_NCNameChar2 | XmlCharType_AttributeDQuote | XmlCharType_AttributeSQuote | XmlCharType_Text | XmlCharType_CDATA | XmlCharType_Comment | XmlCharType_PI,
    /*  213 0xD5    0540-057F   */  XmlCharType_NCNameChar2 | XmlCharType_AttributeDQuote | XmlCharType_AttributeSQuote | XmlCharType_Text | XmlCharType_CDATA | XmlCharType_Comment | XmlCharType_PI,
    /*  214 0xD6    0580-05BF   */  XmlCharType_NCNameChar2 | XmlCharType_AttributeDQuote | XmlCharType_AttributeSQuote | XmlCharType_Text | XmlCharType_CDATA | XmlCharType_Comment | XmlCharType_PI,
    /*  215 0xD7    05C0-05FF   */  XmlCharType_NCNameChar2 | XmlCharType_AttributeDQuote | XmlCharType_AttributeSQuote | XmlCharType_Text | XmlCharType_CDATA | XmlCharType_Comment | XmlCharType_PI,
    /*  216 0xD8    0600-063F   */  XmlCharType_NCNameChar2 | XmlCharType_AttributeDQuote | XmlCharType_AttributeSQuote | XmlCharType_Text | XmlCharType_CDATA | XmlCharType_Comment | XmlCharType_PI,
    /*  217 0xD9    0640-067F   */  XmlCharType_NCNameChar2 | XmlCharType_AttributeDQuote | XmlCharType_AttributeSQuote | XmlCharType_Text | XmlCharType_CDATA | XmlCharType_Comment | XmlCharType_PI,
    /*  218 0xDA    0680-06BF   */  XmlCharType_NCNameChar2 | XmlCharType_AttributeDQuote | XmlCharType_AttributeSQuote | XmlCharType_Text | XmlCharType_CDATA | XmlCharType_Comment | XmlCharType_PI,
    /*  219 0xDB    06C0-06FF   */  XmlCharType_NCNameChar2 | XmlCharType_AttributeDQuote | XmlCharType_AttributeSQuote | XmlCharType_Text | XmlCharType_CDATA | XmlCharType_Comment | XmlCharType_PI,
    /*  220 0xDC    0700-073F   */  XmlCharType_NCNameChar2 | XmlCharType_AttributeDQuote | XmlCharType_AttributeSQuote | XmlCharType_Text | XmlCharType_CDATA | XmlCharType_Comment | XmlCharType_PI,
    /*  221 0xDD    0740-077F   */  XmlCharType_NCNameChar2 | XmlCharType_AttributeDQuote | XmlCharType_AttributeSQuote | XmlCharType_Text | XmlCharType_CDATA | XmlCharType_Comment | XmlCharType_PI,
    /*  222 0xDE    0780-07BF   */  XmlCharType_NCNameChar2 | XmlCharType_AttributeDQuote | XmlCharType_AttributeSQuote | XmlCharType_Text | XmlCharType_CDATA | XmlCharType_Comment | XmlCharType_PI,
    /*  223 0xDF    07C0-07FF   */  XmlCharType_NCNameChar2 | XmlCharType_AttributeDQuote | XmlCharType_AttributeSQuote | XmlCharType_Text | XmlCharType_CDATA | XmlCharType_Comment | XmlCharType_PI,
    /*  224 0xE0    0000-0FFF   */  XmlCharType_NCNameChar3Maybe | XmlCharType_AttributeDQuote | XmlCharType_AttributeSQuote | XmlCharType_Text | XmlCharType_CDATA | XmlCharType_Comment | XmlCharType_PI,
    /*  225 0xE1    1000-1FFF   */  XmlCharType_NCNameChar3 | XmlCharType_AttributeDQuote | XmlCharType_AttributeSQuote | XmlCharType_Text | XmlCharType_CDATA | XmlCharType_Comment | XmlCharType_PI,
    /*  226 0xE2    2000-2FFF   */  XmlCharType_NCNameChar3Maybe | XmlCharType_AttributeDQuote | XmlCharType_AttributeSQuote | XmlCharType_Text | XmlCharType_CDATA | XmlCharType_Comment | XmlCharType_PI,
    /*  227 0xE3    3000-3FFF   */  XmlCharType_NCNameChar3Maybe | XmlCharType_AttributeDQuote | XmlCharType_AttributeSQuote | XmlCharType_Text | XmlCharType_CDATA | XmlCharType_Comment | XmlCharType_PI,
    /*  228 0xE4    4000-4FFF   */  XmlCharType_NCNameChar3 | XmlCharType_AttributeDQuote | XmlCharType_AttributeSQuote | XmlCharType_Text | XmlCharType_CDATA | XmlCharType_Comment | XmlCharType_PI,
    /*  229 0xE5    5000-5FFF   */  XmlCharType_NCNameChar3 | XmlCharType_AttributeDQuote | XmlCharType_AttributeSQuote | XmlCharType_Text | XmlCharType_CDATA | XmlCharType_Comment | XmlCharType_PI,
    /*  230 0xE6    6000-6FFF   */  XmlCharType_NCNameChar3 | XmlCharType_AttributeDQuote | XmlCharType_AttributeSQuote | XmlCharType_Text | XmlCharType_CDATA | XmlCharType_Comment | XmlCharType_PI,
    /*  231 0xE7    7000-7FFF   */  XmlCharType_NCNameChar3 | XmlCharType_AttributeDQuote | XmlCharType_AttributeSQuote | XmlCharType_Text | XmlCharType_CDATA | XmlCharType_Comment | XmlCharType_PI,
    /*  232 0xE8    8000-8FFF   */  XmlCharType_NCNameChar3 | XmlCharType_AttributeDQuote | XmlCharType_AttributeSQuote | XmlCharType_Text | XmlCharType_CDATA | XmlCharType_Comment | XmlCharType_PI,
    /*  233 0xE9    9000-9FFF   */  XmlCharType_NCNameChar3 | XmlCharType_AttributeDQuote | XmlCharType_AttributeSQuote | XmlCharType_Text | XmlCharType_CDATA | XmlCharType_Comment | XmlCharType_PI,
    /*  234 0xEA    A000-AFFF   */  XmlCharType_NCNameChar3 | XmlCharType_AttributeDQuote | XmlCharType_AttributeSQuote | XmlCharType_Text | XmlCharType_CDATA | XmlCharType_Comment | XmlCharType_PI,
    /*  235 0xEB    B000-BFFF   */  XmlCharType_NCNameChar3 | XmlCharType_AttributeDQuote | XmlCharType_AttributeSQuote | XmlCharType_Text | XmlCharType_CDATA | XmlCharType_Comment | XmlCharType_PI,
    /*  236 0xEC    C000-CFFF   */  XmlCharType_NCNameChar3 | XmlCharType_AttributeDQuote | XmlCharType_AttributeSQuote | XmlCharType_Text | XmlCharType_CDATA | XmlCharType_Comment | XmlCharType_PI,
    /*  237 0xED    D000-DFFF   */  XmlCharType_NCNameChar3Maybe | XmlCharType_AttributeDQuote | XmlCharType_AttributeSQuote | XmlCharType_Text | XmlCharType_CDATA | XmlCharType_Comment | XmlCharType_PI,
    /*  238 0xEE    E000-EFFF   */  XmlCharType_NCNameInvalid | XmlCharType_AttributeDQuote | XmlCharType_AttributeSQuote | XmlCharType_Text | XmlCharType_CDATA | XmlCharType_Comment | XmlCharType_PI,
    /*  239 0xEF    F000-FFFF   */  XmlCharType_NCNameChar3Maybe | XmlCharType_AttributeDQuote | XmlCharType_AttributeSQuote | XmlCharType_Text | XmlCharType_CDATA | XmlCharType_Comment | XmlCharType_PI,
    /*  240 0xF0    illegal     */  XmlCharType_NCNameInvalid | XmlCharType_None,
    /*  241 0xF1    illegal     */  XmlCharType_NCNameInvalid | XmlCharType_None,
    /*  242 0xF2    illegal     */  XmlCharType_NCNameInvalid | XmlCharType_None,
    /*  243 0xF3    illegal     */  XmlCharType_NCNameInvalid | XmlCharType_None,
    /*  244 0xF4    illegal     */  XmlCharType_NCNameInvalid | XmlCharType_None,
    /*  245 0xF5    illegal     */  XmlCharType_NCNameInvalid | XmlCharType_None,
    /*  246 0xF6    illegal     */  XmlCharType_NCNameInvalid | XmlCharType_None,
    /*  247 0xF7    illegal     */  XmlCharType_NCNameInvalid | XmlCharType_None,
    /*  248 0xF8    illegal     */  XmlCharType_NCNameInvalid | XmlCharType_None,
    /*  249 0xF9    illegal     */  XmlCharType_NCNameInvalid | XmlCharType_None,
    /*  250 0xFA    illegal     */  XmlCharType_NCNameInvalid | XmlCharType_None,
    /*  251 0xFB    illegal     */  XmlCharType_NCNameInvalid | XmlCharType_None,
    /*  252 0xFC    illegal     */  XmlCharType_NCNameInvalid | XmlCharType_None,
    /*  253 0xFD    illegal     */  XmlCharType_NCNameInvalid | XmlCharType_None,
    /*  254 0xFE    illegal     */  XmlCharType_NCNameInvalid | XmlCharType_None,
    /*  255 0xFF    illegal     */  XmlCharType_NCNameInvalid | XmlCharType_None,
};

